from work.authored_helpers import *
k='400b364bd022913e96a1667f7813381261290d744a3eabad6ca70a15efc77a52'
save(k,[dict(quote='Oracle announced that its Board of Directors has declared a cash dividend of $0.40 per share of outstanding common stock payable on October 24, 2024',stage='signed',model_quantity='dividend_declared_future_payment',flag_unknown_reason='exact_declaration_date_unknown'),abstention('to stockholders of record as of the close of business on October 10, 2024.','Full item/section boundary read. Future dividend/record date not actual issuer cash or funding.')])
k='ed13da72376acfd58bc2d9b09f4aa784316d3d45a9629043761eab9508ced219'
save(k,[dict(quote='On September 5, 2024, the Company announced that the Board of Directors has declared a quarterly cash dividend on the Company’s common stock of $0.53 per share.',event_date='2024-09-05',stage='signed',model_quantity='dividend_declared_future_payment'),abstention('This dividend is payable on September 30, 2024','Full item/record time/date read. Prospective dividend not actual aggregate cash payment or financing.')])
k='7ffc423547bc1d14d350bf0cfc3ec2e8955c2e11f7b97e2f09b707b603149e39'
rows=[dict(quote='On August 17, 2024 (the “Signing Date”), Advanced Micro Devices, Inc., a Delaware corporation (“Buyer”), entered into a Stock Purchase Agreement (the “Agreement”) with ZT Group Int’l, Inc., a New Jersey corporation',event_date='2024-08-17',stage='signed',counterparty='ZT Group Int’l, Inc.',counterparty_evidence='named',model_quantity='ZT_stock_purchase_signed_legal_parties_jurisdictions',flag_unknown_reason='pending_acquisition_not_consolidation_target_or_selling_stockholders_cash_receipt_not_equivalent')]
for quote,num,scale,qual,q,nature in [('an equity value for all outstanding equity interests of the Company of up to $4.9 billion','4.9','1000000000','up_to','ZT_purchase_maximum_equity_consideration','mixed_cash_stock_and_conditional_consideration_not_all_cash'),('$1.125 billion','1.125','1000000000','exact','ZT_purchase_fixed_buyer_stock_reference_value','stock_valuation_component_not_cash_or_primary_target_funding'),('$3.375 billion in the form of cash payable to the Sellers, the Company Warrant Holders and the holders of Company RSUs','3.375','1000000000','exact','ZT_purchase_fixed_planned_cash_consideration','planned_cash_to_selling_security_holders_not_paid'),('a maximum of $100 million','100','1000000','up_to','ZT_purchase_contingent_buyer_stock_reference_cap','conditional_stock_reference_value_not_cash'),('up to $300 million of cash','300','1000000','up_to','ZT_purchase_contingent_cash_cap','conditional_cash_earnout_not_paid')]:
 rows.append(money(quote,num,scale,'selling_security_holders',counterparty_evidence='anonymous',payer='Advanced Micro Devices, Inc.',event_date='2024-08-17',stage='signed',amount_qualifier=qual,model_quantity=q,amount_nature=nature,flag_unknown_reason='components_of_4_9bn_maximum_not_additional_flows_no_actual_close'))
for quote,num,qual,q in [('8,335,852 shares of Buyer common stock','8335852','exact','ZT_purchase_fixed_planned_buyer_shares'),('up to 740,964 shares of Buyer Stock','740964','up_to','ZT_purchase_contingent_buyer_share_cap')]:
 rows.append(dict(quote=quote,amount=num,unit='http://www.xbrl.org/2003/instance:shares',amount_origin='narrative_only',amount_qualifier=qual,event_date='2024-08-17',stage='signed',model_quantity=q,amount_nature='planned_buyer_stock_consideration_not_actual_issued_shares_or_USD_cash'))
rows.extend([money('Buyer will be required to pay a termination fee to the Company equal to $300 million','300','1000000','ZT Group Int’l, Inc.',payer='Advanced Micro Devices, Inc.',receiver='ZT Group Int’l, Inc.',event_date='2024-08-17',stage='signed',amount_qualifier='exact',conditionality='conditional',trigger_description='if the Agreement is terminated in certain circumstances related to the failure to obtain certain regulatory approvals prior to the Outside Date.',model_quantity='ZT_purchase_conditional_regulatory_termination_fee',amount_nature='conditional_fee_not_actual_cash_or_guarantee_called'),abstention('The obligation of the parties to consummate the transactions contemplated by the Agreement is subject to the satisfaction or waiver of a number of customary conditions','Full item: full legal parties/jurisdictions, shareholder sale, all fixed/contingent stock/cash and VWAP share calculations, all closing/termination/extension/fee conditions, securities exemptions/resale, exhibits and all representation limitations read. No actual close, consolidated target, cash/stock issued, primary target financing, invoked fee or F4 financial waiver/F9 capacity termination. Commercial closing-condition waiver not financial-covenant waiver; later close not imported.')])
save(k,rows)
