from work.authored_helpers import *
k='64ff51a6e3d9bdec7a86169cc38f23aba0de4f9f294de3080045d350afc63682'
save(k,[authored_control(k,'were effective to provide reasonable assurance that the information required to be disclosed by us','disclosure_controls_effective',event_present=True),authored_control(k,'There were no changes in our internal control over financial reporting that occurred during our last fiscal quarter','no_material_ICFR_change_quarter',flag_unknown_reason='generic_limits_not_MW')])
k='f9364038cdbfe38c01b47be98ebae031357dd00741b5d5085f6a52faaf487178'
rows=repeat_chosen_rows('dd201e7e5e97fbf6f12ff180c3efe0c1cc13e068004d4d7fb9d92627ee4a9fed',['issuer_legal_name_jurisdiction','consolidation_scope','intercompany_elimination','presentation_reclassification'])
rows += [dict(quote='Fiscal 2021 had a 52-week year. Fiscal 2022 is a 52-week year.',model_quantity='fiscal_calendar'),dict(quote='On April 20, 2021, the Company completed its acquisition of Inphi Corporation (“Inphi”).',model_quantity='Inphi_acquisition_completed',event_date='2021-04-20',counterparty='Inphi Corporation',counterparty_evidence='named',stage='recognized',flag_unknown_reason='no_amount_here'),dict(quote='Marvell Technology Group Ltd. and Inphi became wholly owned subsidiaries of the new parent company, MTI, on April 20, 2021.',model_quantity='new_parent_predecessor_and_Inphi_wholly_owned',event_date='2021-04-20',basis_break=True,recast_cause='unknown',flag_unknown_reason='legal_successor_not_automatic_retroactive_combination'),dict(quote='include the operating results of Inphi for the period from the date of acquisition through the Company’s third quarter ended October 30, 2021.',model_quantity='Inphi_prospective_consolidation',basis_break=True,recast_cause='unknown'),dict(quote='On October 5, 2021, the Company completed its acquisition of Innovium, Inc. (“Innovium”), a leading provider of networking solutions for cloud and edge data centers, in an all-stock transaction.',model_quantity='Innovium_acquisition_completed_all_stock',event_date='2021-10-05',counterparty='Innovium, Inc.',counterparty_evidence='named',stage='recognized',flag_unknown_reason='not_cash_no_amount_here'),dict(quote='include the operating results of Innovium for the period from the date of acquisition through the Company’s third quarter ended October 30, 2021.',model_quantity='Innovium_prospective_consolidation',basis_break=True,recast_cause='unknown'),abstention('As events continue to evolve and additional information becomes available, these estimates may change materially in future periods.','Complete note no substantial doubt or actual investment impairment or equipment life change.')]
save(k,rows)
k='eba2d456f5504b47bcbc45809e5dce1cf481454ca281bdf0d82cf4a8f4bee5b5'
save(k,[authored_control(k,'our disclosure controls and procedures were effective.','disclosure_controls_effective',event_present=True),authored_control(k,'There have been no changes in our internal control over financial reporting during the three months ended October 30, 2021','no_material_ICFR_change_quarter',flag_unknown_reason='COVID_remote_work_generic_limits_not_MW')])
