from authored_helpers import save,money as m
cp='GLOBALFOUNDRIES Inc.'
rows=[]
q='The Company’s total purchases from GF related to wafer manufacturing, research and development activities and other for the quarters ended September 29, 2018 and September 30, 2017 were $377 million and $331 million, respectively.'
for n,start,end in [('377','2018-07-01','2018-09-29'),('331','2017-07-02','2017-09-30')]:
 rows.append(m(q,n,'1000000',cp,period_start=start,period_end=end,payer='AMD',receiver=cp,family='commercial',link_type='purchase',stage='delivered',amount_qualifier='exact',amount_nature='related_supplier_purchases_including_other_foundry_volume_fees_not_explicit_cash_or_supplier_GAAP_revenue',model_quantity='related_supplier_purchases',instrument_key='AMD_GF_WSA'))
q='The Company’s total purchases from GF related to wafer manufacturing, research and development activities and other for the nine months ended September 29, 2018 and September 30, 2017 were $1.2 billion and $773 million, respectively.'
for n,s,start,end in [('1.2','1000000000','2017-12-31','2018-09-29'),('773','1000000','2017-01-01','2017-09-30')]:
 rows.append(m(q,n,s,cp,period_start=start,period_end=end,payer='AMD',receiver=cp,family='commercial',link_type='purchase',stage='delivered',amount_qualifier='exact',amount_nature='related_supplier_YTD_purchases_not_additive_with_quarter_components_not_explicit_cash',model_quantity='related_supplier_purchases',instrument_key='AMD_GF_WSA'))
for n,end in [('15','2018-09-29'),('27','2017-12-30')]:
 rows.append(m('As of September 29, 2018 and December 30, 2017, the amount of prepayment and other receivables related to GF was $15 million and $27 million, respectively, included in Prepayment and receivables—related parties on the Company’s condensed consolidated balance sheets.',n,'1000000',cp,period_end=end,stage='recognized',amount_qualifier='exact',amount_nature='combined_prepayment_and_other_receivables_asset_stock_not_pure_advance_or_financing_component',model_quantity='related_prepayment_and_other_receivables',instrument_key='AMD_GF_WSA',flag_unknown_reason='prepayment_and_receivables_not_split_maturity_and_financing_component_not_disclosed'))
for n,end in [('321','2018-09-29'),('241','2017-12-30')]:
 rows.append(m('As of September 29, 2018 and December 30, 2017, the amount of payable to GF was $321 million and $241 million, respectively, included in Payables to related parties on the Company’s condensed consolidated balance sheets.',n,'1000000',cp,period_end=end,stage='recognized',amount_qualifier='exact',amount_nature='related_supplier_payable_stock_not_explicit_borrowing_or_financing_program',model_quantity='related_supplier_payables',instrument_key='AMD_GF_WSA',flag_unknown_reason='payment_terms_and_financing_component_not_disclosed'))
rows += [
m('As of December 30, 2017, the Company had paid GF $100 million in aggregate.','100','1000000',cp,period_end='2017-12-30',payer='AMD',receiver=cp,family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_qualifier='exact',instrument_key='AMD_GF_WSA_sixth_amendment_2016',model_quantity='supplier_waiver_rights_cash_payments',amount_nature='cumulative_historical_supplier_commercial_rights_payments_not_current_stock_or_customer_funding',flag_unknown_reason='cumulative_interval_start_and_annual_installment_allocation_not_disclosed_not_additive_across_repeated_filings'),
dict(quote='Starting in 2017 and continuing through 2020, the Company also agreed to make quarterly payments to GF based on the volume of certain wafers purchased from another wafer foundry.',counterparty=cp,counterparty_evidence='named',payer='AMD',receiver=cp,family='commercial',link_type='purchase_commitment',stage='signed',instrument_key='AMD_GF_WSA',model_quantity='other_foundry_volume_fee_commitment',flag_unknown_reason='fees_unquantified_and_included_in_supplier_purchases'),
dict(quote='If the Company does not meet the annual wafer purchase target for any calendar year, the Company will be required to pay to GF a portion of the difference between the Company’s actual wafer purchases and the wafer purchase target for that year.',counterparty=cp,counterparty_evidence='named',payer='AMD',receiver=cp,family='commercial',link_type='purchase_commitment',stage='signed',conditionality='conditional',trigger_description='If the Company does not meet the annual wafer purchase target for any calendar year',trigger_occurred='unknown',instrument_key='AMD_GF_WSA_sixth_amendment_2016',model_quantity='conditional_wafer_purchase_shortfall_payment',flag_unknown_reason='future_targets_portion_cap_and_triggered_amount_not_disclosed'),
dict(quote='In 2016 and 2017, the Company met its wafer purchase targets.',counterparty=cp,counterparty_evidence='named',conditionality='conditional',trigger_description='If the Company does not meet the annual wafer purchase target for any calendar year',trigger_occurred='no',instrument_key='AMD_GF_WSA_sixth_amendment_2016',model_quantity='wafer_purchase_shortfall_trigger_status',flag_unknown_reason='no_shortfall_trigger_for_stated_years_not_numeric_zero_or_future_guarantee'),
dict(quote='As of September 29, 2018, the Company expects to meet its 2018 wafer purchase target.',counterparty=cp,counterparty_evidence='named',instrument_key='AMD_GF_WSA_sixth_amendment_2016',model_quantity='wafer_purchase_target_expectation',flag_unknown_reason='expectation_does_not_establish_trigger_absence_for_completed_2018'),
dict(quote='On August 27, 2018, GF announced that it was putting its 7nm FinFET program on hold indefinitely.',counterparty=cp,counterparty_evidence='named',event_date='2018-08-27',model_quantity='supplier_wafer_program_suspension',flag_unknown_reason='supplier_operational_program_not_reporter_financial_covenant_or_contract_termination_event'),
dict(quote='Under the Warrant Agreement, WCH and its permitted assigns are entitled to purchase 75 million shares of the Company’s common stock (the Warrant Shares) at a purchase price of $5.98 per share. The warrant is exercisable in whole or in part until February 29, 2020.',counterparty='West Coast Hitech L.P.',counterparty_evidence='named',stage='available',instrument_key='AMD_WCH_warrant_2016',model_quantity='supplier_rights_warrant_exercise_terms',flag_unknown_reason='entitlement_and_expiry_not_cash_receipt_or_actual_equity_stock'),
dict(quote='West Coast Hitech L.P. (WCH), a wholly-owned subsidiary of Mubadala Development Company PJSC (Mubadala)',counterparty='West Coast Hitech L.P.',counterparty_evidence='named',model_quantity='entity_identity_and_control_evidence',issuer_treatment='wholly_owned_subsidiary_of_Mubadala_Development_Company_PJSC',flag_unknown_reason='parent_not_merged_with_Investment_Company_without_identity_evidence_actual_membership_start_unknown'),
dict(quote='GF, WCH and Mubadala Tech are wholly-owned subsidiaries of Mubadala.',counterparty=cp,counterparty_evidence='named',model_quantity='economic_group_control_evidence',issuer_treatment='wholly_owned_subsidiary_of_Mubadala_Development_Company_PJSC',flag_unknown_reason='actual_membership_start_unknown')]
save('ee17f90e2625fbf498b28afe12b42e978262893aabbeff1eda72bbea8e339f62',rows)
