from work.authored_helpers import *
key='38990348925256b6a6f3badefe75678d88e85adea97b9ba27e21d75b436024d9'
legal='REGISTRATION RIGHTS AGREEMENT dated as of October 5, 2025 (this “Agreement”) between Advanced Micro Devices, Inc., a Delaware corporation (the “Company”), and OpenAI OpCo, LLC, a Delaware limited liability corporation (the “Investor”).'
save(key,[
 dict(quote=legal,linkage_quote=legal,linkage_class='L1',counterparty='OpenAI OpCo, LLC',counterparty_evidence='named',payer='Advanced Micro Devices, Inc.',receiver='OpenAI OpCo, LLC',model_quantity='AMD_OpenAI_OpCo_registration_rights_full_legal_parties',stage='signed',event_date='2025-10-05',flag_unknown_reason='BothDEexplicit;literalOpenAIOpCoLLC_describedlimitedliabilitycorporation_preserved_notcorrected;independentdatedlegalproofnotGroupPBCAlias;rightsnotnewprimarycash'),
 dict(quote='“RRA Expiration Date” means October 5, 2033.',counterparty='OpenAI OpCo, LLC',counterparty_evidence='named',model_quantity='AMD_OpenAI_OpCo_registration_rights_conditional_expiry',flag_unknown_reason='6k_earlierRRAexpiry_orHolderceasesRegistrableSecurities_notactualtermination;3_4_5survive;distinct2030warrantexpiry'),
 dict(quote='aggregate gross cash proceeds (without regard to any underwriting discount or commission) of at least $100,000,000',model_quantity='AMD_OpenAI_OpCo_registration_holder_resale_threshold',flag_unknown_reason='2b_holderresalethreshold_notprimarycashAMD;nonunderwritten100mmarketvalueeligible_samedistinctmechanismsnotactualsaleorFV;noissuerfundinglink'),
 abstention('Signature Page to Registration Rights Agreement','Complete physical header and both body packets personally read throughAMDJeanHu/OpenAIOpCoSarahFriar signaturesOct5. Piggyback excludesWarrant; demandunderwrittenexcludesWarrant, ICAtransfercanincludewarrantwithconditions; rightsnotactualregistration/sale/exercise/funding. Oneunderwrittenper12monthsmax3aggregate vsMetaoneoverall notcopied. 40m consentcondition/30m transferminimum/1percentexpirycondition notactualstake. TopCo unnamedultimateparent notdatedlegalmembership. Same160m underlying warrants notadditionalshares. Expenses/indemnities nofinancialguarcall, ordinaryamendmentpermission noactualF4; privatenamedProductPurchaseAgreement notcompletecommercialcoverage.')
])
