from work.authored_helpers import *
k='3b4dc3e6b6180cc18ec05acb445c8190beb4b4fc173c17f009fade05b1bb99b7'
save(k,[dict(quote='The condensed consolidated financial statements include the accounts of Meta Platforms, Inc., its subsidiaries where we have controlling financial interests, and any variable interest entities for which we are deemed to be the primary beneficiary.',model_quantity='consolidation_scope_control_and_VIE_primary_beneficiary'),dict(quote='All intercompany balances and transactions have been eliminated.',model_quantity='intercompany_elimination'),abstention('There have been no material changes to our significant accounting policies from our Annual Report on Form 10-K for the fiscal year ended December 31, 2022.','Complete note no explicit substantial-doubt warning or life change; future April adoption absent at March report date.')])
k='9a2d33bf8aa0a84d1c0dc7d98fc71ebe310f09acd627a5eac30fea1e24ce3fe3'
save(k,[authored_control(k,'our CEO and CFO have concluded that as of March 31, 2023, our disclosure controls and procedures are designed at a reasonable assurance level and are effective to provide reasonable assurance','disclosure_controls_effective',event_present=True),authored_control(k,'There were no changes in our internal control over financial reporting identified in management\'s evaluation','no_material_ICFR_change_quarter',flag_unknown_reason='no_change_and_generic_limitations_not_F5_absence')])
k='cb1b060ce0cb48f8f667e09232fd175e5378ba9f806b1086a43aa0cfa1f46c4c'
rows=[dict(quote='Alphabet Inc. ("Alphabet") became the successor issuer to Google.',model_quantity='Alphabet_successor_issuer_2015',flag_unknown_reason='year_only_no_exact_day_in_block'),dict(quote='The consolidated financial statements of Alphabet include the accounts of Alphabet and entities consolidated under the variable interest and voting models.',model_quantity='consolidation_scope'),dict(quote='Intercompany balances and transactions have been eliminated.',model_quantity='intercompany_elimination'),dict(quote='In January 2023, we completed an assessment of the useful lives of our servers and network equipment',model_quantity='life_change_assessment_month',flag_unknown_reason='month_only_no_exact_day'),dict(quote='adjusted the estimated useful life of our servers from four years to six years and the estimated useful life of certain network equipment from five years to six years.',model_quantity='server_network_life_extension_not_F7',basis_break=True,recast_cause='accounting_change'),dict(quote='Certain amounts in prior periods have been reclassified to conform with current period presentation.',model_quantity='prior_period_reclassification',basis_break=True,recast_cause='presentation_reclassification',flag_unknown_reason='affected_lines_unknown'),dict(quote='On July 15, 2022, we executed a 20-for-one stock split of our Class A, Class B, and Class C stock.',model_quantity='stock_split20for1_all_classes',event_date='2022-07-15',flag_unknown_reason='share_comparatives_retroactive_not_new_cash')]
q='the effect of this change in estimate was a reduction in depreciation expense of $988 million and an increase in net income of $770 million,'
rows.append(authored_tagged(k,'e9a72ece08765b74a45cbfa5eacb3e0f7265eeeb71720fe317471f95d6913f17',q,model_quantity='life_change_depreciation_expense_effect',amount_nature='negative_expense_change_positive_pretax_effect_invert_sign',flag_unknown_reason='Dec2022_and_Q1_new_assets_cohort'))
rows.append(authored_tagged(k,'ccc120bfe931afa1f83723d135b0f41697187afdf734486ef4861d8526caea28',q,model_quantity='life_change_net_income_effect',amount_nature='after_tax_not_pretax_bridge',flag_unknown_reason='Dec2022_and_Q1_new_assets_cohort'))
rows.append(abstention('Actual results could differ materially from these estimates.','Complete note no explicit substantial-doubt warning. Life increases are not F7.'))
save(k,rows)
