from authored_helpers import save,abstention as a,money as m
fy=dict(period_start='2018-01-01',period_end='2018-12-31')
span=dict(period_start='2018-01-01',period_end='2019-03-31')
rows=[
dict(quote='We have entered into an indemnification agreement with each of our directors and executive officers.',stage='signed',model_quantity='legal_indemnification_obligation',flag_unknown_reason='individual_beneficiaries_cap_and_called_amount_not_disclosed'),
m('In 2018, we used these aircraft for business-related travel services for certain of our executive officers, including Eric, and we reimbursed Eric approximately $1,230,000.','1230000','1','Eric',**fy,payer='Google',receiver='Eric',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_nature='personal_aircraft_business_travel_cash_reimbursement_not_company_financing',model_quantity='related_supplier_cash_payments',flag_unknown_reason='individual_beneficiary_not_legal_entity'),
m('In 2018, we charged the Founder Entities approximately $1,332,000.','1332000','1','Founder Entities',**fy,payer='Founder Entities',receiver='Google',family='commercial',link_type='purchase',stage='recognized',amount_nature='airfield_fees_charged_not_explicit_cash_or_GAAP_revenue',model_quantity='related_customer_charges',flag_unknown_reason='aggregate_affiliated_entities_not_individually_named'),
m('In December 2015, we entered into an agreement to license a portion of our hangar space at the Airfield to LTA Research & Exploration LLC (LTA), which is owned by an entity affiliated with Sergey. From the beginning of 2018 through March 31, 2019, we charged LTA approximately $1,100,000.','1100000','1','LTA Research & Exploration LLC',**span,payer='LTA Research & Exploration LLC',receiver='Google',family='commercial',link_type='purchase',stage='recognized',amount_nature='hangar_license_charges_not_explicit_cash_or_GAAP_revenue',model_quantity='related_customer_charges',instrument_key='GOOGL_LTA_hangar_license',flag_unknown_reason='fifteen_month_interval_not_fiscal_year'),
m('Google, GV, and Gradient Ventures directly invested, or committed to invest, an aggregate of approximately $80.2 million in certain private companies from the beginning of 2018 through March 31, 2019, in which Kleiner Perkins Caufield & Byers was a co-investor or existing investor (excluding Viz.ai, Inc. investment described on page 38 of this proxy statement).','80.2','1000000','certain private companies',**span,counterparty_evidence='anonymous',amount_nature='mixed_invested_or_committed_aggregate_excludes_Viz_not_payment_to_KPCB',model_quantity='mixed_private_company_invested_or_committed',flag_unknown_reason='individual_recipients_drawn_vs_committed_split_and_annual_allocation_unknown'),
m('In June 2018, GV directly invested $5,000,000 in Viz.ai, Inc., a private company that develops artificial intelligence assisted medical imaging products.','5000000','1','Viz.ai, Inc.',period_start='2018-06-01',period_end='2018-06-30',payer='GV',receiver='Viz.ai, Inc.',family='financing',link_type='equity_primary',stage='recognized',event_type='funding',amount_qualifier='exact',amount_nature='direct_equity_round_investment_not_explicit_cash_or_current_stock',model_quantity='equity_primary_investment',instrument_key='GOOGL_GV_Viz_ai_2018-06',flag_unknown_reason='month_published_exact_event_day_and_cash_not_disclosed'),
a('On March 15, 2019, the Board of Directors (other than Diane, who recused herself) unanimously approved a waiver of the employment condition of the vesting of the remaining unvested Merger Shares in light of her leadership and contribution on the Google Cloud team.','employee_vesting_waiver_not_financial_covenant_event'),
m('From the beginning of 2018 through March 31, 2019, we charged Kitty Hawk Corporation a total of approximately $2,125,000, in accordance with the rates set forth in the underlying lease agreement that was previously negotiated between Kitty Hawk Corporation and the third-party seller.','2125000','1','Kitty Hawk Corporation',**span,payer='Kitty Hawk Corporation',receiver='Google',family='commercial',link_type='purchase',stage='recognized',amount_nature='office_lease_charges_not_explicit_cash_or_GAAP_revenue',model_quantity='related_customer_charges',instrument_key='GOOGL_Kitty_Hawk_office_lease',flag_unknown_reason='fifteen_month_interval_not_fiscal_year'),
dict(quote='Pursuant to the purchase agreement, the seller’s existing leases were transferred to us, including a lease with Zee.Aero, Inc. (d/b/a Kitty Hawk Corporation), an entity affiliated with Larry.',counterparty='Zee.Aero, Inc.',counterparty_evidence='named',model_quantity='entity_alias_evidence',issuer_treatment='doing_business_as_Kitty_Hawk_Corporation',flag_unknown_reason='trade_name_alias_asserted_not_legal_rename_or_rename_date'),
a('From time to time, we engage in certain transactions with other companies affiliated with our directors, executive officers, and significant stockholders or their immediate family members.','anonymous_ordinary_commercial_relationships_without_additional_amounts_or_financing_terms')]
save('45b070ff992f3fc9c57772e8bd97d76bcb813fcf0a7672270d2a63396f02d364',rows)
