from work.authored_helpers import *
key='7c9796b15b69a474264239130daa88c77c26784729f65849ad771a08b6b57108'
legal='Advanced Micro Devices, Inc., a Delaware corporation (“AMD” or the “Company”), for value received, hereby certifies that Meta Platforms, Inc. or its registered permitted assigns (“Meta” or the “Warrantholder”), is entitled, subject to the terms and conditions set forth herein, to purchase from the Company 160,000,000 shares of Common Stock'
vesting='The Warrant shall vest with respect to the Warrant Shares in accordance with the vesting schedule as set forth in Exhibit E hereto'
save(key,[
    dict(quote=legal,linkage_quote=legal,linkage_class='L1',counterparty='Meta Platforms, Inc.',counterparty_evidence='named',payer='Advanced Micro Devices, Inc.',receiver='Meta Platforms, Inc.',family='customer_consideration',link_type='equity_or_warrants_to_customer',stage='signed',event_date='2026-02-23',model_quantity='AMD_Meta_customer_warrant_full_legal_parties',conditionality='conditional',trigger_description=vesting,trigger_occurred='unknown',flag_unknown_reason='executedissuedwarrant_not_actualcommonshareissue_paidprimarycash_FV_orrecognizedcontra;ExEvest_ExFexerciseconditionsredacted'),
    dict(quote='to purchase from the Company 160,000,000 shares of Common Stock',amount='160000000',unit='http://www.xbrl.org/2003/instance:shares',amount_origin='narrative_only',amount_qualifier='up_to',counterparty='Meta Platforms, Inc.',counterparty_evidence='named',stage='signed',event_date='2026-02-23',model_quantity='AMD_Meta_warrant_max_underlying_share_count',amount_nature='underlying_future_conditional_share_count_not_current_issued_shares_or_money',flag_unknown_reason='0.01persharestrike_andpar_not_FV_cash;cashlesspermitted_nomax1.6mcashassumed'),
    dict(quote=vesting,counterparty='Meta Platforms, Inc.',counterparty_evidence='named',model_quantity='AMD_Meta_warrant_vesting_and_exercise_schedules_redacted',trigger_description=vesting,trigger_occurred='unknown',flag_unknown_reason='ExEandExFonly[***]_purchaseleaseproducttypesmilestonesdetailsredacted;vestedversusexercisable_separate_noactualvest_exercise_FV_orrecognizedcontra_nocaviards0'),
    dict(quote='in lieu of making a cash payment, having canceled a portion of this Warrant in payment of the Warrant Price',counterparty='Meta Platforms, Inc.',counterparty_evidence='named',model_quantity='AMD_Meta_warrant_cashless_exercise_permission',conditionality='optional',flag_unknown_reason='2a_holderchoice_cashorcashless_future_FMVperexercise_VWAP5day_notactualexercise_cashpayment_or_sharevaluation'),
    dict(quote='treat this Warrant as giving rise to a sales discount, allowance, or rebate in connection with the purchase or lease of the applicable products described in Exhibit E.',counterparty='Meta Platforms, Inc.',counterparty_evidence='named',model_quantity='AMD_Meta_warrant_contractual_tax_discount_rebate_treatment',flag_unknown_reason='15USfederalstatelocalINCOMETAXintent_notissueractualGAAPcontra_RV_FV_recognition;E5relationamountunknown_stage_signed'),
    dict(quote='February 23, 2031 (the “Expiration Date”)',counterparty='Meta Platforms, Inc.',counterparty_evidence='named',model_quantity='AMD_Meta_warrant_conditional_expiry_and_automatic_exercise',flag_unknown_reason='17ET_expiry_180dayextensionONLYalreadyvestedexercisable_regapprovalpending;earlyforcauseMPAterminationcancelunvestedandnonexercisable_thenautomaticexerciseONLYexercisable_notactualtermination_or160mvest'),
    abstention('Accepted and Agreed:','Complete physical first page and both body packets personally read including executedAMDJeanHu/MetaRajSingh signatures and all six redactedExhibitsA-F. FirstclauseAMDDE; MetaDEindependentlyregistrationrightsheader. AmendmentEightMPA reference not standalonefinancialdebtamendF4. No actualcash/exercise/vesting/recognizedcontra/FV; commercialvestingdetailsredacted notabsentzero. Warrant no stockholdervote/dividend before exerciseandsettlement under11; maxshares notcurrentstake. Taxdiscount notGAAPrecognizedrevenue. Antidilutionpermissions and partialexercise replacements not actualissuance. No optionalamendment/waiverpermission counted actualF4.')
])
