from work.authored_helpers import *
rows=[money('completed its issuance and sale of $8.0 billion in aggregate principal amount of senior unsecured notes','8','1000000000','initial_note_purchasers',counterparty_evidence='anonymous',receiver='Broadcom Inc.',stage='recognized',event_date='2020-05-08',family='financing',link_type='loan_or_facility',model_quantity='aggregate_issued_note_face',amount_qualifier='exact',amount_nature='aggregate_face_includes4series_not_net_cash')]
for quote,number,year in [('$1,000 million aggregate principal amount of 2.250% senior notes due 2023','1000','2023'),('$2,250 million aggregate principal amount of 3.150% senior notes due 2025','2250','2025'),('$2,750 million aggregate principal amount of 4.150% senior notes due 2030','2750','2030'),('$2,000 million aggregate principal amount of 4.300% senior notes due 2032','2000','2032')]:
 rows.append(money(quote,number,'1000000','initial_note_purchasers',counterparty_evidence='anonymous',receiver='Broadcom Inc.',stage='recognized',event_date='2020-05-08',family='financing',link_type='loan_or_facility',model_quantity='issued_note_face_'+year,amount_qualifier='exact',amount_nature='component_of8bn_issued_face_not_actual_net_cash'))
for name in ['Broadcom Technologies Inc.','Broadcom Corporation']:
 rows.append(dict(quote='Each series of Notes will initially be fully and unconditionally guaranteed, jointly and severally, on an unsecured, unsubordinated basis by Broadcom Technologies Inc., a Delaware corporation and Broadcom Corporation, a California corporation',counterparty=name,counterparty_evidence='named',stage='signed',event_date='2020-05-08',family='credit_support',link_type='guarantee',model_quantity='initial_notes_subsidiary_guarantee_'+name.replace(' ','_'),flag_unknown_reason='same_underlying8bn_notes_joint_several_not_additive_to_face_no_call_DE_Technologies_CA_Corporation_distinct'))
rows.append(abstention('The Company intends to use the net proceeds from the sale of the Notes','Full entire item read:fourfaces/guarantees, originalindenture, allredemption/ranking/covenant/default and registration clauses. Intendedrepaymentnot actual cash; no F4 originalissuance/default/cash penalty from passedMay8,2025deadline. 2023Nov15maturity passednot repaymentproof. Actualnetreceipts unknown.'))
save('27b7cab5e7841cb45809e19f6f5f3eb40b1aedb8ddad048570d0058eadb0fd69',rows)
rows=[]
for quote,number,year in [('$1.0 billion of 2.250% Senior Notes due 2023','1','2023'),('$2.25 billion of 3.150% Senior Notes due 2025','2.25','2025'),('$2.75 billion of 4.150% Senior Notes due 2030','2.75','2030'),('$2.0 billion of 4.300% Senior Notes due 2032','2','2032')]:
 rows.append(money(quote,number,'1000000000','prospective_note_investors',counterparty_evidence='anonymous',stage='intent_non_binding',model_quantity='priced_proposed_notes_'+year,amount_qualifier='exact',amount_nature='priced_offering_face_not_actual_issued_or_cash',flag_unknown_reason='May5pricing_no_executed_binding_underwrite_here_exchange_2026_2028_separate_proposed_transaction'))
rows.append(abstention('announced the commencement of exchange offers','Full item read including every caution. Proposednotes4seriespriced and distinctproposedexchange2026/28, no actual settlement/newexchangefaces/netcash/F4or default. Releases not imported.'))
save('56d34dbecf226b37d31db8be0fc5fcecf2ce7d49c9a6d2edd8cdff293a38b687',rows)
