from pathlib import Path
from decimal import Decimal
from secfragility.reader import store
u='http://www.xbrl.org/2003/iso4217:USD';r=Path('.').resolve();k='1c102800910b116738d56716f76a0704cbc019b901cb2042ddcbeba29296bffa'
def m(q,n,s,**f):return dict(quote=q,amount=str(Decimal(n)*{'million':1000000,'billion':1000000000,'unit':1}[s]),unit=u,currency='USD',amount_origin='narrative_only',amount_qualifier='approximately')|f
fy=dict(period_start='2024-06-01',period_end='2025-05-31')
rows=[]
sales=[
('Autonomous Medical Devices, Inc.','370715','Autonomous Medical Devices, Inc. purchased approximately $370,715 in cloud SaaS, PaaS and IaaS products.'),
('Desert Champions LLC','258526','Desert Champions LLC purchased approximately $258,526 in cloud SaaS products, hardware and consulting services.'),
('Ellison Institute, LLC','2107266','Ellison Institute, LLC purchased approximately $2,107,266 in cloud SaaS, PaaS and IaaS products.'),
('Lanai Resorts, LLC','616324','Lanai Resorts, LLC purchased approximately $616,324 in cloud SaaS products, software licenses, support and consulting services.'),
('Lawrence Investments, LLC','153115','Lawrence Investments, LLC purchased approximately $153,115 in cloud SaaS products.'),
('SailGP','649203','SailGP purchased approximately $649,203 in consulting services.'),
('Sensei AG Holdings, Inc.','1124121','Sensei AG Holdings, Inc. purchased approximately $1,124,121 in cloud SaaS, PaaS and IaaS products, support and consulting services.'),
('Skydance Animation','1872294','Skydance Animation purchased approximately $1,872,294 in cloud PaaS and IaaS products.'),
('Skydance Media','607038','Skydance Media purchased approximately $607,038 in cloud PaaS and IaaS products.')]
for cp,n,q in sales:
 rows.append(m(q,n,'unit',counterparty=cp,counterparty_evidence='named',payer=cp,receiver='Oracle',**fy,amount_nature='related_customer_purchases_not_explicit_GAAP_revenue_or_cash_receipts',model_quantity='related_customer_purchases',family='commercial',link_type='purchase',stage='delivered',instrument_key='ORCL_fiscal_2025_related_customer_purchases',flag_unknown_reason='exact_legal_entity_pending_where_trade_name_only_no_Oracle_financing_inferred'))
rows += [
dict(quote='Under this agreement, if we present Mr. Ellison with reasonable evidence of a lower price or rate for the same goods or services offered by the related company, which would have been available to us at the time we entered into the applicable transaction, then Mr. Ellison will reimburse us for the difference.',counterparty='Mr. Ellison',counterparty_evidence='named',payer='Mr. Ellison',receiver='Oracle',family='credit_support',link_type='guarantee',stage='signed',conditionality='conditional',trigger_description='if we present Mr. Ellison with reasonable evidence of a lower price or rate for the same goods or services offered by the related company, which would have been available to us at the time we entered into the applicable transaction',trigger_occurred='unknown',model_quantity='related_supplier_price_protection_reimbursement',flag_unknown_reason='cap_and_claimed_amount_not_disclosed_person_not_legal_entity'),
dict(quote='Total related person transaction revenues were approximately 0.02% of our total revenues.',amount='0.02',unit='percent',amount_origin='narrative_only',amount_qualifier='approximately',**fy,amount_nature='related_person_revenue_percent_not_financed_customer_revenue_share',model_quantity='related_person_revenue_percent',counterparty_evidence='anonymous',flag_unknown_reason='all_related_person_transactions_not_E2_financed_customer_category'),
dict(quote='Total related person operating expenses were approximately 0.04% of our total operating expenses in fiscal 2025.',amount='0.04',unit='percent',amount_origin='narrative_only',amount_qualifier='approximately',**fy,amount_nature='related_person_operating_expense_percent',model_quantity='related_person_operating_expense_percent',counterparty_evidence='anonymous'),
m('In fiscal 2025, Oracle paid F50 League approximately $7.5 million and SailGP received Oracle products and services valued at approximately $2.5 million.','7.5','million',counterparty='F50 League LLC',counterparty_evidence='named',payer='Oracle',receiver='F50 League LLC',**fy,amount_nature='sponsorship_cash_payments',model_quantity='related_supplier_cash_payments',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',instrument_key='ORCL_F50_SailGP_sponsorship'),
m('In fiscal 2025, Oracle paid F50 League approximately $7.5 million and SailGP received Oracle products and services valued at approximately $2.5 million.','2.5','million',counterparty='SailGP',counterparty_evidence='named',payer='Oracle',receiver='SailGP',**fy,amount_nature='products_services_provided_valuation_not_cash_or_explicit_revenue_reduction',model_quantity='noncash_product_service_value',family='commercial',link_type='purchase',stage='delivered',instrument_key='ORCL_F50_SailGP_sponsorship',flag_unknown_reason='legal_recipient_pending_no_E5_contra_revenue_treatment_disclosed'),
m('Oracle paid Glass Aviation approximately $2.5 million for aircraft management and pilot services in fiscal 2025, excluding all pass-through costs with no mark-up.','2.5','million',counterparty='Glass Aviation',counterparty_evidence='named',payer='Oracle',receiver='Glass Aviation',**fy,amount_nature='aircraft_management_pilot_cash_payments_excluding_pass_through',model_quantity='related_supplier_cash_payments',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',flag_unknown_reason='Glass_Aviation_exact_legal_entity_pending'),
m('The aggregate payment amount for Oracle’s use of the aircraft in fiscal 2025 was approximately $500,000.','500000','unit',counterparty='Wing and a Prayer, Inc.',counterparty_evidence='named',payer='Oracle',receiver='Wing and a Prayer, Inc.',**fy,amount_nature='aircraft_use_cash_payments',model_quantity='related_supplier_cash_payments',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment'),
m('The total carrying value of our investments in Ampere, after accounting for losses under the equity method of accounting, was $1.6 billion as of May 31, 2025.','1.6','billion',counterparty='Ampere Computing Holdings LLC',counterparty_evidence='named',period_end='2025-05-31',amount_qualifier='exact',amount_nature='combined_equity_and_convertible_debt_carrying_value_after_equity_method_losses_not_cash_funding',model_quantity='combined_equity_convertible_investment_carrying_value',stage='recognized',measurement_basis='carrying_value',flag_unknown_reason='equity_debt_split_not_disclosed_no_new_cash_flow'),
dict(quote='Our equity investments in Ampere represent an ownership interest of approximately 29% as of May 31, 2025.',counterparty='Ampere Computing Holdings LLC',counterparty_evidence='named',amount='29',unit='percent',amount_origin='narrative_only',amount_qualifier='approximately',period_end='2025-05-31',amount_nature='equity_ownership_percent',model_quantity='equity_ownership_percent',family='financing',link_type='equity_primary',stage='recognized'),
m('During the fiscal year ended May 31, 2025, we invested an aggregate of $341 million in convertible debt instruments issued by Ampere.','341','million',counterparty='Ampere Computing Holdings LLC',counterparty_evidence='named',payer='Oracle',receiver='Ampere Computing Holdings LLC',**fy,amount_qualifier='exact',amount_nature='convertible_debt_investment_not_combined_holding_stock',model_quantity='convertible_debt_funding',family='financing',link_type='convertible_or_safe',stage='drawn_or_paid',event_type='funding',instrument_key='ORCL_Ampere_fiscal_2025_convertible_debt',flag_unknown_reason='individual_funding_dates_and_cash_vs_noncash_settlement_not_explicit'),
m('In accordance with the terms of an agreement with other co-investors, we are also a counterparty to certain put (exercisable by a co-investor) and call (exercisable by Oracle) options at prices of approximately $500 million to $1.5 billion, respectively, to acquire additional equity interests in Ampere from our co-investors through January 2027.','500','million',counterparty_evidence='anonymous',payer='Oracle',receiver='Ampere co-investors',amount_nature='co_investor_put_exercise_price_not_current_called_obligation',model_quantity='co_investor_put_exercise_price',family='financing',link_type='equity_primary',stage='signed',conditionality='conditional',trigger_description='exercisable by a co-investor',trigger_occurred='unknown',instrument_key='ORCL_Ampere_co_investor_put',flag_unknown_reason='co_investor_identity_and_exercise_date_unknown_potential_secondary_equity_purchase'),
m('In accordance with the terms of an agreement with other co-investors, we are also a counterparty to certain put (exercisable by a co-investor) and call (exercisable by Oracle) options at prices of approximately $500 million to $1.5 billion, respectively, to acquire additional equity interests in Ampere from our co-investors through January 2027.','1.5','billion',counterparty_evidence='anonymous',payer='Oracle',receiver='Ampere co-investors',amount_nature='Oracle_optional_call_exercise_price_not_firm_commitment',model_quantity='optional_call_exercise_price',family='financing',link_type='equity_primary',stage='signed',conditionality='optional',instrument_key='ORCL_Ampere_co_investor_call',flag_unknown_reason='not_additive_to_put_price_co_investor_identity_and_exercise_unknown_potential_secondary_equity_purchase'),
dict(quote='The transaction is subject to customary closing conditions, including regulatory approvals. When the Ampere Acquisition closes, we will cease to be an investor in Ampere.',counterparty='Ampere Computing Holdings LLC',counterparty_evidence='named',model_quantity='Ampere_acquisition_pending_not_actual_Oracle_financing_exit',flag_unknown_reason='actual_closing_date_not_established_by_announcement'),
m('In fiscal 2023, Oracle placed a $104.1 million pre-payment order for Ampere processors which can be accessed through direct purchases from Ampere.','104.1','million',counterparty='Ampere Computing Holdings LLC',counterparty_evidence='named',payer='Oracle',receiver='Ampere',period_start='2022-06-01',period_end='2023-05-31',amount_qualifier='exact',amount_nature='processor_prepayment_order_not_explicit_cash_date_or_revenue',model_quantity='processor_prepayment_order',family='commercial',link_type='prepayment',stage='signed',instrument_key='ORCL_Ampere_fiscal_2023_processor_prepayment',flag_unknown_reason='operating_seller_legal_entity_and_cash_settlement_date_not_explicit'),
m('During fiscal 2025, we purchased approximately $3.7 million directly.','3.7','million',counterparty='Ampere Computing Holdings LLC',counterparty_evidence='named',payer='Oracle',receiver='Ampere',**fy,amount_nature='processor_purchases_not_additional_cash_funding',model_quantity='processor_purchases',family='commercial',link_type='purchase',stage='delivered',instrument_key='ORCL_Ampere_fiscal_2023_processor_prepayment',flag_unknown_reason='operating_seller_legal_entity_pending'),
m('At fiscal year end, we had approximately $97.4 million remaining available under our pre-payment order.','97.4','million',counterparty='Ampere Computing Holdings LLC',counterparty_evidence='named',period_end='2025-05-31',amount_nature='remaining_processor_prepayment_asset_not_undrawn_debt',model_quantity='processor_prepayment_remaining',stage='recognized',measurement_basis='carrying_value',instrument_key='ORCL_Ampere_fiscal_2023_processor_prepayment',flag_unknown_reason='operating_seller_legal_entity_pending'),
m('In fiscal 2025, Ampere purchased approximately $2.5 million in cloud SaaS, PaaS and IaaS products, licenses and support from Oracle.','2.5','million',counterparty='Ampere Computing Holdings LLC',counterparty_evidence='named',payer='Ampere',receiver='Oracle',**fy,amount_nature='customer_purchases_not_explicit_GAAP_revenue_or_cash_receipts',model_quantity='related_customer_purchases',family='commercial',link_type='purchase',stage='delivered',flag_unknown_reason='operating_customer_legal_entity_pending_no_E2_recognized_revenue_inferred'),
dict(abstained=True,abstention_reason='employee_compensation_outside_counterparty_financing_and_commercial_exposure',quote='Steven Janicki, Vice President, Business Relationship Management, is Mr. Ellison’s half-brother.')]
print(store(r,k,rows))
