from work.authored_helpers import *
k='e3eb6d938779d00e24815975b9f923614372ac5553b494a4f907c1160a6d76ac'
rows=repeat_chosen_rows('9f0bbca6e755683742ec60333473f8ef737d1f712487290fa094b800eaa8d715',['issuer_legal_name_jurisdiction','consolidation_scope','intercompany_elimination','fiscal_calendar_current_52weeks','fiscal_calendar_prior_52weeks'])
rows.append(abstention('Actual results could differ materially from these estimates,','Complete note no explicit substantial-doubt warning; no actual VMware acquisition clause here.'))
save(k,rows)
k='9a8c5d0fbca15102d7f71b42e3c5d7a4b1ec93dcfee0d14b18a84f3bb77b8ce0'
save(k,[authored_control(k,'our CEO and CFO concluded that, as of January 29, 2023, our disclosure controls and procedures were effective at the reasonable assurance level.','disclosure_controls_effective',event_present=True),authored_control(k,'There was no change in our internal control over financial reporting','no_material_ICFR_change_quarter',flag_unknown_reason='no_change_generic_limitations_not_F5_absence')])
k='e38cc1bf047d53a79baf4665601c0c0690efef671323671ea0b022472865f8b9'
save(k,[dict(quote='References herein to AMD or the Company mean Advanced Micro Devices, Inc. and its consolidated subsidiaries.',model_quantity='issuer_legal_name_consolidation'),dict(quote='On February 14, 2022 (the Xilinx Acquisition Date), the Company completed the acquisition of Xilinx, Inc. (Xilinx).',model_quantity='Xilinx_acquisition_completed',counterparty='Xilinx, Inc.',counterparty_evidence='named',event_date='2022-02-14',stage='recognized',flag_unknown_reason='no_amount_in_block'),dict(quote='On May 26, 2022 (the Pensando Acquisition Date), the Company completed the acquisition of Pensando Systems, Inc. (Pensando).',model_quantity='Pensando_acquisition_completed',counterparty='Pensando Systems, Inc.',counterparty_evidence='named',event_date='2022-05-26',stage='recognized',flag_unknown_reason='no_amount_in_block'),abstention('See Note 5 - Business Combinations for additional information on these acquisitions.','Complete first organization note no explicit substantial doubt. Separate accounting policies and acquisition details outside natural block not imported.')])
