from work.authored_helpers import *
save('d092765f0d9ea4b4b2f352f38cc6639309a867345ba3ebc887b7543b0ba89745',[dict(quote='on June 28, 2021, the Company completed the Domestication',event_date='2021-06-28',model_quantity='reported_domestication_completed',flag_unknown_reason='domestication_definition_underlying_entity_old_new_jurisdictions_unknown_in_closed_Item8_01_no_root_NVDA_jurisdiction_change_inferred'),abstention('As described above','Full item/signature read:completeddomestication alignscorporate/operatingstructure/OECDtax-lawcontext. Item7.01definition outsideclosed first pass, no imported legalidentity/jurisdiction, consolidation/cash/taxeffect or financial waiver/default/call.')])
save('ed1797a6c68d14b4baad13ca42e7cc04f4307e29ba147745ed4a9b3d1e9b60fb',[abstention('unanimously elected chief executive officer Satya Nadella to the role of board chair and John W. Thompson to the role of lead independent director','Full item/signatures read:June16governance elections. Boardroles not ownership/consolidation/funding, auditor independence assessment or actual ICFRweakness/F5negative.')])
k='a21cbc00ace230fc56c8d57998261f20331afaa3a31667890854b1bfa8855506'
rows=[]
for quote,num,q in [('$5.0 billion aggregate principal amount of unsecured notes','5.0','aggregate'),('$1.25 billion principal amount of 0.309% notes due 2023','1.25','2023'),('$1.25 billion principal amount of 0.584% notes due 2024','1.25','2024'),('$1.25 billion principal amount of 1.550% notes due 2028','1.25','2028'),('$1.25 billion principal amount of 2.000% notes due 2031','1.25','2031')]:
 rows.append(money(quote,num,'1000000000','several_underwriters',counterparty_evidence='anonymous',event_date='2021-06-14',stage='signed',amount_qualifier='exact',model_quantity='notes_'+q+'_underwritten_face',amount_nature='underwritten_unsecured_face_not_net_cash_components_nonadditive',flag_unknown_reason='signed_underwriting_date_not_exact_issue_day'))
rows.extend([money('The net proceeds from the offering of the Notes were approximately $4.98 billion, after deducting underwriting discounts and estimated offering expenses.','4.98','1000000000','several_underwriters',counterparty_evidence='anonymous',stage='drawn_or_paid',amount_qualifier='approximately',model_quantity='notes_actual_approx_net_after_discount_estimated_expenses',amount_nature='reported_actual_proceeds_net_of_discount_and_estimated_expenses_not_final_all_expense_cash',flag_unknown_reason='exact_receipt_day_unknown_no_June14_signing_or_June16_certificate_day_substitution_not_additive_with_faces'),dict(quote='The 2023 Notes will mature on June 15, 2023, the 2024 Notes will mature on June 14, 2024, the 2028 Notes will mature on June 15, 2028 and the 2031 Notes will mature on June 15, 2031.',model_quantity='four_notes_contractual_maturity_dates',flag_unknown_reason='future_original_maturity_not_actual_paid_or_current2026principal'),abstention('Morgan Stanley & Co. LLC, as representative of the several underwriters','Full item:June14underwriting/aggregate/four series and terms, reported actualapproxproceeds afterdiscount/estimatedexpenses/planneduse, registration/exhibit, base/officerscertificate/trustee, all maturities/interest/notice/makewholeexceptions, covenants/exceptions/originaldefault/two-partCoC+ratedowngradeput, allranking/subordination, every agreementrepresentation/materiality/risk limitation and finalreference read. No exact receipt/issue day, final all-expense net, actual debt repayment/default/financial waiver/call; original officerscertificate not F4. Namedrepresentative/trustee not full payer.')])
save(k,rows)
