from authored_helpers import save,abstention as a,money as m
pd=dict(period_start='2019-01-01',period_end='2020-03-31');fy=dict(period_start='2019-01-01',period_end='2019-12-31')
c=dict(family='commercial',link_type='purchase',stage='delivered',amount_nature='charges_not_explicit_cash_or_GAAP_revenue',model_quantity='related_customer_charges')
rows=[
dict(quote='We have entered into an indemnification agreement with each of our directors and executive officers.',counterparty_evidence='anonymous',family='credit_support',link_type='guarantee',stage='signed',model_quantity='director_officer_indemnification',flag_unknown_reason='natural_person_beneficiaries_specific_trigger_cap_claims_and_payments_not_disclosed'),
m('In 2019, we charged the Founder Entities approximately $1,397,089.','1397089','1','Founder Entities',**fy,payer='Founder Entities',receiver='Alphabet',**c,flag_unknown_reason='aggregate_founder_legal_entities_pending'),
m('From the beginning of 2019 through March 31, 2020, we charged LTA approximately $2,881,462.','2881462','1','LTA Research & Exploration LLC',**pd,payer='LTA Research & Exploration LLC',receiver='Alphabet',**c),
m('In 2019, we paid approximately $559,562 to BCH.','559562','1','BCH San Jose LLC',**fy,payer='Alphabet',receiver='BCH San Jose LLC',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_nature='hangar_license_cash_payments',model_quantity='related_supplier_cash_payments'),
m('Google, GV, and Gradient Ventures directly invested, or committed to invest, an aggregate of approximately $81.0 million in certain private companies from the beginning of 2019 through March 31, 2020, in which Kleiner Perkins was a co-investor or existing investor (excluding Viz.ai, Inc. investment described below).','81.0','1000000','certain private companies',**pd,counterparty_evidence='anonymous',payer='Google, GV, and Gradient Ventures',receiver='certain private companies',family='financing',link_type='equity_primary',amount_nature='aggregate_invested_or_committed_mixed_not_cash_to_Kleiner_Perkins',model_quantity='private_company_invested_or_committed',flag_unknown_reason='private_recipients_paid_vs_committed_allocation_unknown_Viz_ai_explicitly_excluded'),
m('In June 2018, GV directly invested $5,000,000 in Viz.ai, Inc., a private company that develops artificial intelligence assisted medical imaging products.','5000000','1','Viz.ai, Inc.',amount_qualifier='exact',payer='GV',receiver='Viz.ai, Inc.',period_start='2018-06-01',period_end='2018-06-30',family='financing',link_type='equity_primary',stage='recognized',event_type='funding',amount_nature='equity_round_investment_not_current_stock_or_explicit_cash',model_quantity='equity_primary_investment',instrument_key='GOOGL_GV_Viz_ai_2018-06',flag_unknown_reason='published_month_not_exact_event_day_cash_form_and_current_holding_not_disclosed'),
m('In August 2019, GV directly invested $7,000,000 in aggregate in the follow-on round of financing.','7000000','1','Viz.ai, Inc.',amount_qualifier='exact',payer='GV',receiver='Viz.ai, Inc.',period_start='2019-08-01',period_end='2019-08-31',family='financing',link_type='equity_primary',stage='recognized',event_type='funding',amount_nature='equity_round_investment_not_current_stock_or_explicit_cash',model_quantity='equity_primary_investment',instrument_key='GOOGL_GV_Viz_ai_2019-08',flag_unknown_reason='source_conflict_later_proxies_6750000_August_to_October_not_added_as_distinct_round_cash_form_unknown'),
dict(quote='Replica, Inc. is a company that Sidewalk Labs incubated and spun off in May 2019 with Sidewalk Labs retaining approximately 47% ownership of the company.',counterparty='Replica, Inc.',counterparty_evidence='named',amount='47',unit='percent',amount_origin='narrative_only',amount_qualifier='approximately',model_quantity='equity_ownership_percent_after_spin_off',amount_nature='ownership_percent_not_cash_or_current_investment_value',flag_unknown_reason='published_spin_off_month_May_2019_exact_stock_instant_and_consolidation_not_disclosed'),
dict(quote='After completion of the financing round, IE III owns approximately 22% of Replica, and Sidewalk Labs owns approximately 29% of Replica.',counterparty='Replica, Inc.',counterparty_evidence='named',amount='29',unit='percent',amount_origin='narrative_only',amount_qualifier='approximately',model_quantity='equity_ownership_percent_after_financing_round',amount_nature='Sidewalk_Labs_ownership_percent_not_cash_or_current_investment_value',flag_unknown_reason='post_August_2019_round_exact_stock_instant_and_consolidation_not_disclosed'),
a('In August 2019, Innovation Endeavors III, L.P. (IE III) invested $10,000,000 in Replica.','third_party_fund_investment_not_Alphabet_group_funding_personal_founder_affiliation_not_consolidation'),
m('From the beginning of 2019 through March 31, 2020, we charged Kitty Hawk Corporation a total of approximately $2,026,275, in accordance with the rates set forth in the underlying lease agreement that was previously negotiated between Kitty Hawk Corporation and the third-party seller, and in June 2019 subsequently divided into three separate lease agreements.','2026275','1','Kitty Hawk Corporation',**pd,payer='Kitty Hawk Corporation',receiver='Alphabet',**c),
dict(quote='including a lease with Zee.Aero, Inc. (d/b/a Kitty Hawk Corporation), an entity affiliated with Larry.',counterparty='Zee.Aero, Inc.',counterparty_evidence='named',model_quantity='documented_doing_business_as_alias',flag_unknown_reason='lease_transferred_July_2017_alias_observed_2020_proxy_not_assumed_date_of_legal_rename'),
a('On March 15, 2019, the Board of Directors (other than Diane, who recused herself) unanimously approved a waiver of the employment condition of the vesting of the remaining unvested Merger Shares in light of her leadership and contribution on the Google Cloud team.','employee_equity_vesting_waiver_not_financial_covenant_event_F4'),
a('The spouse of David has been employed by Google in a non-executive capacity since April 2018.','employee_compensation_outside_counterparty_financing_and_commercial_exposure'),
a('In addition, from time to time, we sell to and purchase from companies in which Kleiner Perkins holds more than 10% of the outstanding shares, products and services in the ordinary course of our business,','unnamed_ordinary_commercial_counterparties_and_amounts_not_disclosed')]
save('5c750db31598399016c97d3acbd7fa4d37c3f0232856f5f1c96b9ff7a5e7a0dc',rows)
