from work.authored_helpers import *
from work.authored_quarantines import record
k='4b95a297a7cffbbca9463b1effb3a93a02ae24c52a319f87371cd43afd5a780e'
record('D76',k,'0001193125-23-271376',[], 'L’échange Microsoft/Activision du 6 novembre 2023 nomme les nouvelles notes 2047 à 4,500 % puis leur attribue 3,400 % dans la liste des taux et échéances. Les deux formulations sont conservées ; le coupon 2047 et les intérêts calculés qui en dépendent restent indéterminés sans résolution documentaire. Les faces échangées/annulées, nouvelles faces et anciens soldes distincts ne sont pas des encaissements. Les suppressions de clauses ont été exécutées le 27 octobre mais sont devenues opérantes le 6 novembre : F4 daté du 6 novembre sans inférer un manquement.')
rows=[dict(quote='Activision Blizzard, Inc., a wholly-owned subsidiary of Microsoft',counterparty='Activision Blizzard, Inc.',counterparty_evidence='named',model_quantity='Activision_wholly_owned_subsidiary_exchange_scope',flag_unknown_reason='relation_current_at_exchange_not_exact_acquisition_consolidation_start'),dict(quote='The Amendments became operative upon the Early Settlement.',event_date='2023-11-06',event_observable='F4',event_present=True,model_quantity='Activision_financial_covenant_default_clause_elimination_operative',flag_unknown_reason='three_supplements_executed_Oct27_operative_Nov6_debt_exchange_not_proof_actual_default'),dict(quote='The 2047 Notes will bear interest at a rate of 3.400% per annum and will mature on June 15, 2047;',model_quantity='new_2047_note_coupon_conflict',flag_unknown_reason='same_item_new_2047_title_4_500_percent_vs_coupon_clause_3_400_percent_no_interest_calculation')]
for table,new,num,remaining,q in [
('3.400% Senior Notes due 2026 | | $ | | | | $ | 762,456,000 | | | $ | 87,544,000 |','$762,456,000 aggregate principal amount of 3.400% Notes due 2026','762456000','87544000','2026'),
('3.400% Senior Notes due 2027 | | $ | | | | $ | 353,183,000 | | | $ | 43,817,000 |','$353,183,000 aggregate principal amount of 3.400% Notes due 2027','353183000','43817000','2027'),
('1.350% Senior Notes due 2030 | | $ | | | | $ | 442,842,000 | | | $ | 57,158,000 |','$442,842,000 aggregate principal amount of 1.350% Notes due 2030','442842000','57158000','2030'),
('4.500% Senior Notes due 2047 | | $ | | | | $ | 391,290,000 | | | $ | 8,710,000 |','$391,290,000 aggregate principal amount of 4.500% Notes due 2047','391290000','8710000','2047'),
('2.500% Senior Notes due 2050 | | $ | | | | $ | 1,439,312,000 | | | $ | 60,688,000 |','$1,439,312,000 aggregate principal amount of 2.500% Notes due 2050','1439312000','60688000','2050')]:
 for quote,n,qty,nature in [(table,num,'old_Activision_'+q+'_principal_exchanged_canceled','old_face_accepted_retired_canceled_not_cash_repayment'),(table,remaining,'old_Activision_'+q+'_principal_remaining','remaining_old_issuer_principal_stock_not_new_funding'),(new,num,'new_Microsoft_'+q+'_notes_face_issued_in_exchange','new_parent_face_exchange_for_old_subsidiary_face_not_new_cash')]:
  rows.append(money(quote,n,'1','eligible_noteholders',counterparty_evidence='anonymous',event_date='2023-11-06',period_end='2023-11-06',stage='recognized',amount_qualifier='exact',model_quantity=qty,amount_nature=nature,flag_unknown_reason='exchange_includes_cash_component_unknown_old_new_face_nonadditive'))
rows.append(abstention('Microsoft shall pay additional interest on the New Microsoft Notes of up to 1.0% if','Full item: completed early exchange/retirement, entire two-column five-series table, all three covenant/default-removal supplemental indentures/trustee successor names/dates, operative clause, five new faces/security and every maturity/coupon, registration rights/12dealer managers/conditional additional interest/renvois read. 2047coupon contradictory kept unknown. Original Microsoft new-note supplemental terms not additional F4; actual Activision operative covenant removal is F4. Cash exchange component not quantified, no inferred new cash receipt/guarantee call or actual registration-interest penalty. Dealer managers/trustees not cash funding counterparties.'))
save(k,rows)
k='811709be12f7ff04f95bb19c162f49b7b82f82b3b44fd35a8f5e5cc0e2f01f0c'
save(k,[money('an unsecured revolving credit facility with a borrowing capacity of up to $15.0 billion.','15.0','1000000000','five_year_revolving_lenders',counterparty_evidence='anonymous',event_date='2023-11-01',stage='available',amount_qualifier='up_to',family='financing',link_type='loan_or_facility',model_quantity='five_year_unsecured_revolver_limit',amount_nature='available_limit_not_cash_drawn'),money('an unsecured revolving credit facility with a borrowing capacity of up to $5.0 billion.','5.0','1000000000','364_day_revolving_lenders',counterparty_evidence='anonymous',event_date='2023-11-01',stage='available',amount_qualifier='up_to',family='financing',link_type='loan_or_facility',model_quantity='364_day_unsecured_revolver_limit',amount_nature='separate_available_limit_not_cash_drawn'),money('the prior $10.0 billion amended and restated credit agreement','10.0','1000000000','prior_five_year_lenders',counterparty_evidence='anonymous',event_date='2023-11-01',stage='terminated',amount_qualifier='exact',model_quantity='old_five_year_revolver_limit_terminated',amount_nature='prior_limit_not_repaid_principal'),money('the prior $10.0 billion 364-day revolving credit agreement','10.0','1000000000','prior_364_day_lenders',counterparty_evidence='anonymous',event_date='2023-11-01',stage='terminated',amount_qualifier='exact',model_quantity='old_364_day_revolver_limit_terminated',amount_nature='prior_limit_not_repaid_principal'),dict(quote='but do not contain financial covenants.',model_quantity='both_revolvers_explicit_no_financial_covenants'),dict(quote='Citibank N.A., as administrative agent',counterparty='Citibank N.A.',counterparty_evidence='named',model_quantity='revolver_administrative_agent_not_total_funding_payer'),abstention('Upon an event of default that is not cured within applicable grace periods or waived','Full item: two new replacement facilities/prior terminations/dates/limits, separate terms/extensions, benchmark margin/undrawn fee, planned CP backstop, explicit no financial covenants, conditional acceleration/termination, lender service relationships and exhibits read. No actual loan draw/repayment or zero outstanding proof, actual default/waiver/guarantee call. Replaced original facilities not proof amendment/waiver under F4; no capacity-contract F9.')])
save('bf9a69dc200256ab563de05c9a940d3250b14295360192237eccd8bb8b1d8e33',[abstention('The information set forth in Item 1.01','Full item read; exact renvoi to eligible Item1.01 personally read. Replacement of credit facilities, not capacity-contract F9; no extra cash amount or default introduced by renvoi.')])
