from work.authored_helpers import *
save('f78e439ccf534214c64273d4998cfe4867b0990fa619d9f713ea1587ec096b93',[
money('borrowings under a term loan facility of up to $600 million with a maturity date of February 3, 2020.','600','1000000','Bridge_Lenders',counterparty_evidence='anonymous',receiver='Marvell Technology Group Ltd.',stage='signed',event_date='2019-11-04',family='financing',link_type='loan_or_facility',model_quantity='unsecured_90_day_bridge_limit',amount_qualifier='up_to',amount_nature='signed_bridge_limit_not_actual_funded_cash',flag_unknown_reason='funding_commitments_expire_Nov4_or_after_loan_no_actual_draw_or_lapse_proof_maturity_Feb3_2020_not_repaymentproof'),abstention('Bridge Credit Agreement requires the Company to maintain a Leverage Ratio','Full item read. Originalbridge/leverage3threshold/rates/covenants not F4 or actualbreach/draw. IntendedAverafinance not acquiredtargetprimarycash; WellsFargoBankNatAssociationdistinct WellsFargoSecuritiesLLC; agents not all lenderallocation.')])
save('992c33cb620bb8a04019b352a4816b7806fe683e3b8073ed8d24ca65656ee927',[
money('for $650 million in cash, subject to certain closing adjustments specified in the purchase agreement, at closing','650','1000000','GLOBALFOUNDRIES',stage='signed',model_quantity='Avera_agreed_base_cash_consideration',amount_qualifier='exact',amount_nature='agreed_base_price_subject_adjustments_not_actual_paid',flag_unknown_reason='May20announcement_exact_signing_day_unknown_Avera_ASIC_business_not_proven_standalone_legalentity_GF_brand_identity_pending'),money('an additional $90 million in cash if certain business conditions are satisfied within the next 15 months.','90','1000000','GLOBALFOUNDRIES',stage='signed',model_quantity='Avera_conditional_earnout_cap',amount_qualifier='exact',amount_nature='conditional_increment_not_actual_cash_paid',trigger_description='if certain business conditions are satisfied within the next 15 months',flag_unknown_reason='conditions_period_anchor_actual_trigger_and_payment_unknown_not_add_to_actualpaid'),dict(quote='On November 5, 2019, the Company issued a press release announcing that it had closed the transaction.',stage='settled',model_quantity='Avera_acquisition_completed_announced',flag_unknown_reason='exact_actual_close_day_and_cash_payment_unknown_Nov5announcement_not_reportNov4_or_legal_entity_consolidation_start_proof'),abstention('the Application Specific Integrated Circuit (ASIC) business of GLOBALFOUNDRIES','Full item read. Acquisitionbusiness announcedcompleted, not650actualpaidproof or newGFprimarycash. Distinct90contingentcash not exercised; release not imported.')])
rows=[]
for quote,number,quantity in [('an aggregate of $15.50 billion of term loan commitments','15.50','aggregate_term_commitment'),('a $7.75 billion unsecured term A-3 facility','7.75','term_A3_commitment_component'),('a $7.75 billion unsecured term A-5 facility','7.75','term_A5_commitment_component')]:
 rows.append(money(quote,number,'1000000000','term_lenders',counterparty_evidence='anonymous',stage='signed',family='financing',link_type='loan_or_facility',model_quantity=quantity,amount_qualifier='exact',amount_nature='unsecured_commitment_components_in_aggregate15_5bn_not_actual_cash',flag_unknown_reason='Effective_Date_definition_outside_eligible_item_not_imported_actual_date_unknown_third_fifth_anniversary_no_calendar_day_invented'))
rows.append(money('the Company borrowed $12.0 billion of term loans ratably between the Term Facilities','12','1000000000','term_lenders',counterparty_evidence='anonymous',stage='drawn_or_paid',family='financing',link_type='loan_or_facility',model_quantity='actual_term_borrowing',amount_qualifier='exact',amount_nature='actual_borrowing_in15_5bn_commitment_not_additive_to_limits',flag_unknown_reason='Effective_Date_unknown_not_reportdate_substitute_actual_acquisition_and_working_capital_expense_allocation_unknown'))
for quote,number,scale,cp,quantity in [('CA, Inc.’s $750 million aggregate principal amount of 5.375% Senior Notes due December 1, 2019','750','1000000','CA, Inc.','CA_old_notes_planned_refinancing_face'),('$2.75 billion aggregate principal amount of 2.375% Senior Notes due January 15, 2020','2.75','1000000000','two_subsidiary_issuers','two_sub_old_notes_planned_refinancing_face')]:
 rows.append(money(quote,number,scale,cp,counterparty_evidence='named' if cp=='CA, Inc.' else 'anonymous',stage='recognized',model_quantity=quantity,amount_qualifier='exact',amount_nature='old_note_face_reference_not_actual_repaid_or_fresh_financing',flag_unknown_reason='planned_remaining_commitment_borrowings_subject_conditions_not_actualdraw'))
rows.extend([dict(quote='The Company’s obligations under the Credit Agreement are guaranteed on an unsecured basis by its subsidiaries, Broadcom Corporation, a California corporation, and Broadcom Technologies Inc., a Delaware corporation.',stage='signed',family='credit_support',link_type='guarantee',model_quantity='two_subsidiary_term_credit_guarantees',flag_unknown_reason='full_legal_names_CA_Corporation_DE_Technologies_distinct_face_not_extra_financing_or_called_actual_date_unknown'),abstention('shall not be less than 3.00:1.00','Full item read including commitments/actual12borrowing/pendingrefinance/maturities/rates/prepay/ICR3/defaults/bankservices. EffectiveDateundefinedhere; no exactborrow/signingday invented. NeworiginalfinancialtermsnotF4/actualbreach; no targetlegalname importedfromexcluded2.01 or actualoldnoterepayments.')])
save('2626d78f14c8971dbe10d3d54cbb00937e8341d06c8dbd515114af9219f233e0',rows)
