from work.authored_helpers import *
k='8a110c67218bdf76aad89497de7394889c6aedd902605017074f278aaf137130'
save(k,[dict(quote='Marvell Technology, Inc. (“MTI”), a Delaware corporation, and its wholly owned subsidiaries',model_quantity='issuer_legal_name_jurisdiction_consolidation'),dict(quote='All inter-company accounts and transactions have been eliminated.',model_quantity='intercompany_elimination'),dict(quote='Certain prior period amounts have been reclassified to conform to current period presentation.',model_quantity='prior_period_reclassification',basis_break=True,recast_cause='presentation_reclassification',flag_unknown_reason='affected_lines_unknown_not_automatic_total_change'),dict(quote='Fiscal 2023 had a 52-week year. Fiscal 2024 is a 53-week year.',model_quantity='fiscal_calendar_53weeks_current_52prior',flag_unknown_reason='extra_week_fourth_quarter14weeks'),abstention('As events continue to evolve and additional information becomes available, these estimates may change materially in future periods.','Complete note no explicit substantial-doubt warning; estimates are generic.')])
k='e29ca35cd981b57e35abcf84ca9fd01534ebaf1b84c7f1a36cc93d4f42298c61'
save(k,[authored_control(k,'our principal executive officer and principal financial officer concluded that our disclosure controls and procedures were effective as of April 29, 2023.','disclosure_controls_effective',event_present=True),authored_control(k,'No changes in the Company’s internal control over financial reporting','no_material_ICFR_change_quarter',flag_unknown_reason='no_change_and_generic_limitations_not_F5_absence')])
k='c4cac648d78e704ab54b3056d25c59884f246becba13480267916f068e1c5f78'
rows=[dict(quote='Our condensed consolidated financial statements include the accounts of NVIDIA Corporation and our wholly-owned subsidiaries.',model_quantity='consolidation_scope'),dict(quote='All intercompany balances and transactions have been eliminated in consolidation.',model_quantity='intercompany_elimination'),dict(quote='Fiscal years 2024 and 2023 are both 52-week years. The first quarters of fiscal years 2024 and 2023 were both 13-week quarters.',model_quantity='fiscal_calendar_both52weeks_quarters13'),dict(quote='Certain prior fiscal year balances have been reclassified to conform to the current fiscal year presentation.',model_quantity='prior_period_reclassification',basis_break=True,recast_cause='presentation_reclassification',flag_unknown_reason='affected_lines_unknown'),dict(quote='In February 2023, we completed an assessment of the useful lives of our property, plant, and equipment.',model_quantity='equipment_life_change_assessment_month',flag_unknown_reason='month_only_no_exact_day'),dict(quote='we increased the estimated useful life of a majority of our server, storage, and network equipment from three to a range of four to five years, and our assembly and test equipment from five to seven years.',model_quantity='server_network_and_assembly_test_life_extension_not_F7',basis_break=True,recast_cause='accounting_change'),dict(quote='This change in accounting estimate became effective at the beginning of fiscal year 2024.',model_quantity='life_change_effective_fiscal_year')]
q='the effect of this change in estimate for the three months ended April 30, 2023, was a benefit of $2 million and $31 million for cost of revenue and operating expenses, respectively.'
for fid,qty in [('4224664a20c50140244f9e9eb1eeddd9eb2899344f698e392495f1c39341e4db','life_change_cost_of_revenue_effect'),('6ac025f20f9927c582096dc24897ae51f74ea931b14a871cfd81baac2961dcea','life_change_operating_expense_effect')]:rows.append(authored_tagged(k,fid,q,model_quantity=qty,amount_nature='negative_expense_change_positive_pretax_effect_invert_sign',flag_unknown_reason='end_FY2023_existing_asset_cohort_components_overlap_operating_income_effect'))
q='This resulted in an increase in operating income of $33 million and net income of $28 million after tax,'
rows.append(authored_tagged(k,'7da7a2933a7ff9a303515ed21d872d6e34c0f1bb389fd4fe11c81ef52bb5b27a',q,model_quantity='life_change_operating_income_effect',amount_nature='pretax_effect_overlaps_expense_components'))
rows.append(authored_tagged(k,'579a61dbc08aad3d1e865de9e01c67d44d8c865b79b0fea0bb8a33fa4e8909a0',q,model_quantity='life_change_net_income_effect',amount_nature='after_tax_not_pretax_bridge'))
rows.append(abstention('Actual results could differ materially from our estimates.','Complete note no explicit substantial-doubt warning; life changes are extensions, not F7 decreases.'))
save(k,rows)
