from authored_helpers import save,abstention as a,money as m,repeat_chosen_rows
fy=dict(period_start='2017-01-01',period_end='2017-12-31')
span=dict(period_start='2017-01-01',period_end='2018-03-31')
rows=repeat_chosen_rows('45b070ff992f3fc9c57772e8bd97d76bcb813fcf0a7672270d2a63396f02d364',['legal_indemnification_obligation'])
rows += [
m('In 2017, we used these aircraft for business-related travel services for certain of our executive officers, including Eric, and we reimbursed Eric approximately $1,338,750.','1338750','1','Eric E. Schmidt',**fy,payer='Google',receiver='Eric E. Schmidt',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_nature='personal_aircraft_business_travel_cash_reimbursement_not_company_financing',model_quantity='related_supplier_cash_payments',flag_unknown_reason='individual_beneficiary_not_legal_entity'),
m('In 2017, we charged the Founder Entities approximately $1,720,820.','1720820','1','Founder Entities',**fy,payer='Founder Entities',receiver='Google',family='commercial',link_type='purchase',stage='recognized',amount_nature='airfield_fees_charged_not_explicit_cash_or_GAAP_revenue',model_quantity='related_customer_charges',flag_unknown_reason='aggregate_affiliated_entities_not_individually_named'),
m('In December 2015, we entered into an agreement to license a portion of our hangar space at the Airfield to LTA Research & Exploration LLC (LTA), which is owned by an entity affiliated with Sergey Brin. From the beginning of 2017 through March 31, 2018, we charged LTA approximately $423,000.','423000','1','LTA Research & Exploration LLC',**span,payer='LTA Research & Exploration LLC',receiver='Google',family='commercial',link_type='purchase',stage='recognized',amount_nature='hangar_license_charges_not_explicit_cash_or_GAAP_revenue',model_quantity='related_customer_charges',instrument_key='GOOGL_LTA_hangar_license',flag_unknown_reason='fifteen_month_interval_not_fiscal_year'),
m('In November 2015, we entered into an agreement with BCH San Jose LLC (BCH) to license the use of a portion of BCH’s hangar space at the Mineta San Jose International Airport to hold Google’s corporate aircraft. In 2017, we paid approximately $513,971 to BCH.','513971','1','BCH San Jose LLC',**fy,payer='Google',receiver='BCH San Jose LLC',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_nature='corporate_aircraft_hangar_supplier_cash_payments',model_quantity='related_supplier_cash_payments',instrument_key='GOOGL_BCH_hangar_license'),
m('GV and CapitalG directly invested, or committed to invest, an aggregate of approximately $128.6 million in certain private companies from the beginning of 2017 through March 31, 2018, in which Kleiner Perkins Caufield & Byers was a co-investor or existing investor.','128.6','1000000','certain private companies',**span,counterparty_evidence='anonymous',amount_nature='mixed_invested_or_committed_aggregate_not_payment_to_KPCB',model_quantity='mixed_private_company_invested_or_committed',flag_unknown_reason='individual_recipients_drawn_vs_committed_split_and_annual_allocation_unknown'),
m('In 2017, we provided a $3,620,000 sponsorship to X Prize Foundation.','3620000','1','X Prize Foundation',**fy,payer='Google',receiver='X Prize Foundation',family='commercial',link_type='purchase',stage='delivered',amount_qualifier='exact',amount_nature='sponsorship_provided_cash_vs_in_kind_not_explicit',model_quantity='sponsorship_provided',flag_unknown_reason='cash_form_and_legal_status_not_inferred'),
dict(quote='Larry Page, Sergey Brin, and Eric E. Schmidt each own one-third interests in BCH, through their respective affiliated entities.',counterparty='BCH San Jose LLC',counterparty_evidence='named',model_quantity='ownership_affiliation_evidence',flag_unknown_reason='personal_affiliated_owners_not_Alphabet_consolidation'),
a('From time to time, we engage in certain transactions with other companies affiliated with our directors, executive officers, and significant stockholders or their immediate family members.','anonymous_ordinary_commercial_relationships_without_additional_amounts_or_financing_terms')]
save('ea1e8a58b39e8b7a9ad351c82ef2427c08da6b782e6f23da33d42aa8852ab887',rows)
