from work.authored_helpers import *

save('f24d69e76f85675e235927893388e8ae2904742843ed40899fcd77efa86f01b3', [
 dict(quote='the Credit Agreement is hereby amended to delete the stricken text',event_date='2023-04-14',event_type='amendment',event_observable='F4',event_present=True,stage='signed',model_quantity='MRVL_2023_first_amendment_financial_clauses',flag_unknown_reason='AutonomousFirstAmendmentFULLsinglebodypacket read under11.1. IndependentItem1.01 actualApril14 SOFRtransition andmaximumleverageconformity. AnnexA [Attached] heading only no conformedtext; bodydoesnot independentlyquantify leverage limit. No actualdistresswaiver/default/cure/guaranteecall. Allsignaturepagesfinanciallenders; WillemMientjesBorrower/AgentRyanZimmerman signed.'),
 dict(quote='any Eurocurrency Loans (as defined in the Existing Credit Agreement) outstanding as of the First Amendment Effective Date shall continue to the end of the applicable Interest Period',model_quantity='MRVL_2023_amendment_existing_loans_transition_not_new_funding',flag_unknown_reason='Section5 old Eurocurrencyloans transition at endofexistingperiod; not actualnewcash/principalrepayment. Section8e noimpliedwaiver/novation othertermsratified; no guarantor/principal/currentbalance inferred.'),
 abstention('Annex A [Attached]','CompletephysicalheaderANDentirebodyonepacketpersonallyread. AnnexA amendedcredittext onlyheading [Attached], absentcontents; doNOT infer numericcovenantold/new, facilitycashdraw ordefaultexercise. IndependentItem1.01 conformsleverageandadoptsSOFR; restated1bnrevolver separateagreement not addedasnewloanfromthisamendment.')
])
save('acb3b679736f9374457a407a2be322784e68c590f13304c11185a6e092dcd38a', [dict(abstention('Officers’ Certificate', 'Completephysicalheader0:6037 personallyread; sameItem8.01 d309c51a FULLreread actualFeb6,23 5.25bn4seriesunderwritingFeb2 withfivefinancialBofA/Citi/Goldman/HSBC/JPM. FinancialBNYMellonTrustCompanyNA trustee; old2006OracleSystems/2007successions historicalnotnewF4 andnotexternalnonfinancialcurrentbuyer. Originalofficercertificate ENTIREbody6037:186281 excludedUNREAD financial_parties_only; noamount/link/covenant/bodyF4. 3.1bntermloan/1.25bnnotes/CPpaydown statedINTENTIONnotactualrepayment; historicalnamesjurisdictionsnotinferred.'),model_quantity='exhibit_body_excluded_financial_parties_only',raw_byte_start=0,raw_byte_end=6037,locator='rawbytes:0:6037')])
save('170f11e5a9e477b36bbd263f9f59011be78dc48079e4f710b67254df3bd84fe9', [dict(abstention('dated as of January 3, 2023', 'Completephysicalheader0:5132 personallyread; sameItem1.01 95b0c0a9 FULLreread expresslyfinancialinstitutionspartytocreditagreement, notagentonlyinference. Allnamedbanks/bookrunnersfinancial; originaltermloancontractnotAmendment/Waiver/Consent. ENTIREbody5132:483052 excludedUNREAD financial_parties_only noamount/link/covenant/bodyF4. Independent8bncapacity; Uponfundingfutureproceeds not actualdrawpaid; maturity364daysoptional364extension andspreadincreaseconditionalnotactualF4 ordefault. TorontoDominionTexasLLCfullname distinctTorontoDominionBank/nofuzzyalias.'),model_quantity='exhibit_body_excluded_financial_parties_only',raw_byte_start=0,raw_byte_end=5132,locator='rawbytes:0:5132')])
