from authored_helpers import save,money as m
cp='GLOBALFOUNDRIES Inc.'
rows=[]
q='The Company’s total purchases from GF related to wafer manufacturing, research and development activities and other for 2018, 2017 and 2016 were $1.6 billion, $1.1 billion and $0.7 billion, respectively.'
for n,start,end in [('1.6','2017-12-31','2018-12-29'),('1.1','2017-01-01','2017-12-30'),('0.7','2015-12-27','2016-12-31')]:
 rows.append(m(q,n,'1000000000',cp,period_start=start,period_end=end,payer='AMD',receiver=cp,family='commercial',link_type='purchase',stage='delivered',amount_qualifier='exact',amount_nature='related_supplier_purchases_not_explicit_cash_or_supplier_GAAP_revenue',model_quantity='related_supplier_purchases',instrument_key='AMD_GF_WSA'))
for n,end in [('18','2018-12-29'),('27','2017-12-30')]:
 rows.append(m('As of December 29, 2018 and December 30, 2017, the amount of prepayment and receivables related to GF was $18 million and $27 million, respectively, included in Prepayment and receivables - related parties on the Company\'s consolidated balance sheets.',n,'1000000',cp,period_end=end,stage='recognized',amount_qualifier='exact',amount_nature='combined_prepayment_and_receivables_asset_stock_not_pure_advance_or_financing_component',model_quantity='related_prepayment_and_other_receivables',instrument_key='AMD_GF_WSA',flag_unknown_reason='prepayment_and_receivables_not_split_maturity_and_financing_component_not_disclosed'))
for n,end in [('326','2018-12-29'),('241','2017-12-30')]:
 rows.append(m('As of December 29, 2018 and December 30, 2017, the amount of payable to GF was $326 million and $241 million, respectively, included in Payables to related parties on the Company\'s consolidated balance sheets.',n,'1000000',cp,period_end=end,stage='recognized',amount_qualifier='exact',amount_nature='related_supplier_payable_stock_not_explicit_borrowing_or_financing_program',model_quantity='related_supplier_payables',instrument_key='AMD_GF_WSA',flag_unknown_reason='payment_terms_and_financing_component_not_disclosed'))
rows += [
m('In consideration for these rights, the Company agreed to pay GF $100 million, to be paid in a series of installments starting in the fourth quarter of 2016 through the third quarter of 2017. The Company paid these installments in compliance with the agreement.','100','1000000',cp,payer='AMD',receiver=cp,family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_qualifier='exact',instrument_key='AMD_GF_WSA_sixth_amendment_2016',model_quantity='supplier_waiver_rights_cash_payments',amount_nature='aggregate_historical_supplier_commercial_rights_payments_not_customer_funding',flag_unknown_reason='quarter_dates_and_annual_installment_allocation_not_published_in_block'),
dict(quote='Starting in 2017 and continuing through 2020, the Company also agreed to make quarterly payments to GF based on the volume of certain wafers purchased from another wafer foundry.',counterparty=cp,counterparty_evidence='named',payer='AMD',receiver=cp,family='commercial',link_type='purchase_commitment',stage='signed',instrument_key='AMD_GF_WSA',model_quantity='other_foundry_volume_fee_commitment',flag_unknown_reason='fees_unquantified_and_included_in_supplier_purchases_not_additive'),
dict(quote='If the Company does not meet the annual wafer purchase target for any calendar year, the Company will be required to pay to GF a portion of the difference between the Company’s actual wafer purchases and the wafer purchase target for that year.',counterparty=cp,counterparty_evidence='named',payer='AMD',receiver=cp,family='commercial',link_type='purchase_commitment',stage='signed',conditionality='conditional',trigger_description='If the Company does not meet the annual wafer purchase target for any calendar year',trigger_occurred='unknown',instrument_key='AMD_GF_WSA_sixth_amendment_2016',model_quantity='conditional_wafer_purchase_shortfall_payment',flag_unknown_reason='future_targets_portion_cap_and_triggered_amount_not_disclosed'),
dict(quote='In 2018, 2017 and 2016, the Company met its respective annual wafer purchase targets.',counterparty=cp,counterparty_evidence='named',conditionality='conditional',trigger_description='If the Company does not meet the annual wafer purchase target for any calendar year',trigger_occurred='no',instrument_key='AMD_GF_WSA_sixth_amendment_2016',model_quantity='wafer_purchase_shortfall_trigger_status',flag_unknown_reason='no_shortfall_trigger_for_stated_years_not_numeric_zero_debt_or_future_commitments'),
dict(quote='On January 28, 2019, the Company entered into a seventh amendment (the Seventh Amendment) to the Wafer Supply Agreement with GF.',counterparty=cp,counterparty_evidence='named',family='commercial',link_type='purchase_commitment',stage='signed',event_type='amendment',event_date='2019-01-28',instrument_key='AMD_GF_WSA',model_quantity='wafer_supply_agreement_amendment',flag_unknown_reason='commercial_not_financial_covenant_event_date_conflicts_with_January_29_in_proxy'),
dict(quote='The Seventh Amendment modifies certain purchase commitments, pricing and other terms of the WSA applicable to wafer purchases at the 12 nm technology node and above by the Company for the period commencing on January 1, 2019 and continuing through March 1, 2024.',counterparty=cp,counterparty_evidence='named',family='commercial',link_type='purchase_commitment',stage='signed',period_start='2019-01-01',period_end='2024-03-01',instrument_key='AMD_GF_WSA',model_quantity='wafer_purchase_commitment',flag_unknown_reason='purchase_targets_and_committed_amount_not_disclosed'),
dict(quote='If the Company does not meet the annual wafer purchase target for any of these years, the Company will be required to pay to GF a portion of the difference between the Company’s actual wafer purchases and the wafer purchase target for that year.',counterparty=cp,counterparty_evidence='named',payer='AMD',receiver=cp,family='commercial',link_type='purchase_commitment',stage='signed',conditionality='conditional',trigger_description='If the Company does not meet the annual wafer purchase target for any of these years',trigger_occurred='unknown',instrument_key='AMD_GF_WSA_seventh_amendment_2019',model_quantity='conditional_wafer_purchase_shortfall_payment',flag_unknown_reason='target_portion_cap_and_triggered_amount_not_disclosed'),
dict(quote='Under the Warrant Agreement, WCH and its permitted assigns are entitled to purchase 75 million shares of the Company’s common stock (the Warrant Shares) at a purchase price of $5.98 per share. The warrant is exercisable in whole or in part until February 29, 2020.',counterparty='WCH',counterparty_evidence='named',stage='available',instrument_key='AMD_WCH_warrant_2016',model_quantity='supplier_rights_warrant_exercise_terms',flag_unknown_reason='entitlement_and_expiry_not_cash_receipt_or_actual_equity_stock'),
m('On February 5, 2019, WCH notified the Company it would exercise its warrant to purchase 75 million shares of the Company’s common stock at a purchase price of $5.98 per share for a total amount of $448.5 million. The Company expects to receive proceeds of $448.5 million upon the exercise of the warrant and issue the 75 million shares of its common stock to WCH in accordance with the terms of the Warrant Agreement.','448.5','1000000','WCH',event_date='2019-02-05',period_end='2019-02-05',payer='WCH',receiver='AMD',family='financing',link_type='equity_primary',stage='signed',amount_qualifier='exact',instrument_key='AMD_WCH_warrant_2016',model_quantity='primary_warrant_expected_proceeds',amount_nature='expected_proceeds_upon_future_warrant_exercise_not_received_cash',flag_unknown_reason='notice_of_future_exercise_not_actual_receipt_at_this_filing'),
dict(quote='GF, WCH and Mubadala Tech are wholly-owned subsidiaries of Mubadala.',counterparty=cp,counterparty_evidence='named',model_quantity='economic_group_control_evidence',issuer_treatment='wholly_owned_subsidiary_of_Mubadala',flag_unknown_reason='parent_full_name_and_actual_membership_start_not_disclosed_in_this_block')]
save('d053125f5c9065687fe46e6b375d5e4096a8e877f4a202899a9f0ff05f0ed2a2',rows)
