from authored_helpers import save,abstention as a,money as m
fy=dict(period_start='2021-01-01',period_end='2021-12-31')
rows=[
a('Justin Burks, an employee of Amazon, is the son-in-law of Thomas O. Ryder, who served as a director through December 2021.','employee_compensation_outside_counterparty_financing_and_commercial_exposure'),
m('In 2021, Amazon sold approximately $5.3 million of consumer goods to Blue Origin under a line of credit.','5.3','1000000','Blue Origin',**fy,payer='Blue Origin',receiver='Amazon',family='commercial',link_type='purchase',stage='delivered',amount_nature='consumer_goods_sales_under_credit_line_not_explicit_GAAP_revenue_or_cash',model_quantity='related_customer_purchases',flag_unknown_reason='credit_term_not_disclosed_vendor_financing_not_inferred'),
m('Amazon paid Blue Origin $650,000 in data and content license fees, and incurred approximately $669,000 for content production, marketing, and related costs.','650000','1','Blue Origin',**fy,payer='Amazon',receiver='Blue Origin',amount_qualifier='exact',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_nature='data_and_content_license_cash_payments',model_quantity='related_supplier_cash_payments'),
m('Amazon paid Blue Origin $650,000 in data and content license fees, and incurred approximately $669,000 for content production, marketing, and related costs.','669000','1','Blue Origin',**fy,payer='Amazon',receiver='Blue Origin',family='commercial',link_type='purchase',stage='recognized',amount_nature='content_production_marketing_and_related_costs_incurred_not_cash',model_quantity='related_supplier_costs_incurred'),
m('In 2021, Amazon purchased approximately $1.3 million of advertising from, and paid approximately $8.5 million related to digital content to, the Washington Post entities, all on terms negotiated on an arms-length basis.','1.3','1000000','Washington Post entities',**fy,payer='Amazon',receiver='Washington Post entities',family='commercial',link_type='purchase',stage='delivered',amount_nature='advertising_purchases_not_explicit_cash',model_quantity='related_supplier_purchases',flag_unknown_reason='legal_publishing_entities_pending'),
m('In 2021, Amazon purchased approximately $1.3 million of advertising from, and paid approximately $8.5 million related to digital content to, the Washington Post entities, all on terms negotiated on an arms-length basis.','8.5','1000000','Washington Post entities',**fy,payer='Amazon',receiver='Washington Post entities',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_nature='digital_content_cash_payments',model_quantity='related_supplier_cash_payments',flag_unknown_reason='legal_publishing_entities_pending')]
q='In addition, in 2022, Amazon announced agreements with Blue Origin and a third party pursuant to which it expects to pay approximately $7.4 billion for satellite launch and related services through 2028, of which approximately $2.7 billion is expected to be paid to Blue Origin.'
rows += [m(q,'7.4','1000000000','Blue Origin and a third party',payer='Amazon',receiver='Blue Origin and a third party',counterparty_evidence='anonymous',amount_nature='expected_aggregate_launch_payments_through_2028_not_firm_remaining_commitment',model_quantity='expected_launch_payments',family='commercial',link_type='purchase_commitment',stage='signed',instrument_key='AMZN_2022_satellite_launch_agreements',flag_unknown_reason='remaining_vs_historical_and_unnamed_third_party_allocation_unknown'),
m(q,'2.7','1000000000','Blue Origin',payer='Amazon',receiver='Blue Origin',amount_nature='expected_Blue_Origin_component_of_aggregate_launch_payments_not_additive',model_quantity='expected_launch_payments_component',family='commercial',link_type='purchase_commitment',stage='signed',instrument_key='AMZN_2022_satellite_launch_agreements',flag_unknown_reason='remaining_vs_historical_payment_split_unknown')]
save('32ac1563126c551f260c136520dbb6d16ded2068c7e9b7607701ea0d6d92ae2d',rows)
