from pathlib import Path
from secfragility.reader import store,block_for
r=Path('.').resolve();k='49c9c0bf62d0c714ab791f7821056526b2326f3c018fe8e5eddd37bb91f2ac0b';b=block_for(r,k)
def t(i,q,**kw):
 f=b['candidates'][i]
 return {x:f.get(x) for x in ('unit','currency','period_start','period_end')}|dict(quote=q,amount=f['value'],amount_origin='tagged_reference',tagged_fact_id=f['fact_id'],amount_qualifier='exact')|kw
opt='In connection with the issuance of the 2021 Convertible Senior Secured Notes in October 2021, the Company granted Magnetar an option to purchase up to $15 million of the Company’s Class A common stock at the IPO price, which is equal to 375,000 shares at the IPO price of $40.00 per share, which is exercisable until the one-year anniversary of the IPO.'
notes='In October 2022, the Company executed a note issuance agreement and a note purchase agreement (the “2022 Senior Secured Notes”) and between October 2022 and April 2023, the Company issued $125 million of 2022 Senior Secured Notes with maturity dates between October 2025 and April 2026 to funds or accounts managed or advised by Magnetar, along with warrants to purchase 12,144,668 shares of the Company’s Class A common stock.'
s1='As of March 31, 2025 and December 31, 2024, $413 million and $438 million in aggregate principal amount, respectively, of the DDTL 1.0 Facility was outstanding and held by funds or accounts managed or advised by Magnetar.'
f1='The Company has paid to funds or accounts managed or advised by Magnetar $25 million and $0 million in principal and incurred $15 million and $13 million in interest expense for the three months ended March 31, 2025 and 2024, respectively.'
s2='As of March 31, 2025 and December 31, 2024, $121 million and $106 million of the DDTL 2.0 Facility was outstanding and held by funds or accounts managed or advised by Magnetar, respectively.'
c=dict(counterparty_evidence='anonymous',family='financing',link_type='loan_or_facility',flag_unknown_reason='individual_Magnetar_managed_funds_pending_not_manager_consolidation')
pr=dict(**c,payer='CoreWeave',receiver='funds or accounts managed or advised by Magnetar',amount_nature='principal_cash_repayment_to_managed_funds',model_quantity='related_lender_principal_cash_paid',stage='drawn_or_paid',event_type='repayment',component_kind='principal',instrument_key='CRWV_DDTL_1_0_Magnetar_funds')
i=dict(**c,amount_nature='interest_expense_not_cash_payment',model_quantity='related_lender_interest_expense',stage='recognized',event_type='recognition',component_kind='interest')
pstock=dict(**c,amount_nature='explicit_principal_held_by_managed_funds_not_total_facility',model_quantity='related_lender_principal_outstanding',block='recognized_liabilities',category_id='debt',measurement_basis='principal',component_kind='principal',stage='drawn_or_paid',instrument_key='CRWV_DDTL_1_0_Magnetar_funds')
cstock=dict(**c,amount_nature='outstanding_carrying_amount_held_by_managed_funds_not_total_facility',model_quantity='related_lender_debt_carrying_amount',block='recognized_liabilities',category_id='debt',measurement_basis='carrying_value',stage='recognized',instrument_key='CRWV_DDTL_2_0_Magnetar_funds')
rows=[t(0,opt,counterparty='Magnetar Financial LLC',counterparty_evidence='named',amount_qualifier='up_to',amount_nature='subscription_option_limit_not_funding',model_quantity='equity_subscription_option_limit',family='financing',link_type='equity_primary',stage='signed',instrument_key='CRWV_2021_Magnetar_IPO_option',flag_unknown_reason='actual_fund_pending_no_exercise_as_of_2025_03_31'),
t(1,opt,counterparty='Magnetar Financial LLC',counterparty_evidence='named',amount_nature='subscription_option_underlying_shares_not_cash',model_quantity='subscription_option_share_count',stage='signed',instrument_key='CRWV_2021_Magnetar_IPO_option'),
t(2,opt,counterparty='Magnetar Financial LLC',counterparty_evidence='named',amount_nature='option_exercise_price_per_share_not_cash',model_quantity='subscription_option_exercise_price',stage='signed',instrument_key='CRWV_2021_Magnetar_IPO_option'),
t(4,'As of March 31, 2025, this option is still outstanding and has not been exercised.',counterparty='Magnetar Financial LLC',counterparty_evidence='named',amount_nature='explicit_zero_option_exercises_not_zero_equity_exposure',model_quantity='subscription_option_shares_exercised',instrument_key='CRWV_2021_Magnetar_IPO_option'),
t(5,notes,**c,amount_nature='original_note_face_amount_not_current_principal_or_net_cash',model_quantity='senior_note_original_face_amount',stage='signed',instrument_key='CRWV_2022_2025_Senior_Notes'),
t(6,notes,counterparty_evidence='anonymous',amount_nature='warrant_underlying_shares_not_equity_cash',model_quantity='warrant_underlying_shares',stage='signed',instrument_key='CRWV_2022_Magnetar_warrants'),
t(7,'In July 2024, the Company redeemed these notes in full, paying $137 million.',**c,payer='CoreWeave',receiver='funds or accounts managed or advised by Magnetar',amount_nature='full_note_redemption_cash_not_principal_only',model_quantity='note_redemption_cash_payment',stage='settled',event_type='repayment',instrument_key='CRWV_2022_2025_Senior_Notes'),
dict(quote='This option expired unexercised in connection with the IPO.',counterparty_evidence='anonymous',stage='terminated',event_type='expiry',model_quantity='unexercised_subscription_option_expiry_not_equity_funding',instrument_key='CRWV_2022_Magnetar_IPO_option'),
dict(quote='In March 2025, the warrants were amended to fix the exercise price per share, and the Company concluded that these warrants met the requirements for equity classification.',counterparty_evidence='anonymous',event_type='amendment',model_quantity='warrant_price_amendment_not_financial_covenant_waiver',instrument_key='CRWV_2022_Magnetar_warrants'),
t(10,s1,**pstock),t(11,s1,**pstock),t(12,f1,**pr),t(13,f1,**pr),
t(14,f1,**i,instrument_key='CRWV_DDTL_1_0_Magnetar_funds'),t(15,f1,**i,instrument_key='CRWV_DDTL_1_0_Magnetar_funds'),
t(16,s2,**cstock),t(17,s2,**cstock),
t(18,'The Company has not made principal payments on the DDTL 2.0 Facility as of March 31, 2025.',**c,amount_nature='explicit_zero_principal_cash_repayments_not_zero_debt',model_quantity='related_lender_principal_cash_paid',component_kind='principal',instrument_key='CRWV_DDTL_2_0_Magnetar_funds'),
t(19,'The Company incurred $3 million in interest expense for the three months ended March 31, 2025 associated with amounts held by funds or accounts managed or advised by Magnetar.',**i,instrument_key='CRWV_DDTL_2_0_Magnetar_funds'),
t(20,'In connection with the MagAI Capacity Agreement with MagAI Ventures, the Company had $249 million outstanding under the Magnetar Loan as of March 31, 2025.',counterparty='MagAI Ventures',counterparty_evidence='named',amount_nature='capacity_refundable_deposit_current_debt_carrying_amount_not_revenue',model_quantity='refundable_capacity_deposit_debt_carrying_value',block='recognized_liabilities',category_id='debt',measurement_basis='carrying_value',stage='recognized',instrument_key='MagAI_Capacity_Agreement',issuer_treatment='DebtCurrent_XBRL'),
dict(quote='The deposit of $230 million was previously classified within other current liabilities on the condensed consolidated balance sheets as of December 31, 2024.',abstained=True,abstention_reason='tagged_face_amount_context_2025_03_31_conflicts_with_narrative_prior_balance_date_2024_12_31'),
t(22,'The Company incurred $19 million in interest expense in connection with the Magnetar Loan for the three months ended March 31, 2025.',counterparty='MagAI Ventures',counterparty_evidence='named',amount_nature='capacity_deposit_interest_expense_not_cash',model_quantity='capacity_deposit_interest_expense',stage='recognized',component_kind='interest',instrument_key='MagAI_Capacity_Agreement'),
t(23,'In June 2024, the Company contributed $50 million to a fund managed by Magnetar in connection with the fund’s purchase of a third-party’s preferred stock.',counterparty_evidence='anonymous',amount_nature='historical_private_equity_investment_via_consolidated_fund_not_external_cash_to_fund',model_quantity='private_equity_investment_via_consolidated_fund',stage='recognized',flag_unknown_reason='fund_consolidated_underlying_private_company_pending_tagged_June_2024_not_current_stock'),
dict(quote='The Company consolidated the fund and accounted for the purchased preferred stock as privately held equity securities that do not have a readily determinable fair value measured at cost, with subsequent adjustments for observable price changes or impairments.',counterparty_evidence='anonymous',model_quantity='consolidated_investment_fund_measurement_alternative',issuer_treatment='ASC321_measurement_alternative',flag_unknown_reason='no_actual_specific_gain_or_impairment_disclosed')]
print(store(r,k,rows))
