from work.authored_helpers import *
save('dc109ffc04342903169f6706920f34185e90022d3553e37d5358ff4d3f2c8cf7',[
dict(quote='intends to cause Brocade to provide notice',stage='intent_non_binding',model_quantity='Brocade_old_notes_repurchase_intent',flag_unknown_reason='Brocade_alias_legalfullname_unknown_Jan16_2018_expected_notactualpay_amountunknown'),abstention('on or about January 16, 2018','Entireitemread. Futureoldnote repurchase notice not actualrepayment/guaranteecall or newfunding.')])
save('dd783faa96b88cc1ab78503445365991164941c6a688b362556184a09592c6c7',[
dict(quote='On November 6, 2017, NVIDIA Land Development, LLC, or NVIDIA Land, a wholly-owned subsidiary of NVIDIA Corporation',counterparty='NVIDIA Land Development, LLC',counterparty_evidence='named',model_quantity='NVIDIA_Land_current_legal_membership',flag_unknown_reason='whollysub_exactstart_unknown'),money('from Wachovia for approximately $350 million','350','1000000','Wachovia Service Corporation',payer='NVIDIA Land Development, LLC',receiver='Wachovia Service Corporation',family='commercial',link_type='purchase',stage='signed',event_date='2017-11-06',model_quantity='Santa_Clara_property_purchase_option_exercised_price',amount_nature='option_exercised_future_purchase_price_not_actualpaid',flag_unknown_reason='L1_fullnames_samefirstclause_property_price_mixes_participants_investment_int_rent_fees_unknownsplit_no_actualclosing'),dict(quote='NVIDIA Land has obtained a waiver from a majority of the Participants of the requirement to provide 90 days advance notice to exercise the purchase option.',stage='signed',model_quantity='lease_property_purchase_option_notice_waived',flag_unknown_reason='exactwaiverdate_unknown_procedural_notice_not_actualfinancialpayment/defaultwaiver_F4_unknown'),dict(quote='On June 19, 2015, NVIDIA Land entered into the Ground Lease, Real Property Lease, Participation Agreement, Agency Agreement and related documents',stage='signed',event_date='2015-06-19',family='financing',link_type='lease_financing',model_quantity='Santa_Clara_campus_historical_lease_financing',flag_unknown_reason='historicalassertion_knownNov9_2017_no_floor_extension_investmentcash_unknown'),abstention('Upon completing the purchase, the agreements referenced above and related documents will be terminated','Full entireitem/exhibitreferences read. ActualoptionexerciseNov6notcashclosing; futuretitle/lease termination notactualF9capacityexit. Majoritynoticewaiver notcalledguar or financialbreach; expectedQ4FY18noexactpurchase date.')])
k='9babe0657430b2c06e824080a77a0b6b99db2e4531a31f123a0333848ff740bc'
rows=[]
for quote,num,year in [('$1,250,000,000 aggregate principal amount of its 2.625% notes due 2023','1250000000','2023'),('$2,000,000,000 aggregate principal amount of its 2.950% notes due 2024','2000000000','2024'),('$2,750,000,000 aggregate principal amount of its 3.250% notes due 2027','2750000000','2027'),('$1,750,000,000 aggregate principal amount of its 3.800% notes due 2037','1750000000','2037'),('$2,250,000,000 aggregate principal amount of its 4.000% notes due 2047','2250000000','2047')]:
    rows.append(money(quote,num,'1','underwriters',counterparty_evidence='anonymous',family='financing',link_type='loan_or_facility',stage='drawn_or_paid',event_date='2017-11-09',model_quantity='new_'+year+'_note_face_issued',amount_qualifier='exact',amount_nature='actual_face_not_netcash',flag_unknown_reason='underwriteNov7_notclose_netandsecurity_unknown_total10b_containscomponents'))
rows.append(dict(quote='Oracle (formerly known as Ozark Holding Inc.), Oracle Systems Corporation (formerly known as Oracle Corporation)',model_quantity='two_distinct_Oracle_legal_names_and_former_names',flag_unknown_reason='currentOracleCorp_exOzark_distinct_OracleSystems_exOracleCorp_exactrenamedaysunknown'))
rows.append(abstention('an officers’ certificate issued pursuant thereto','Full entireitemread. Newnotesunderexistingindenture/officerscertificate not F4existingfinancialclausechange. TrusteeBNYMellonTrustformerlyBNYTrustdistinctCitibank/legalnameproof only not lenders allocation; noactualcashproof.'))
save(k,rows)
