from work.authored_helpers import *
save('150e5bca1a82838f9cdb9f0c4cfc3356f6b427e91536bd9cc5f1eee296ef1d08',[abstention('filed a motion for preliminary approval of the settlement','Full item read. Sep25motion/stipulation derivative litigation, no court final approval/actual quantitative cash or investment impairment. Exhibit99.1not imported.')])
save('c02d4d1d6d560728113d33cd6aa5bcac35e41a581df8fe0a415876bf241d0c3b',[abstention('declared the payment of its quarterly dividend of $0.06 per share','Full item read. Sep25announcement futureOct28/recordOct12and Bermuda law/payment conditions, no aggregate actual cash payment or distress; separate furnishedrelease not entireitem.')])
rows=[dict(quote='NVIDIA International Holdings Inc., a Delaware corporation and a wholly owned subsidiary of NVIDIA (“NVIDIA Holdings”), Arm Limited, a company organized under the laws of England & Wales (“Arm”), SoftBank Group Capital Limited, a company organized under the laws of England & Wales (“SoftBank”), and SVF Holdco (UK) Limited, a company organized under the laws of England & Wales',counterparty='Arm Limited',counterparty_evidence='named',stage='signed',event_date='2020-09-13',model_quantity='Arm_purchase_signed_legal_parties',flag_unknown_reason='NVIDIA_Holdings_DE_whollyNVIDIA_current_Arm_SoftBank_Group_Capital_SVF_Holdco_EW_distinct_future_Arm_acquisition_not_actual_no_fundmanager_alias')]
for quote,number,scale,cp,quantity,nature in [
('in a transaction valued at $40 billion.','40','1000000000','Arm Limited','Arm_transaction_reference_value','aggregate_reference_mix_cash_shares_contingent_employee_awards_not_actual_purchase_cash'),
('pay the Sellers and Arm $2 billion in cash','2','1000000000','Sellers_and_Arm','signing_consideration_cash_agreed','agreed_advance_and_IP_license_mixed_cash_no_allocation_Sellers_Arm_not_actual_paid'),
('pay the Sellers $10 billion in cash (subject to certain deductions and adjustments)','10','1000000000','Sellers','closing_cash_agreed','future_closing_cash_subject_adjustments_not_actual_paid'),
('with an aggregate value of $21.5 billion','21.5','1000000000','Sellers','closing_stock_reference_value','reference_value44_3million_NVIDIA_shares_30day_market_basis_not_cash_or_actual_issued'),
('earn out payments of up to $5 billion in cash or up to 10.3 million shares','5','1000000000','Sellers','earnout_cash_alternative_cap','conditional_cash_OR10_3million_shares_not_two_payments_actual_performance_unknown'),
('with an aggregate value not to exceed $1.5 billion to employees of Arm following the Closing','1.5','1000000000','Arm_employees','postclosing_employee_RSU_reference_cap','future_employee_share_award_cap_not_cash_to_target_or_sellers')]:
 rows.append(money(quote,number,scale,cp,counterparty_evidence='named' if cp=='Arm Limited' else 'anonymous',stage='signed',event_date='2020-09-13',model_quantity=quantity,amount_qualifier='up_to' if quantity.endswith('cap') else 'exact',amount_nature=nature,flag_unknown_reason='pending_regulatory_other_conditions_actual_execution_cash_dates_and_seller_allocations_unknown_no_primary_target_financing_or_consolidation'))
rows.extend([dict(quote='contingent on the achievement of certain financial performance targets for Arm during the fiscal period beginning April 1, 2021 and ending March 31, 2022',stage='signed',event_date='2020-09-13',model_quantity='Arm_earnout_trigger',trigger_description='contingent on the achievement of certain financial performance targets for Arm during the fiscal period beginning April 1, 2021 and ending March 31, 2022',flag_unknown_reason='targets_and_actual_trigger_cash_or_share_choice_unknown'),dict(quote='If the Purchase Agreement is terminated under certain circumstances, the Sellers will refund a portion of the Signing Consideration to NVIDIA.',stage='signed',event_date='2020-09-13',model_quantity='conditional_signing_advance_refund',trigger_description='If the Purchase Agreement is terminated under certain circumstances',flag_unknown_reason='portion_conditions_and_actual_refund_unknown_not_entire2bn_refundable'),abstention('The Share Purchase is not subject to a financing condition.','Full entire item read:allparties/cashshareearnoutemployeecomponents/IPlicense/covenants/conditions/termination/qualifications. Signedpromise2bnot actual paymentproof or laterretained1.25bcontradiction. Future four3monthoutside-dateextensionsnotactual default. No financial-covenant F4/guarantee call or actual customer funding.')])
save('4a28ca23d18595c0829e32457ff0967c625bfbc39412913e0af699fc718a7ddf',rows)
