from work.authored_helpers import *
k='18257b5bffd5390df2d463670d503dffa76746562dae58841795ad7c8fb59337'
save(k,[dict(quote='On July 11, 2025, Broadcom Inc. (the “Company”) repaid all outstanding obligations under the credit agreement, dated as of August 15, 2023',event_date='2025-07-11',stage='settled',event_type='repayment',model_quantity='2023_term_credit_all_obligations_repaid',flag_unknown_reason='total_cash_including_interest_fees_not_disclosed_capacity_F9_not_applicable'),money('The Company had an aggregate principal amount of $6.0 billion of term loans outstanding under the Existing Credit Agreement immediately prior to its termination.','6','1000000000','lenders_named_in_agreement',counterparty_evidence='anonymous',payer='Broadcom Inc.',stage='settled',event_date='2025-07-11',period_end='2025-07-11',amount_qualifier='exact',family='financing',link_type='loan_or_facility',model_quantity='2023_term_credit_principal_extinguished',amount_nature='prior_outstanding_principal_extinguished_by_all_obligation_repayment_not_total_cash_interest_fees',flag_unknown_reason='principal_same_repayment_event_not_separate_outflow_individual_lender_allocations_unknown'),money('The Existing Credit Agreement originally provided for a $30.4 billion term loan credit facility.','30.4','1000000000','lenders_named_in_agreement',counterparty_evidence='anonymous',stage='terminated',event_date='2025-07-11',period_end='2025-07-11',amount_qualifier='exact',model_quantity='2023_term_credit_original_limit_terminated',amount_nature='original_facility_limit_not_current6bn_principal_or_unused_cash'),abstention('Absent termination, the term loan credit facility under the Existing Credit Agreement would have matured in 2028.','Full item: actual all-obligation repayment,6bnprior principal, original30.4bnlimit, maturity/rate and lenders banking-service clauses read. Financial facility termination not capacity termination or covenant waiver/default. Exact total cash incl interest/fees and individual lender allocation unknown; agentBankofAmerica not assumed sole lender.')])
k='11ac261378d0f73b4567914a5e267a496682b6ad4176895d13ea681ed6adc088'
q='pursuant to which the Company agreed to issue and sell to the Underwriters $6,000,000,000 aggregate principal amount of its senior notes, consisting of $1,750,000,000 aggregate principal amount of its 4.600% senior notes due 2030 (the “2030 Notes”), $1,750,000,000 aggregate principal amount of its 4.900% senior notes due 2032 (the “2032 Notes”) and $2,500,000,000 aggregate principal amount of its 5.200% senior notes due 2035'
rows=[]
for number,year in [('6000','aggregate'),('1750','2030'),('1750','2032'),('2500','2035')]:rows.append(money(q,number,'1000000','several_underwriters',counterparty_evidence='anonymous',receiver='Broadcom Inc.',stage='signed',event_date='2025-07-07',period_end='2025-07-07',amount_qualifier='exact',family='financing',link_type='loan_or_facility',model_quantity='senior_notes_'+year+'_agreed_face',amount_nature='agreement_face_aggregate_series_nonadditive_not_exact_net_cash',flag_unknown_reason='subsequent_issuance_confirmed_same_block_exact_issue_day_unknown'))
rows += [dict(quote='The Notes were sold pursuant to the Underwriting Agreement and were issued pursuant to the Prospectus Supplement.',stage='recognized',model_quantity='three_senior_note_series_issued',flag_unknown_reason='no_exact_issue_day_or_net_cash_amount'),dict(quote='The Company used the net proceeds received from the issuance of the Notes, together with cash on hand, to repay all outstanding obligations under the Existing Credit Agreement as described in Item 1.02 above.',stage='settled',event_type='repayment',model_quantity='actual_notes_net_proceeds_and_cash_used_for_term_credit_repayment',flag_unknown_reason='documented_refinancing_total_net_cash_and_cash_on_hand_contribution_not_quantified_same_repayment_as_Item1_02_not_additive'),dict(quote='The Notes will not be guaranteed by any of the Company’s subsidiaries',model_quantity='senior_notes_explicit_no_subsidiary_guarantees'),abstention('as supplemented by the Supplemental Indenture No. 4, dated July 11, 2025','Full item: underwriting/issued note faces, maturity/unsecured structural subordination/no subsidiary guarantees, actual received net proceeds and on-hand cash used for same loan repayment read. No net cash amount or exact new issue date, actual financial-covenant waiver/default/call/capacity termination. New-series supplement without Item3.03 not autonomous amendment body; faces not treated as received net cash.')]
save(k,rows)
