from work.authored_helpers import *
save('0170f6110e7b1f02302d42a5d25376be203f6a1908e01c42b14399e323d3e245',[
dict(quote='NVIDIA Holdings, a wholly owned subsidiary of NVIDIA Corporation.',counterparty='NVIDIA International Holdings Inc.',counterparty_evidence='named',model_quantity='NVIDIA_Holdings_current_legal_group_membership',flag_unknown_reason='full_name_defined_earlier_same_block_not_Mellanox_current_membership_or_exact_sub_start'),abstention('The transaction is currently expected to close on or about April 27, 2020, subject to all remaining customary closing conditions.','Full item and signature read. Apr16China approval and priorEU/Mexico/May23,2019HSRexpiry; pendingMellanoxacquisitionnotactualApr27close/consolidation/paymentproof here.')])
rows=[money('up to an aggregate purchase price, excluding accrued and unpaid interest, of $3.75 billion','3.75','1000000000','existing_noteholders',counterparty_evidence='anonymous',stage='intent_non_binding',model_quantity='tender_aggregate_purchase_price_cap',amount_qualifier='up_to',amount_nature='offer_price_cap_not_actual_purchase_or_note_face'),money('of which up to $250 million may be used to purchase the 2.200% senior notes due January 15, 2021','250','1000000','existing_noteholders',counterparty_evidence='anonymous',stage='intent_non_binding',model_quantity='January2021_tender_purchase_price_sublimit',amount_qualifier='up_to',amount_nature='explicit_component_of3_75bn_cap_not_750mface_or_actualcash')]
for quote,number,issuer,series in [('$ | 3,500,000,000','3500000000','Broadcom Corporation','2022_3000'),('$ | 2,000,000,000','2000000000','Broadcom Inc.','2021_3125'),('$ | 750,000,000','750000000','Broadcom Corporation','2021_2200')]:
 rows.append(money(quote,number,'1',issuer,stage='recognized',model_quantity='existing_note_face_in_tender_table_'+series,amount_qualifier='exact',amount_nature='aggregate_outstanding_old_face_not_tendered_accepted_face_or_actual_cash',flag_unknown_reason='exact_stock_measurement_day_not_explicit_table_known_Apr15_announced_Apr14_no_default_from_passed_maturity'))
rows.append(abstention('the new total consideration for (i) the 2022 Notes is $1,025.00 per $1,000 principal amount','Full entire item and table/4footnotes/cautions read. Offerper1000prices1025/1015andJanuary1000incl30premium not aggregate payment; increasedofferprice/deadlines not F4 financial-covenant amendment. ExtendedApr21earlydeadline/expectedApr23settlement not actual. No quantifiedacceptedface or cash.'))
save('77e8320755373fc485f7ff46a7e40cdd1a6bd997a50e0e0a9b4898415e2fc250',rows)
rows=[money('completed its issuance and sale of $4.5 billion in aggregate principal amount of senior unsecured notes','4.5','1000000000','initial_note_purchasers',counterparty_evidence='anonymous',receiver='Broadcom Inc.',stage='recognized',event_date='2020-04-09',family='financing',link_type='loan_or_facility',model_quantity='aggregate_issued_notes_face',amount_qualifier='exact',amount_nature='aggregate_face_includes2series_not_actual_net_cash')]
for quote,year in [('$2,250 million aggregate principal amount of 4.700% senior notes due 2025','2025'),('$2,250 million aggregate principal amount of 5.000% senior notes due 2030','2030')]:
 rows.append(money(quote,'2250','1000000','initial_note_purchasers',counterparty_evidence='anonymous',receiver='Broadcom Inc.',stage='recognized',event_date='2020-04-09',family='financing',link_type='loan_or_facility',model_quantity='issued_note_face_'+year,amount_qualifier='exact',amount_nature='component_of4_5bn_face_not_actual_net_cash'))
for name in ['Broadcom Technologies Inc.','Broadcom Corporation']:
 rows.append(dict(quote='Each series of Notes will initially be fully and unconditionally guaranteed, jointly and severally, on an unsecured, unsubordinated basis by Broadcom Technologies Inc., a Delaware corporation and Broadcom Corporation, a California corporation',counterparty=name,counterparty_evidence='named',stage='signed',event_date='2020-04-09',family='credit_support',link_type='guarantee',model_quantity='initial_subsidiary_notes_guarantee_'+name.replace(' ','_'),flag_unknown_reason='same_underlying4_5bn_notes_not_additive_no_actual_guarantee_call'))
rows.extend([money('up to an aggregate purchase price, excluding accrued and unpaid interest, of $3.75 billion','3.75','1000000000','existing_noteholders',counterparty_evidence='anonymous',stage='intent_non_binding',model_quantity='concurrent_tender_purchase_price_cap',amount_qualifier='up_to',amount_nature='pending_offer_price_cap_not_actualcash_or_additive_to_new_issue_face'),money('of which up to $250 million may be used to purchase the 2.200% senior notes due January 15, 2021','250','1000000','existing_noteholders',counterparty_evidence='anonymous',stage='intent_non_binding',model_quantity='tender_price_sublimit',amount_qualifier='up_to',amount_nature='component_of3_75bn_offer_not_extra_or_actualcash'),abstention('The Company intends to use the net proceeds from the sale of the Notes to repay certain of its existing indebtedness','Full item read:actualnewissue/guarantees,pendingtenders/plannedloanrepay, originalindenture/redemption/ranking/covenants/default/registration. No actualdebtredemption, netcash, F4 originalclause/default/penalty inferred from passedApr9,2025deadline. Securitiesfirmnotbankparent/trusteefinalinvestor.')])
save('638edb370be0a02c748ea2a02419f2019523bd61d3ab221ec7ebe4351db1b615',rows)
