from authored_helpers import save,abstention as a,money as m
fy=dict(period_start='2020-06-01',period_end='2021-05-31')
sales=[('Annapurna Releasing LLC','393000','Annapurna Releasing LLC purchased approximately $393,000 in cloud SaaS products.'),('Autonomous Medical Devices, Inc.','130000','Autonomous Medical Devices, Inc. purchased approximately $130,000 in cloud IaaS and PaaS products.'),('PA Hotel Holdings, LLC','176000','PA Hotel Holdings, LLC purchased approximately $176,000 in cloud SaaS products, software licenses, training, and / support.'),('Lanai Resorts, LLC','208000','Lanai Resorts, LLC purchased approximately $208,000 in hardware, cloud SaaS products, software licenses, and support.')]
rows=[m(q,n,'1',cp,**fy,payer=cp,receiver='Oracle',family='commercial',link_type='purchase',stage='delivered',amount_nature='related_customer_purchases_not_explicit_GAAP_revenue_or_cash',model_quantity='related_customer_purchases',instrument_key='ORCL_fiscal_2021_related_customer_purchases') for cp,n,q in sales]
rows += [
m('In fiscal 2021, the total amount of all purchases by these companies was approximately $1.1 million.','1.1','1000000','companies related to Mr. Ellison',**fy,counterparty_evidence='anonymous',amount_nature='aggregate_related_customer_purchases_includes_named_components_not_additive',model_quantity='related_customer_purchases_total',instrument_key='ORCL_fiscal_2021_related_customer_purchases'),
m('In fiscal 2021, the total amount of all purchases from these companies was approximately $8,700.','8700','1','companies related to Mr. Ellison',**fy,counterparty_evidence='anonymous',amount_nature='aggregate_related_supplier_purchases',model_quantity='related_supplier_purchases_total'),
dict(quote='then Mr. Ellison will reimburse us for the difference.',counterparty='Mr. Ellison',counterparty_evidence='named',payer='Mr. Ellison',receiver='Oracle',family='credit_support',link_type='guarantee',stage='signed',conditionality='conditional',trigger_description='if we present Mr. Ellison with reasonable evidence of a lower price or rate for the same goods or services offered by the related company',trigger_occurred='unknown',model_quantity='related_supplier_price_protection_reimbursement',flag_unknown_reason='cap_and_called_amount_not_disclosed_person_not_legal_entity'),
dict(quote='Total related person transaction revenues were approximately 0.0028% of our total revenues and total related person operating expenses were approximately 0.1% of our total operating expenses in fiscal 2021.',amount='0.0028',unit='percent',amount_origin='narrative_only',amount_qualifier='approximately',**fy,amount_nature='related_person_revenue_percent_not_financed_customer_revenue_share',model_quantity='related_person_revenue_percent',counterparty_evidence='anonymous',flag_unknown_reason='all_related_person_transactions_not_E2_financed_customer_category'),
dict(quote='Total related person transaction revenues were approximately 0.0028% of our total revenues and total related person operating expenses were approximately 0.1% of our total operating expenses in fiscal 2021.',amount='0.1',unit='percent',amount_origin='narrative_only',amount_qualifier='approximately',**fy,amount_nature='related_person_operating_expense_percent',model_quantity='related_person_operating_expense_percent',counterparty_evidence='anonymous'),
dict(quote='Oracle entered into an agreement providing for an in-kind exchange with the SailGP sailing league (operated by Mr. Ellison’s company F50 League LLC)',counterparty='F50 League LLC',counterparty_evidence='named',family='commercial',link_type='purchase',stage='signed',model_quantity='in_kind_sponsorship_exchange',issuer_treatment='in_kind_exchange',flag_unknown_reason='no_explicit_GAAP_revenue_or_contra_revenue_treatment'),
m('Oracle received customer hospitality experiences valued at approximately $2.0 million; and SailGP received Oracle products and services valued at approximately $2.3 million.','2.0','1000000','SailGP',**fy,payer='Oracle',receiver='SailGP',family='commercial',link_type='purchase',stage='delivered',amount_nature='received_hospitality_experience_value_not_cash',model_quantity='noncash_sponsorship_value',instrument_key='ORCL_F50_SailGP_sponsorship',flag_unknown_reason='legal_recipient_pending_no_explicit_contra_revenue_accounting'),
m('Oracle received customer hospitality experiences valued at approximately $2.0 million; and SailGP received Oracle products and services valued at approximately $2.3 million.','2.3','1000000','SailGP',**fy,payer='SailGP',receiver='Oracle',family='commercial',link_type='purchase',stage='delivered',amount_nature='provided_Oracle_products_services_value_not_cash',model_quantity='noncash_product_service_value',instrument_key='ORCL_F50_SailGP_sponsorship',flag_unknown_reason='commercial_orientation_customer_to_supplier_no_explicit_GAAP_revenue'),
dict(quote='Under certain circumstances, Oracle has the obligation to acquire additional equity of Ampere from the other equity holders of Ampere, including Ms. James.',counterparty='Ampere Computing LLC',counterparty_evidence='named',model_quantity='conditional_secondary_equity_acquisition',stage='signed',conditionality='conditional',trigger_description='Under certain circumstances',trigger_occurred='unknown',flag_unknown_reason='specific_circumstances_cap_and_called_amount_not_disclosed_secondary_not_primary_funding'),
m('In July 2020, Oracle invested $40 million in an equity fundraising round for Ampere Computing LLC (Ampere), a developer of high-performance semiconductors for hyperscale cloud, storage, and edge computing.','40','1000000','Ampere Computing LLC',period_start='2020-07-01',period_end='2020-07-31',payer='Oracle',receiver='Ampere Computing LLC',amount_qualifier='exact',family='financing',link_type='equity_primary',stage='recognized',event_type='funding',amount_nature='equity_fundraising_round_investment_not_current_holding',model_quantity='equity_primary_investment',instrument_key='ORCL_Ampere_July_2020_equity_round',flag_unknown_reason='published_month_not_exact_day_cash_form_and_current_holding_not_disclosed'),
m('In March 2021, Oracle invested an additional $300 million in a subsequent equity fundraising round for Ampere.','300','1000000','Ampere Computing LLC',period_start='2021-03-01',period_end='2021-03-31',payer='Oracle',receiver='Ampere Computing LLC',amount_qualifier='exact',family='financing',link_type='equity_primary',stage='recognized',event_type='funding',amount_nature='equity_fundraising_round_investment_not_current_holding',model_quantity='equity_primary_investment',instrument_key='ORCL_Ampere_March_2021_equity_round',flag_unknown_reason='published_month_not_exact_day_cash_form_and_current_holding_not_disclosed'),
m('In fiscal 2021, Oracle paid Ampere approximately $195,000 for hardware used for development and testing purposes and also purchased Ampere processors valuing $3.4 million against a $25 million pre-payment order placed in fiscal 2020.','195000','1','Ampere Computing LLC',**fy,payer='Oracle',receiver='Ampere',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_nature='hardware_development_and_testing_cash_payments',model_quantity='related_supplier_cash_payments'),
m('In fiscal 2021, Oracle paid Ampere approximately $195,000 for hardware used for development and testing purposes and also purchased Ampere processors valuing $3.4 million against a $25 million pre-payment order placed in fiscal 2020.','3.4','1000000','Ampere Computing LLC',**fy,payer='Oracle',receiver='Ampere',amount_qualifier='exact',family='commercial',link_type='purchase',stage='delivered',amount_nature='processor_purchases_against_historical_prepayment_not_new_cash',model_quantity='processor_prepayment_application',instrument_key='ORCL_Ampere_fiscal_2020_processor_prepayment'),
m('In fiscal 2021, Oracle paid Ampere approximately $195,000 for hardware used for development and testing purposes and also purchased Ampere processors valuing $3.4 million against a $25 million pre-payment order placed in fiscal 2020.','25','1000000','Ampere Computing LLC',period_start='2019-06-01',period_end='2020-05-31',payer='Oracle',receiver='Ampere',amount_qualifier='exact',family='commercial',link_type='prepayment',stage='signed',amount_nature='historical_processor_prepayment_order_not_current_cash',model_quantity='processor_prepayment_order',instrument_key='ORCL_Ampere_fiscal_2020_processor_prepayment'),
a('Steven Janicki, Vice President, Global IT Communications and Experience, is Mr. Ellison’s half-brother.','employee_compensation_outside_counterparty_financing_and_commercial_exposure')]
save('85efbd7304ba131d944d742a2d38b5f98023428ff0afb3da444d5beaaa9a7e68',rows)
