from work.authored_helpers import *
k='2601b5c9df4da31143119c0234cdfa67b1d5e29df63100d3c85946f51d476e86'
rows=[money('Issuance of $7.75 Billion Aggregate Principal Amount of Notes','7.75','1000000000','unidentified_noteholders',counterparty_evidence='anonymous',event_date='2025-02-03',stage='recognized',amount_qualifier='exact',model_quantity='notes_issued_face_aggregate',amount_nature='face_aggregate_not_net_cash_components_nonadditive')]
for quote,number,quantity in [('$500,000,000 aggregate principal amount of its Floating Rate Notes due 2028','500000000','floating_2028'),('$1,500,000,000 aggregate principal amount of its 4.800% Notes due 2028','1500000000','fixed_2028'),('$1,250,000,000 aggregate principal amount of its 5.250% Notes due 2032','1250000000','fixed_2032'),('$1,750,000,000 aggregate principal amount of its 5.500% Notes due 2035','1750000000','fixed_2035'),('$1,750,000,000 aggregate principal amount of its 6.000% Notes due 2055','1750000000','fixed_2055'),('$1,000,000,000 aggregate principal amount of its 6.125% Notes due 2065','1000000000','fixed_2065')]:
 rows.append(money(quote,number,'1','unidentified_noteholders',counterparty_evidence='anonymous',event_date='2025-02-03',stage='recognized',amount_qualifier='exact',model_quantity='notes_'+quantity+'_issued_face',amount_nature='component_of_aggregate_face_not_net_cash'))
rows.extend([dict(quote='Oracle (formerly known as Ozark Holding Inc.), Oracle Systems Corporation (formerly known as Oracle Corporation)',model_quantity='current_and_legacy_Oracle_legal_names_distinct',flag_unknown_reason='two_distinct_legal_persons_not_alias_merge_exact_rename_dates_unknown'),dict(quote='Oracle intends to use a portion of the net proceeds of the offering to repay all or a portion',model_quantity='notes_planned_debt_repayments_and_general_use',flag_unknown_reason='intended_payments_not_actual_repayment_or_amount_of_net_cash'),abstention('The material terms and conditions of the Notes are set forth in the Officers’ Certificate','Full item: actual issuance/sale, six series, underwriting/indenture/trustee identities, registrations, planned principal/interest/general uses and renvois read. No quantified net cash, actual debt repayment, security status from this item or financial-covenant waiver/default. Representatives/trustee not each payer; original officers certificate not F4.')])
save(k,rows)
k='4e877b7bb91e11681058f3ba6d6c3cef8e12de8b61fc0848418d3df83306bd92'
save(k,[abstention('the Supreme Court of the State of Delaware, sitting en banc, affirmed the lower court’s judgment in favor of defendants','Full item/signature read. Derivative litigation judgment Jan21 is not a financial derivative or quantified investment impairment/cash flow; rejected claims not financial-covenant waiver or customer funding.')])
k='38c54a1f23b1b1f15de4451a320a181d79c9c342a9521c61027bad54d02b357c'
save(k,[dict(quote='The rule published in the Federal Register on January 15, 2025 at 90 Fed. Reg. 4544.',event_date='2025-01-15',model_quantity='AI_diffusion_rule_published',flag_unknown_reason='future_compliance_May15_subject_modification_not_actual_financial_loss'),dict(quote='On January 16, 2025, the Bureau of Industry and Security, Department of Commerce, published a rule entitled “Implementation of Additional Due Diligence Measures for Advanced Computing Integrated Circuits.”',event_date='2025-01-16',model_quantity='advanced_IC_due_diligence_rule_published'),abstention('NVIDIA Corporation is an approved IC designer and thus the rule is not expected to have an impact on our operations or on product sales to China.','Full item: both rules, product/ECCN scope, 120-day comment/delayed compliance and conditional May15 future requirements, policy positions, approved-designer expectation, all forward-looking risks and signature read. No actual cash loss, investment impairment, financial-covenant waiver/default, guarantee call or capacity termination. Expected no impact is not an actual quantified zero effect.')])
