from work.authored_helpers import *
k='17622b060a19dae14dc599645c03c67efe48678bb7a171fd15ada93369882a90'
save(k,[authored_control(k,'our disclosure controls and procedures are designed at a reasonable assurance level and are effective to provide reasonable assurance','disclosure_controls_effective',event_present=True),authored_control(k,'There have been no changes in our internal control over financial reporting that occurred during the quarter ended September 30, 2021','no_material_ICFR_change_quarter',flag_unknown_reason='COVID_work_from_home_not_MW'),dict(quote='The implementation is expected to continue in phases over the next few years.',model_quantity='ERP_implementation_in_progress',flag_unknown_reason='no_completed_subledger_clause_here')])
k='9298b59432bb09b775bd45e4ffaafcd003dd319b22c2c3e6925171f131d36975'
rows=[dict(quote='The condensed consolidated financial statements include the accounts of Facebook, Inc., its subsidiaries where we have controlling financial interests, and any variable interest entities for which we are deemed to be the primary beneficiary.',model_quantity='consolidation_scope',flag_unknown_reason='Facebook_legal_name_here_no_later_Meta_rename_import'),dict(quote='All intercompany balances and transactions have been eliminated.',model_quantity='intercompany_elimination'),dict(quote='we extended the estimated average useful lives of selected cohorts of servers and other network equipment included in our network equipment category from three years to four years in prior years as well as in 2021',model_quantity='server_network_selected_cohort_life_extension_not_F7',basis_break=True,recast_cause='accounting_change',flag_unknown_reason='selected_cohorts_no_exact_effective_dates'),dict(quote='The impact from the changes in our estimates was calculated based on the asset bases existing as of the effective dates of the changes and applying the revised estimated useful lives prospectively.',model_quantity='life_change_existing_cohorts_prospective'),dict(quote='On January 1, 2021, we adopted Accounting Standards Update (ASU) No. 2020-01,',model_quantity='ASU2020_01_adopted',event_date='2021-01-01',recast_cause='accounting_change',flag_unknown_reason='no_material_impact_not_zero'),abstention('Accounting Pronouncements Not Yet Adopted','ASU2020-06 and ASU2021-05 pending as reported here despite later adoption disclosure; no later clause imported. Complete note no substantial doubt, actual investment impairment or life shortening.')]
q='The effect of the 2021 changes was a reduction in depreciation expense of $390 million and an increase in net income of $316 million, or $0.11 per diluted share for the nine months ended September 30, 2021.'
rows += [authored_tagged(k,'eba0d2ad5d6b585e145fe2c800d47c8b118316d8672566f15188c5a56e620dae',q,model_quantity='life_change_depreciation_expense_effect',amount_nature='negative_expense_change_positive_pretax_effect_invert_sign'),authored_tagged(k,'919eb0225f369d4c48c8429c8629dfdd4d0b50a862943f855a2ea62fa382d6ec',q,model_quantity='life_change_net_income_effect',amount_nature='after_tax_not_pretax')]
save(k,rows)
k='42b0e1d464c776181383bce7b5ef1b1a011a8cf1e84761b51db480233c529304'
save(k,[authored_control(k,'our disclosure controls and procedures are designed at a reasonable assurance level and are effective to provide reasonable assurance','disclosure_controls_effective',event_present=True),authored_control(k,'There were no changes in our internal control over financial reporting identified in management\'s evaluation','no_material_ICFR_change_quarter',flag_unknown_reason='generic_limits_not_MW')])
