from pathlib import Path
from decimal import Decimal
from secfragility.reader import store
KEY='732781c17eae04df06d9bdbfb34cb4ef0174f34d98750c9c38b10c278ab3e01e'
USD='http://www.xbrl.org/2003/iso4217:USD'
def usd(quote,number,scale,**fields):
 return dict(quote=quote,amount=str(Decimal(number)*{'million':1000000,'billion':1000000000}[scale]),unit=USD,currency='USD',amount_origin='narrative_only',amount_qualifier='exact') | fields
rows=[
 dict(abstained=True,abstention_reason='employee_equity_exchange_rights_not_cash_primary_equity_funding',quote='The Equity Exchange Rights only apply to equity awards granted to our Co-Founders prior to September 2024.'),
 dict(abstained=True,abstention_reason='employee_compensation_outside_counterparty_financing_and_commercial_exposure',quote='Michael McBee, the brother of Brannin McBee, our Chief Development Officer, has been employed by us in a non-executive role since November 2024.'),
 usd('We received a refundable deposit of approximately $230 million in connection with the MagAI Capacity Agreement.','230','million',counterparty='MagAI Ventures',counterparty_evidence='named',payer='MagAI Ventures',receiver='CoreWeave',amount_nature='refundable_capacity_deposit_received_not_revenue',model_quantity='refundable_capacity_deposit_received',family='commercial',link_type='prepayment',stage='drawn_or_paid',event_type='payment',instrument_key='MagAI_Capacity_Agreement',amount_qualifier='approximately',vehicle_level=True,flag_unknown_reason='individual_fund_legal_name_and_cash_receipt_date_not_disclosed'),
 dict(quote='If the arrangement is terminated out of convenience, we are required to pay MagAI Ventures a breakup fee equal to the unused portion of the deposit multiplied by a factor that increases from 1.06x to 1.73x over the term of the arrangement.',counterparty='MagAI Ventures',counterparty_evidence='named',payer='CoreWeave',receiver='MagAI Ventures',family='commercial',link_type='capacity_lease',stage='signed',block='contingent_obligations',category_id='take_or_pay',component_kind='termination_payment',conditionality='conditional',trigger_description='If the arrangement is terminated out of convenience',trigger_occurred='unknown',model_quantity='capacity_termination_payment_terms',instrument_key='MagAI_Capacity_Agreement',flag_unknown_reason='conditional_fee_not_current_called_amount'),
 dict(quote='As of December 31, 2025 and March 31, 2026, the $230 million refundable deposit remains available for cloud computing services for MagAI Ventures’ portfolio companies, as no services had yet been provided under this arrangement.',counterparty='MagAI Ventures',counterparty_evidence='named',instrument_key='MagAI_Capacity_Agreement',model_quantity='refundable_capacity_deposit_no_services_delivered',stage='available',flag_unknown_reason='refundable_deposit_not_recognized_revenue'),
 usd('As of December 31, 2025, we had $273 million classified as debt, current, including $43 million of redemption premiums, on the consolidated balance sheets, related to this arrangement.','273','million',counterparty='MagAI Ventures',counterparty_evidence='named',payer='CoreWeave',receiver='MagAI Ventures',period_end='2025-12-31',amount_nature='current_debt_carrying_value_including_redemption_premium',model_quantity='refundable_capacity_deposit_debt_carrying_value',block='recognized_liabilities',category_id='debt',measurement_basis='carrying_value',stage='recognized',instrument_key='MagAI_Capacity_Agreement',issuer_treatment='debt_current',issuer_treatment_quote='As of December 31, 2025, we had $273 million classified as debt, current, including $43 million of redemption premiums, on the consolidated balance sheets, related to this arrangement.'),
 usd('As of December 31, 2025, we had $273 million classified as debt, current, including $43 million of redemption premiums, on the consolidated balance sheets, related to this arrangement.','43','million',counterparty='MagAI Ventures',counterparty_evidence='named',period_end='2025-12-31',amount_nature='redemption_premium_component_of_current_debt_not_separate_principal',model_quantity='refundable_capacity_redemption_premium',block='recognized_liabilities',category_id='debt',measurement_basis='carrying_value_component',component_kind='interest',stage='recognized',instrument_key='MagAI_Capacity_Agreement'),
 usd('On June 14, 2024, we contributed an aggregate amount of $50 million to a fund managed by Magnetar (“MAIV”) in connection with MAIV’s purchase of shares of preferred stock in a private company.','50','million',counterparty='MAIV',counterparty_evidence='named',payer='CoreWeave',receiver='MAIV',event_date='2024-06-14',event_type='funding',amount_nature='fund_capital_contribution_not_direct_investment_in_named_private_company',model_quantity='fund_capital_contribution',family='financing',link_type='equity_primary',stage='drawn_or_paid',vehicle_level=True,flag_unknown_reason='fund_legal_identity_and_underlying_private_company_pending'),
 usd('On May 16, 2024, CoreWeave Compute Acquisition Co. IV, LLC, our direct, wholly-owned subsidiary, as borrower, entered into a credit agreement with U.S. Bank National Association, as depository bank, U.S. Bank Trust Company, National Association, as administrative agent and collateral agent, Blackstone Alternative Credit Advisors LP, Blackstone Alternative Solutions L.L.C., Blackstone Tactical Opportunities Advisors L.L.C., and Blackstone Private Investments Advisors L.L.C., as lead lenders and co-lead investors, Magnetar, as a co-lead investor, and the lenders party thereto, providing for a $7.6 billion delayed draw term loan facility (as amended, the “DDTL 2.0 Facility”).','7.6','billion',counterparty_evidence='anonymous',payer='lenders party to the DDTL 2.0 Facility',receiver='CoreWeave Compute Acquisition Co. IV, LLC',amount_nature='facility_limit_as_amended_not_drawn_principal_or_Magnetar_allocation',model_quantity='facility_limit',family='financing',link_type='loan_or_facility',stage='signed',instrument_key='CRWV_DDTL_2_0',amount_qualifier='up_to',flag_unknown_reason='allocation_to_individual_lenders_not_disclosed'),
 usd('As of December 31, 2025, $5.0 billion of our DDTL 2.0 Facility was drawn with no amounts remaining available for borrowing.','5.0','billion',counterparty_evidence='anonymous',payer='lenders party to the DDTL 2.0 Facility',receiver='CoreWeave Compute Acquisition Co. IV, LLC',period_end='2025-12-31',amount_nature='drawn_facility_amount_not_carrying_value_or_single_lender_share',model_quantity='facility_drawn_amount',family='financing',link_type='loan_or_facility',stage='drawn_or_paid',instrument_key='CRWV_DDTL_2_0',flag_unknown_reason='individual_lender_allocation_not_disclosed'),
 usd('As of December 31, 2025, we have paid $457 million in interest on outstanding amounts under our DDTL 2.0 Facility and have made no principal payments.','457','million',counterparty_evidence='anonymous',payer='CoreWeave Compute Acquisition Co. IV, LLC',receiver='lenders party to the DDTL 2.0 Facility',period_end='2025-12-31',amount_nature='cumulative_interest_cash_payments_not_annual_expense',model_quantity='facility_interest_cash_paid_cumulative',family='financing',link_type='loan_or_facility',stage='drawn_or_paid',event_type='payment',component_kind='interest',instrument_key='CRWV_DDTL_2_0',flag_unknown_reason='cumulative_start_and_lender_allocation_not_disclosed'),
 usd('In September 2025, we further amended the DDTL 2.0 Facility (as so amended, the “DDTL 2.1 Facility”) to create a new tranche of delayed draw term loan facility up to $3.0 billion that may be drawn through March 2026.','3.0','billion',counterparty_evidence='anonymous',payer='lenders party to the DDTL 2.1 Facility',receiver='CoreWeave Compute Acquisition Co. IV, LLC',amount_nature='new_tranche_facility_limit_not_drawn_principal',model_quantity='facility_limit',family='financing',link_type='loan_or_facility',stage='signed',event_type='amendment',instrument_key='CRWV_DDTL_2_1',amount_qualifier='up_to',flag_unknown_reason='exact_amendment_date_and_lender_allocation_not_disclosed'),
 usd('As of December 31, 2025, $2.7 billion of our DDTL 2.1 Facility was drawn and $0.3 billion remained available for borrowing.','2.7','billion',counterparty_evidence='anonymous',period_end='2025-12-31',amount_nature='drawn_tranche_amount',model_quantity='facility_drawn_amount',family='financing',link_type='loan_or_facility',stage='drawn_or_paid',instrument_key='CRWV_DDTL_2_1',flag_unknown_reason='lender_allocation_not_disclosed'),
 usd('As of December 31, 2025, $2.7 billion of our DDTL 2.1 Facility was drawn and $0.3 billion remained available for borrowing.','0.3','billion',counterparty_evidence='anonymous',period_end='2025-12-31',amount_nature='undrawn_facility_availability_not_debt_or_cash',model_quantity='facility_available_amount',family='financing',link_type='loan_or_facility',stage='available',instrument_key='CRWV_DDTL_2_1',flag_unknown_reason='lender_allocation_not_disclosed'),
 usd('On July 30, 2023, CoreWeave Compute Acquisition Co. II, LLC, our direct, wholly-owned subsidiary, as borrower, entered into a credit agreement with U.S. Bank National Association, as depository bank, U.S. Bank Trust Company, National Association, as administrative agent and collateral agent, Blackstone Tactical Opportunities Advisors L.L.C., and Magnetar, on behalf of certain lenders as the lead lenders, and the arrangers, bookrunners, and lenders party thereto, providing for a $2.3 billion delayed draw term loan facility (as amended, the “DDTL 1.0 Facility”).','2.3','billion',counterparty_evidence='anonymous',payer='lenders party to the DDTL 1.0 Facility',receiver='CoreWeave Compute Acquisition Co. II, LLC',amount_nature='facility_limit_as_amended_not_Magnetar_allocation',model_quantity='facility_limit',family='financing',link_type='loan_or_facility',stage='signed',instrument_key='CRWV_DDTL_1_0',amount_qualifier='up_to',flag_unknown_reason='lender_allocation_not_disclosed'),
 usd('As of December 31, 2025, our DDTL 1.0 Facility was fully drawn, and we had $1.6 billion outstanding under our DDTL 1.0 Facility.','1.6','billion',counterparty_evidence='anonymous',period_end='2025-12-31',amount_nature='outstanding_facility_amount_not_original_limit',model_quantity='facility_outstanding_amount',family='financing',link_type='loan_or_facility',stage='drawn_or_paid',instrument_key='CRWV_DDTL_1_0',flag_unknown_reason='principal_vs_carrying_basis_and_lender_allocation_not_explicit'),
 usd('As of December 31, 2025, we have paid $748 million in principal and $523 million in interest on outstanding amounts under our DDTL 1.0 Facility.','748','million',counterparty_evidence='anonymous',payer='CoreWeave Compute Acquisition Co. II, LLC',receiver='lenders party to the DDTL 1.0 Facility',period_end='2025-12-31',amount_nature='cumulative_principal_cash_repayment',model_quantity='facility_principal_cash_paid_cumulative',family='financing',link_type='loan_or_facility',stage='drawn_or_paid',event_type='repayment',component_kind='principal',instrument_key='CRWV_DDTL_1_0',flag_unknown_reason='cumulative_start_and_lender_allocation_not_disclosed'),
 usd('As of December 31, 2025, we have paid $748 million in principal and $523 million in interest on outstanding amounts under our DDTL 1.0 Facility.','523','million',counterparty_evidence='anonymous',payer='CoreWeave Compute Acquisition Co. II, LLC',receiver='lenders party to the DDTL 1.0 Facility',period_end='2025-12-31',amount_nature='cumulative_interest_cash_payments_not_annual_expense',model_quantity='facility_interest_cash_paid_cumulative',family='financing',link_type='loan_or_facility',stage='drawn_or_paid',event_type='payment',component_kind='interest',instrument_key='CRWV_DDTL_1_0',flag_unknown_reason='cumulative_start_and_lender_allocation_not_disclosed'),
 usd('In October 2021, we entered into a Note Issuance Agreement with Magnetar (the “Note Issuance Agreement”), pursuant to which we issued to funds or accounts managed or advised by Magnetar (the “2025 Convertible Note Purchasers”) $50 million aggregate principal amount of Convertible Senior Secured Notes due 2025 (the “2025 Convertible Notes”).','50','million',counterparty_evidence='anonymous',payer='2025 Convertible Note Purchasers',receiver='CoreWeave',amount_nature='original_convertible_note_face_amount_not_current_principal_or_net_cash',model_quantity='convertible_note_original_face_amount',family='financing',link_type='convertible_or_safe',stage='signed',instrument_key='CRWV_2021_2025_Convertible_Notes',flag_unknown_reason='individual_funds_not_named_and_net_cash_not_disclosed'),
 usd('In 2023, the aggregate principal amount of the 2025 Convertible Notes was increased to $55 million as a result of the payment of certain interest payments in kind.','55','million',counterparty_evidence='anonymous',amount_nature='2023_aggregate_principal_including_PIK_not_current_or_new_cash',model_quantity='convertible_note_historical_principal_with_PIK',family='financing',link_type='convertible_or_safe',stage='recognized',instrument_key='CRWV_2021_2025_Convertible_Notes',flag_unknown_reason='exact_historical_date_and_funds_not_disclosed'),
 dict(quote='Effective as of September 17, 2024, the 2025 Convertible Note Purchasers caused the 2025 Convertible Notes to be converted into shares of our Class A common stock pursuant to the terms and conditions of the Note Issuance Agreement.',counterparty_evidence='anonymous',payer='2025 Convertible Note Purchasers',receiver='CoreWeave',stage='settled',event_date='2024-09-17',event_type='conversion',family='financing',link_type='convertible_or_safe',instrument_key='CRWV_2021_2025_Convertible_Notes',model_quantity='convertible_note_conversion_not_cash_funding',flag_unknown_reason='individual_fund_legal_identities_not_named'),
 usd('In connection with the issuance of the 2025 Convertible Notes, we granted to Magnetar (a) an option to purchase $15.0 million of our Class A common stock at the initial public offering price of $40.00 per share, which option was exercised by Magnetar on March 19, 2026 and (b) the right (using our commercially reasonable efforts) to subscribe for and purchase at least 5% of our capital stock issued in any future public equity offering by us, including for shares of our Class A common stock.','15.0','million',counterparty='Magnetar',counterparty_evidence='named',payer='Magnetar',receiver='CoreWeave',amount_nature='equity_subscription_option_limit_not_explicit_cash_proceeds',model_quantity='equity_subscription_option_limit',family='financing',link_type='equity_primary',stage='signed',instrument_key='CRWV_2021_Magnetar_IPO_option',amount_qualifier='up_to',event_date='2026-03-19',event_type='purchase',flag_unknown_reason='exercise_disclosed_cash_receipt_not_disclosed_actual_fund_pending'),
 usd('In October 2022, we entered into a Note Issuance Agreement with Magnetar, pursuant to which we issued to funds or accounts managed or advised by Magnetar (the “2025 Note Purchasers”) $125 million aggregate principal amount of Senior Secured Notes due 2025 (the “2025 Notes”).','125','million',counterparty_evidence='anonymous',payer='2025 Note Purchasers',receiver='CoreWeave',amount_nature='original_note_face_amount_not_current_principal_or_net_cash',model_quantity='senior_note_original_face_amount',family='financing',link_type='loan_or_facility',stage='signed',instrument_key='CRWV_2022_2025_Senior_Notes',flag_unknown_reason='individual_funds_not_named_and_net_cash_not_disclosed'),
 dict(quote='This option expired unexercised in connection with the IPO.',counterparty_evidence='anonymous',stage='terminated',event_type='expiry',instrument_key='CRWV_2022_Magnetar_IPO_option',model_quantity='unexercised_subscription_option_expiry_not_equity_funding'),
 dict(quote='The Director Nomination Letter was terminated as of November 6, 2025.',counterparty_evidence='anonymous',event_date='2025-11-06',event_type='termination',stage='terminated',model_quantity='director_nomination_right_termination_not_financing_exit',flag_unknown_reason='governance_right_termination_does_not_establish_equity_disposal'),
 dict(quote='NVIDIA beneficially owns more than 5% of our outstanding capital stock.',counterparty='NVIDIA Corporation',counterparty_evidence='named',source_perspective='counterparty',model_quantity='disclosed_beneficial_equity_holding',family='financing',link_type='equity_primary',stage='recognized',flag_unknown_reason='beneficial_holding_not_new_cash_funding_and_exact_measurement_date_not_disclosed'),
 usd('For the year ended December 31, 2025 and the three months ended March 31, 2026, NVIDIA has paid us an aggregate of approximately $326.3 million and $59.6 million, respectively, pursuant to the Master Services Agreement and related order forms.','326.3','million',counterparty='NVIDIA Corporation',counterparty_evidence='named',payer='NVIDIA Corporation',receiver='CoreWeave',period_start='2025-01-01',period_end='2025-12-31',amount_nature='customer_cash_payments_not_explicit_GAAP_revenue',model_quantity='customer_cash_payments',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',instrument_key='CRWV_NVIDIA_MSA_2023',amount_qualifier='approximately'),
 usd('For the year ended December 31, 2025 and the three months ended March 31, 2026, NVIDIA has paid us an aggregate of approximately $326.3 million and $59.6 million, respectively, pursuant to the Master Services Agreement and related order forms.','59.6','million',counterparty='NVIDIA Corporation',counterparty_evidence='named',payer='NVIDIA Corporation',receiver='CoreWeave',period_start='2026-01-01',period_end='2026-03-31',amount_nature='customer_cash_payments_not_explicit_GAAP_revenue',model_quantity='customer_cash_payments',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',instrument_key='CRWV_NVIDIA_MSA_2023',amount_qualifier='approximately'),
 dict(quote='For the year ended December 31, 2025, NVIDIA accounted for 17% of our total purchases from suppliers.',counterparty='NVIDIA Corporation',counterparty_evidence='named',amount='17',unit='percent',amount_origin='narrative_only',amount_qualifier='exact',period_start='2025-01-01',period_end='2025-12-31',amount_nature='supplier_purchase_concentration_percent_not_revenue_share',model_quantity='supplier_purchase_concentration_percent',family='commercial',link_type='purchase',flag_unknown_reason='percentage_unit_is_percent_points_not_ratio'),
 usd('On January 23, 2026, we entered into a Securities Purchase Agreement (the “Purchase Agreement”) with NVIDIA and completed the issuance and sale of 22,935,780 shares of our Class A common stock to NVIDIA pursuant to the Purchase Agreement, at a price of $87.20 per share for an aggregate purchase price of $2 billion in cash.','2','billion',counterparty='NVIDIA Corporation',counterparty_evidence='named',payer='NVIDIA Corporation',receiver='CoreWeave',event_date='2026-01-23',event_type='funding',amount_nature='primary_common_equity_cash_funding',model_quantity='primary_equity_cash_funding',family='financing',link_type='equity_primary',stage='drawn_or_paid',instrument_key='CRWV_NVIDIA_2026_primary_equity'),
 usd('For the year ended December 31, 2025 and the three months ended March 31, 2026, Jane Street has paid us an aggregate of approximately $100.0 million and $220.6 million, respectively, pursuant to the Jane Street MSA and related order forms.','100.0','million',counterparty='Jane Street Group, LLC',counterparty_evidence='named',payer='Jane Street Group, LLC and affiliates',receiver='CoreWeave',period_start='2025-01-01',period_end='2025-12-31',amount_nature='customer_cash_payments_not_explicit_GAAP_revenue',model_quantity='customer_cash_payments',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',instrument_key='CRWV_Jane_Street_MSA_2024',amount_qualifier='approximately',flag_unknown_reason='individual_payer_affiliates_not_disclosed'),
 usd('For the year ended December 31, 2025 and the three months ended March 31, 2026, Jane Street has paid us an aggregate of approximately $100.0 million and $220.6 million, respectively, pursuant to the Jane Street MSA and related order forms.','220.6','million',counterparty='Jane Street Group, LLC',counterparty_evidence='named',payer='Jane Street Group, LLC and affiliates',receiver='CoreWeave',period_start='2026-01-01',period_end='2026-03-31',amount_nature='customer_cash_payments_not_explicit_GAAP_revenue',model_quantity='customer_cash_payments',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',instrument_key='CRWV_Jane_Street_MSA_2024',amount_qualifier='approximately',flag_unknown_reason='individual_payer_affiliates_not_disclosed'),
 usd('On April 15, 2026, we entered into a Securities Purchase Agreement (the “Jane Street Purchase Agreement”) with Jane Street Global Trading LLC (“Jane Street GT”) and completed the issuance and sale of 9,174,311 shares of our Class A common stock to Jane Street GT pursuant to the Jane Street Purchase Agreement, at a price of $109.00 per share for an aggregate purchase price of approximately $1.0 billion in cash.','1.0','billion',counterparty='Jane Street Global Trading LLC',counterparty_evidence='named',payer='Jane Street Global Trading LLC',receiver='CoreWeave',event_date='2026-04-15',event_type='funding',amount_nature='primary_common_equity_cash_funding',model_quantity='primary_equity_cash_funding',family='financing',link_type='equity_primary',stage='drawn_or_paid',instrument_key='CRWV_Jane_Street_2026_primary_equity',amount_qualifier='approximately',vehicle_level=True),
 dict(quote='Our Voting Agreement terminated upon the completion of our initial public offering.',abstained=True,abstention_reason='governance_and_registration_rights_not_equity_disposal_or_cash_financing_event')]
print(store(Path('.').resolve(),KEY,rows))
