from pathlib import Path
from decimal import Decimal
from secfragility.reader import store
r=Path('.').resolve();k='fcdeb524113721d268252ad3878cfdc5a7d75f1816691ec4b1ab8b9dd0c1b645';u='http://www.xbrl.org/2003/iso4217:USD'
def m(q,n,s,**f):return dict(quote=q,amount=str(Decimal(n)*{'unit':1,'million':1000000,'billion':1000000000}[s]),unit=u,currency='USD',amount_origin='narrative_only',amount_qualifier='exact')|f
anon=dict(counterparty_evidence='anonymous')
secondary=dict(**anon,source_perspective='counterparty',payer='existing and new stockholders',receiver='selling stockholders',amount_nature='secondary_tender_purchase_price_not_CoreWeave_cash_funding',model_quantity='secondary_tender_purchase_price',stage='settled',event_type='secondary_purchase')
primary=dict(**anon,payer='investors',receiver='CoreWeave',amount_nature='primary_preferred_equity_purchase_price_not_net_cash_proceeds',model_quantity='primary_preferred_equity_purchase_price',family='financing',link_type='equity_primary',stage='drawn_or_paid',event_type='funding')
facility=dict(counterparty_evidence='anonymous',family='financing',link_type='loan_or_facility')
rows=[m('An aggregate of 13,851,240 shares of our Class A common stock,\nClass B common stock, and convertible preferred stock were tendered for an aggregate purchase price of $651 million.','651','million',**secondary,instrument_key='CRWV_2024_secondary_tender'),
m('The aggregate amount received by us in respect of these net exercises for shares sold in the 2024 Tender Offer was $1 million.','1','million',counterparty_evidence='anonymous',payer='employee option holders',receiver='CoreWeave',amount_nature='net_employee_option_exercise_cash_received_not_secondary_tender_proceeds',model_quantity='employee_option_exercise_cash_received',stage='drawn_or_paid',event_type='funding',instrument_key='CRWV_2024_secondary_tender_employee_option_exercises'),
m('Entities affiliated with Fidelity(1) | | | 1,416,340 | | | $ | 66,557,577 |','66557577','unit',**(secondary|dict(payer='entities affiliated with Fidelity')),instrument_key='CRWV_2024_secondary_tender_Fidelity'),
m('Funds or accounts managed or advised by Magnetar(2) | | | 1,934,980 | | | $ | 90,929,848 |','90929848','unit',**(secondary|dict(payer='funds or accounts managed or advised by Magnetar')),instrument_key='CRWV_2024_secondary_tender_Magnetar'),
m('Funds affiliated with Glenn Hutchins(3) | | | 212,780 | | | $ | 9,999,097 |','9999097','unit',**(secondary|dict(payer='funds affiliated with Glenn Hutchins')),instrument_key='CRWV_2024_secondary_tender_Hutchins'),
m('An aggregate of 41,476,000 shares of our Class A common stock and convertible preferred stock were tendered for an aggregate\npurchase price of $643 million.','643','million',**secondary,instrument_key='CRWV_2023_secondary_tender'),
m('The aggregate amount received by us in respect of these net exercises for shares sold in the 2023 Tender Offer was $354,436.','354436','unit',counterparty_evidence='anonymous',payer='employee option holders',receiver='CoreWeave',amount_nature='net_employee_option_exercise_cash_received_not_secondary_tender_proceeds',model_quantity='employee_option_exercise_cash_received',stage='drawn_or_paid',event_type='funding',instrument_key='CRWV_2023_secondary_tender_employee_option_exercises'),
m('Entities affiliated with Fidelity(1) | | | 20,009,040 | | | $ | 310,000,057 |','310000057','unit',**(secondary|dict(payer='entities affiliated with Fidelity')),instrument_key='CRWV_2023_secondary_tender_Fidelity'),
dict(abstained=True,abstention_reason='individual_director_officer_secondary_sales_are_gross_seller_proceeds_not_issuer_financing',quote='The amounts set forth in the column titled “Total Purchase Price” represent the gross sales proceeds realized by the seller, before any reduction for transaction costs, tax withholding,\nor amounts remitted to us in respect of the net exercise of employee stock options:'),
dict(quote='Fidelity exercised its option to participate in this offering, and this right terminated immediately prior to the consummation of this offering.',counterparty='Fidelity',counterparty_evidence='named',family='financing',link_type='equity_primary',stage='signed',event_type='purchase',model_quantity='Fidelity_IPO_subscription_option_exercise_unquantified',flag_unknown_reason='actual_affiliated_entities_cash_proceeds_and_exact_exercise_date_not_disclosed'),
m('In May 2024, we sold an aggregate of 29,523,120 shares of our Series C convertible preferred stock at a\npurchase price of $38.96 per share for an aggregate purchase price of approximately $1.2 billion.','1.2','billion',**primary,amount_qualifier='approximately',instrument_key='CRWV_Series_C_2024',flag_unknown_reason='total_all_investors_net_cash_and_individual_payment_dates_not_disclosed'),
m('Funds or accounts managed or advised by Magnetar(1) | | | 8,985,300 | | | $ | 349,999,898 |','349999898','unit',**(primary|dict(payer='funds or accounts managed or advised by Magnetar')),instrument_key='CRWV_Series_C_2024_Magnetar'),
m('Entities affiliated with Fidelity(2) | | | 1,283,620 | | | $ | 50,000,208 |','50000208','unit',**(primary|dict(payer='entities affiliated with Fidelity')),instrument_key='CRWV_Series_C_2024_Fidelity'),
m('Upon exercise of the Put Right (as defined herein), holders\nof the Put Shares (as defined herein) would be entitled to receive from us an amount in cash equal to the original issue price per share of the Series C convertible preferred stock, of $38.95, representing an aggregate payment of\n$1.2 billion.','1.2','billion',counterparty_evidence='anonymous',payer='CoreWeave',receiver='Series C Put Share holders',amount_nature='contingent_Series_C_equity_put_payment_not_current_debt_or_called_amount',model_quantity='Series_C_contingent_equity_put_payment',stage='signed',conditionality='conditional',trigger_description='Upon exercise of the Put Right',trigger_occurred='unknown',instrument_key='CRWV_Series_C_Put_Right',flag_unknown_reason='first_trading_day_after_earlier_of_2029_08_15_or_second_IPO_anniversary_holder_identity_pending_nonadditive_to_existing_equity'),
m('Between April 2023 and January 2024, we sold an aggregate of 79,978,760 shares of our Series B\nconvertible preferred stock at a purchase price of $5.58 per share for an aggregate purchase price of approximately $446 million.','446','million',**primary,amount_qualifier='approximately',instrument_key='CRWV_Series_B_2023_2024',flag_unknown_reason='no_annual_split_across_2023_2024_or_net_cash_disclosed'),
m('Funds or accounts managed or advised by Magnetar(1) | | | 60,253,060 | | | $ | 336,000,014 |','336000014','unit',**(primary|dict(payer='funds or accounts managed or advised by Magnetar')),instrument_key='CRWV_Series_B_2023_2024_Magnetar'),
m('In April 2023, we issued an aggregate of 12,484,540 shares of our\nSeries B-1 convertible preferred stock at a purchase price of $0.41 per share upon conversion of convertible notes previously issued to several accredited private investors for an aggregate principal\namount of $4 million and which bore a PIK interest rate of 7% per annum.','4','million',counterparty_evidence='anonymous',amount_nature='historical_notes_principal_converted_to_preferred_not_new_cash',model_quantity='convertible_note_principal_on_non_cash_conversion',family='financing',link_type='convertible_or_safe',stage='settled',event_type='conversion',instrument_key='CRWV_Series_B_1_2023_conversion',flag_unknown_reason='original_note_issuance_dates_and_private_investors_not_named'),
dict(abstained=True,abstention_reason='Series_B_1_conversion_purchase_price_allocations_are_noncash_conversion_not_new_primary_cash_funding',quote='Each outstanding share of our Series B-1 convertible preferred stock will convert automatically into shares of our\nClass A common stock immediately prior to the completion of this offering.'),
m('As of December 31, 2024, NVIDIA has paid us an aggregate of approximately $320 million pursuant to the Master Services Agreement and related order forms.','320','million',counterparty='NVIDIA',counterparty_evidence='named',payer='NVIDIA',receiver='CoreWeave',period_end='2024-12-31',amount_qualifier='approximately',amount_nature='cumulative_customer_cash_payments_not_annual_GAAP_revenue',model_quantity='customer_cash_payments_cumulative',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',instrument_key='CRWV_NVIDIA_MSA_2023',flag_unknown_reason='cumulative_start_not_explicit_no_allocation_to_fiscal_2024'),
m('We received a refundable deposit of approximately\n$230 million in connection with the MagAI Capacity Agreement.','230','million',counterparty='MagAI Ventures',counterparty_evidence='named',payer='MagAI Ventures',receiver='CoreWeave',amount_qualifier='approximately',amount_nature='refundable_capacity_deposit_received_not_revenue',model_quantity='refundable_capacity_deposit_received',family='commercial',link_type='prepayment',stage='drawn_or_paid',event_type='payment',instrument_key='MagAI_Capacity_Agreement',flag_unknown_reason='cash_receipt_date_and_actual_fund_legal_identity_not_disclosed'),
m('As of December 31, 2024, approximately $230 million of this refundable deposit is included within other current\nliabilities in the consolidated balance sheet, as no services had yet been provided under this arrangement.','230','million',counterparty='MagAI Ventures',counterparty_evidence='named',period_end='2024-12-31',amount_qualifier='approximately',amount_nature='refundable_capacity_deposit_other_current_liability_balance_not_revenue',model_quantity='refundable_capacity_deposit_balance',stage='recognized',measurement_basis='carrying_value',issuer_treatment='other_current_liabilities',instrument_key='MagAI_Capacity_Agreement'),
dict(quote='If the arrangement is terminated out of convenience, we are required to pay MagAI Ventures a breakup fee equal to the\nunused portion of the deposit multiplied by a factor that increases from 1.06x to 1.73x over the term of the arrangement.',counterparty='MagAI Ventures',counterparty_evidence='named',payer='CoreWeave',receiver='MagAI Ventures',stage='signed',conditionality='conditional',trigger_description='If the arrangement is terminated out of convenience',trigger_occurred='unknown',model_quantity='capacity_termination_payment_terms',instrument_key='MagAI_Capacity_Agreement',flag_unknown_reason='not_current_called_amount'),
m('On June 14, 2024, we contributed an aggregate amount of $50 million to a fund managed by\nMagnetar (“MAIV”) in connection with MAIV’s purchase of shares of preferred stock in a private company.','50','million',counterparty='MAIV',counterparty_evidence='named',payer='CoreWeave',receiver='MAIV',event_date='2024-06-14',event_type='funding',amount_nature='fund_capital_contribution_not_direct_investment_in_named_private_company',model_quantity='fund_capital_contribution',family='financing',link_type='equity_primary',stage='drawn_or_paid',vehicle_level=True,flag_unknown_reason='fund_and_underlying_private_company_legal_identities_pending_consolidation_cross_reference_not_established'),
m('lenders party thereto, providing for a $7.6 billion delayed draw term loan facility (as amended, the “DDTL 2.0 Facility”).','7.6','billion',**facility,payer='DDTL 2.0 lenders',receiver='CCAC IV',amount_qualifier='up_to',amount_nature='facility_limit_as_amended_not_drawn_amount',model_quantity='facility_limit',stage='signed',instrument_key='CRWV_DDTL_2_0'),
m('As of December 31, 2024, $3.8 billion of our DDTL 2.0 Facility was drawn and $3.8 billion remained available for borrowing under our DDTL 2.0\nFacility.','3.8','billion',**facility,payer='DDTL 2.0 lenders',receiver='CCAC IV',period_end='2024-12-31',amount_nature='drawn_facility_amount_not_carrying_value',model_quantity='facility_drawn_amount',stage='drawn_or_paid',instrument_key='CRWV_DDTL_2_0'),
m('As of December 31, 2024, $3.8 billion of our DDTL 2.0 Facility was drawn and $3.8 billion remained available for borrowing under our DDTL 2.0\nFacility.','3.8','billion',**facility,period_end='2024-12-31',amount_nature='undrawn_facility_availability_not_debt_or_cash',model_quantity='facility_available_amount',stage='available',instrument_key='CRWV_DDTL_2_0'),
m('As of December 31, 2024, we have paid $0 million and $21 million in principal and in interest on outstanding amounts under our Delayed Draw Term Loan 2.0 Facility, respectively.','0','million',**facility,payer='CCAC IV',receiver='DDTL 2.0 lenders',period_end='2024-12-31',amount_nature='cumulative_principal_repayment_not_zero_outstanding_debt',model_quantity='facility_principal_cash_paid_cumulative',stage='drawn_or_paid',event_type='repayment',component_kind='principal',instrument_key='CRWV_DDTL_2_0'),
m('As of December 31, 2024, we have paid $0 million and $21 million in principal and in interest on outstanding amounts under our Delayed Draw Term Loan 2.0 Facility, respectively.','21','million',**facility,payer='CCAC IV',receiver='DDTL 2.0 lenders',period_end='2024-12-31',amount_nature='cumulative_interest_cash_payments_not_annual_expense',model_quantity='facility_interest_cash_paid_cumulative',stage='drawn_or_paid',event_type='payment',component_kind='interest',instrument_key='CRWV_DDTL_2_0'),
m('behalf of certain lenders as the lead lenders, and the arrangers, bookrunners, and lenders party thereto, providing for a $2.3 billion delayed draw term loan facility (as amended, the “DDTL 1.0 Facility”).','2.3','billion',**facility,payer='DDTL 1.0 lenders',receiver='CCAC II',amount_qualifier='up_to',amount_nature='facility_limit_as_amended_not_outstanding_amount',model_quantity='facility_limit',stage='signed',instrument_key='CRWV_DDTL_1_0'),
m('As of December 31, 2024, our DDTL 1.0 Facility was fully drawn, and we had $2.0 billion outstanding under our DDTL 1.0 Facility.','2.0','billion',**facility,period_end='2024-12-31',amount_nature='outstanding_facility_amount_basis_not_explicit',model_quantity='facility_outstanding_amount',stage='drawn_or_paid',instrument_key='CRWV_DDTL_1_0'),
m('2024, we have paid $288 million and $255 million in principal and in interest on outstanding amounts under our DDTL 1.0 Facility, respectively.','288','million',**facility,payer='CCAC II',receiver='DDTL 1.0 lenders',period_end='2024-12-31',amount_nature='cumulative_principal_cash_repayment',model_quantity='facility_principal_cash_paid_cumulative',stage='drawn_or_paid',event_type='repayment',component_kind='principal',instrument_key='CRWV_DDTL_1_0'),
m('2024, we have paid $288 million and $255 million in principal and in interest on outstanding amounts under our DDTL 1.0 Facility, respectively.','255','million',**facility,payer='CCAC II',receiver='DDTL 1.0 lenders',period_end='2024-12-31',amount_nature='cumulative_interest_cash_payments_not_annual_expense',model_quantity='facility_interest_cash_paid_cumulative',stage='drawn_or_paid',event_type='payment',component_kind='interest',instrument_key='CRWV_DDTL_1_0'),
m('Magnetar, pursuant to which we issued to funds or accounts managed or advised by Magnetar (the “2025 Convertible Note Purchasers”) $50 million aggregate principal amount of Convertible Senior Secured Notes due 2025 (the “2025\nConvertible Notes”).','50','million',counterparty_evidence='anonymous',amount_nature='historical_convertible_principal_not_original_October_2021_cash',model_quantity='convertible_note_historical_principal',family='financing',link_type='convertible_or_safe',stage='signed',instrument_key='CRWV_2021_2025_Convertible_Notes',flag_unknown_reason='annual_note_original_20m_October_2021_increased_to_50m_April_2022_no_original_cash_inferred'),
m('In 2023, the aggregate principal amount of the 2025 Convertible Notes was increased to $55 million as a result of the payment of certain interest payments in kind.','55','million',counterparty_evidence='anonymous',amount_nature='historical_principal_including_PIK_not_new_cash',model_quantity='convertible_note_historical_principal_with_PIK',family='financing',link_type='convertible_or_safe',stage='recognized',instrument_key='CRWV_2021_2025_Convertible_Notes'),
dict(quote='Effective as of September 17, 2024, the 2025 Convertible Note Purchasers caused the 2025\nConvertible Notes to be converted into shares of our Class A common stock pursuant to the terms and conditions of the Note Issuance Agreement.',counterparty_evidence='anonymous',event_date='2024-09-17',event_type='conversion',stage='settled',model_quantity='convertible_note_conversion_not_new_cash',instrument_key='CRWV_2021_2025_Convertible_Notes'),
m('In connection with the issuance of the 2025 Convertible Notes, we granted to Magnetar (a) an option\nto purchase $15.0 million of our Class A common stock at the initial public offering price of $40.00 per share, which option is exercisable until the one-year anniversary of the listing of our Class A common stock and (b) the right (using our\ncommercially reasonable efforts) to subscribe for and purchase at least 5% of our capital stock issued in any future public equity offering by us, including our Class A common stock to be sold and issued in this offering.','15.0','million',counterparty='Magnetar',counterparty_evidence='named',amount_qualifier='up_to',amount_nature='equity_subscription_option_limit_not_cash',model_quantity='equity_subscription_option_limit',family='financing',link_type='equity_primary',stage='signed',instrument_key='CRWV_2021_Magnetar_IPO_option',flag_unknown_reason='actual_fund_and_cash_proceeds_not_disclosed'),
m('funds or accounts managed or advised by Magnetar (the “2025 Note Purchasers”) $125 million aggregate principal amount of Senior Secured Notes due 2025 (the “2025 Notes”).','125','million',**facility,amount_nature='original_note_face_amount_not_current_principal_or_cash',model_quantity='senior_note_original_face_amount',stage='signed',instrument_key='CRWV_2022_2025_Senior_Notes'),
m('On July 17, 2024, we paid\napproximately $136 million to redeem the 2025 Notes in full from the 2025 Note Purchasers, which amount represented the aggregate outstanding principal amount of the 2025 Notes plus accrued and unpaid interest and prepayment premiums, and all\nour obligations under the Note Issuance Agreement and related documents were satisfied and discharged in full (except customary surviving obligations and as otherwise discussed herein).','136','million',**facility,payer='CoreWeave',receiver='2025 Note Purchasers',event_date='2024-07-17',amount_qualifier='approximately',amount_nature='full_note_redemption_including_principal_interest_premium_not_principal_only',model_quantity='note_redemption_cash_payment',stage='settled',event_type='repayment',instrument_key='CRWV_2022_2025_Senior_Notes',flag_unknown_reason='same_prospectus_audited_annual_note_reports_137m_difference_unresolved'),
dict(quote='On March 27, 2025, we entered into an agreement with Magnetar and certain funds or accounts managed or advised by\nMagnetar, pursuant to which Magnetar and certain funds or accounts managed or advised by Magnetar waived their purchase rights in this offering.',counterparty_evidence='anonymous',event_date='2025-03-27',event_type='amendment',stage='terminated',model_quantity='IPO_subscription_rights_waived_not_covenant_waiver_or_equity_disposal',instrument_key='CRWV_2022_Magnetar_IPO_option'),
dict(quote='holders of our capital stock, including funds or accounts managed or advised by Magnetar and NVIDIA, each beneficial owners of more\nthan 5% of our outstanding capital stock,',counterparty='NVIDIA',counterparty_evidence='named',source_perspective='counterparty',model_quantity='NVIDIA_disclosed_beneficial_equity_holding_not_new_cash',family='financing',link_type='equity_primary',stage='recognized',flag_unknown_reason='precise_holding_measurement_date_not_disclosed'),
dict(quote='We have entered into, and intend to continue to enter into, separate indemnification agreements with each\nof our executive officers and directors, including those affiliated with certain of our 5% stockholders.',counterparty_evidence='anonymous',stage='signed',block='contingent_obligations',category_id='indemnification',model_quantity='director_officer_indemnification',instrument_key='CRWV_director_officer_indemnification',trigger_occurred='unknown',flag_unknown_reason='individual_caps_and_calls_not_disclosed'),
dict(abstained=True,abstention_reason='employee_equity_exchange_compensation_and_directed_IPO_program_capacity_not_actual_counterparty_financing',quote='We do not currently know the extent to which these related persons will participate in our directed share program, if at all, or the extent to which they will purchase more than $120,000 in value of our Class A common stock.')]
for row in rows:
 if row.get('counterparty_evidence')=='anonymous':row.setdefault('flag_unknown_reason','individual_fund_lender_stockholder_identities_pending_no_manager_consolidation')
print(store(r,k,rows))
