from authored_helpers import save,money as m
cp='GLOBALFOUNDRIES Inc.'
rows=[]
q='The Company’s total purchases from GF related to wafer manufacturing, research and development activities and other during the three months ended March 30, 2019 and March 31, 2018 were $378 million and $398 million, respectively.'
for n,start,end in [('378','2018-12-30','2019-03-30'),('398','2017-12-31','2018-03-31')]:
 rows.append(m(q,n,'1000000',cp,period_start=start,period_end=end,payer='AMD',receiver=cp,family='commercial',link_type='purchase',stage='delivered',amount_qualifier='exact',amount_nature='related_supplier_purchases_including_other_foundry_volume_fees_not_explicit_cash_or_supplier_GAAP_revenue',model_quantity='related_supplier_purchases',instrument_key='AMD_GF_WSA'))
for n,end in [('12','2019-03-30'),('18','2018-12-29')]:
 rows.append(m('As of March 30, 2019 and December 29, 2018, the amount of prepayment and other receivables related to GF was $12 million and $18 million, respectively, included in Prepayment and receivables—related parties on the Company’s condensed consolidated balance sheets.',n,'1000000',cp,period_end=end,stage='recognized',amount_qualifier='exact',amount_nature='combined_prepayment_and_other_receivables_asset_stock_not_pure_advance_or_financing_component',model_quantity='related_prepayment_and_other_receivables',instrument_key='AMD_GF_WSA',flag_unknown_reason='prepayment_and_other_receivables_not_split_maturity_and_financing_component_not_disclosed'))
for n,end in [('246','2019-03-30'),('326','2018-12-29')]:
 rows.append(m('As of March 30, 2019 and December 29, 2018, the amount of payable to GF was $246 million and $326 million, respectively, included in Payables to related parties on the Company’s condensed consolidated balance sheets.',n,'1000000',cp,period_end=end,stage='recognized',amount_qualifier='exact',amount_nature='related_supplier_payable_stock_not_explicit_borrowing_or_financing_program',model_quantity='related_supplier_payables',instrument_key='AMD_GF_WSA',flag_unknown_reason='payment_terms_and_financing_component_not_disclosed'))
rows += [
dict(quote='On January 28, 2019, the Company entered into a seventh amendment (the Seventh Amendment) to the WSA with GF.',counterparty=cp,counterparty_evidence='named',family='commercial',link_type='purchase_commitment',stage='signed',event_type='amendment',event_date='2019-01-28',instrument_key='AMD_GF_WSA',model_quantity='wafer_supply_agreement_amendment',flag_unknown_reason='commercial_supply_terms_amendment_not_financial_covenant_waiver'),
dict(quote='The Seventh Amendment modifies certain purchase commitments, pricing and other terms of the WSA applicable to wafer purchases at the 12 nm technology node and above by the Company for the period commencing on January 1, 2019 and continuing through March 1, 2024.',counterparty=cp,counterparty_evidence='named',family='commercial',link_type='purchase_commitment',stage='signed',period_start='2019-01-01',period_end='2024-03-01',instrument_key='AMD_GF_WSA',model_quantity='wafer_purchase_commitment',flag_unknown_reason='purchase_targets_and_committed_amount_not_disclosed'),
dict(quote='If the Company does not meet the annual wafer purchase target for any of these years, the Company will be required to pay to GF a portion of the difference between the Company’s actual wafer purchases and the wafer purchase target for that year.',counterparty=cp,counterparty_evidence='named',payer='AMD',receiver=cp,family='commercial',link_type='purchase_commitment',stage='signed',conditionality='conditional',trigger_description='If the Company does not meet the annual wafer purchase target for any of these years',trigger_occurred='unknown',instrument_key='AMD_GF_WSA',model_quantity='conditional_wafer_purchase_shortfall_payment',flag_unknown_reason='target_portion_cap_and_triggered_amount_not_disclosed'),
dict(quote='The Company also agreed to continue to make quarterly payments to GF based on the volume of certain wafers purchased from another wafer foundry.',counterparty=cp,counterparty_evidence='named',payer='AMD',receiver=cp,family='commercial',link_type='purchase_commitment',stage='signed',instrument_key='AMD_GF_WSA',model_quantity='other_foundry_volume_fee_commitment',flag_unknown_reason='fees_unquantified_included_in_reported_supplier_purchases_not_separate_loan'),
dict(quote='On August 30, 2016, in consideration for the limited waiver and rights under the WSA Sixth Amendment, the Company entered into a warrant agreement (the Warrant Agreement) with West Coast Hitech L.P. (WCH), a wholly-owned subsidiary of Mubadala Development Company PJSC (Mubadala).',counterparty='West Coast Hitech L.P.',counterparty_evidence='named',stage='signed',event_type='signing',event_date='2016-08-30',instrument_key='AMD_WCH_warrant_2016',model_quantity='supplier_rights_warrant_issuance',amount_nature='warrant_for_supplier_waiver_not_customer_consideration_or_cash',flag_unknown_reason='commercial_WSA_waiver_not_financial_covenant_event'),
m('During the three months ended March 30, 2019, WCH exercised its warrant to purchase 75 million shares of the Company’s common stock at a purchase price of $5.98 per share for a total amount of $448.5 million.','448.5','1000000','West Coast Hitech L.P.',period_start='2018-12-30',period_end='2019-03-30',payer='West Coast Hitech L.P.',receiver='AMD',amount_qualifier='exact',family='financing',link_type='equity_primary',stage='recognized',event_type='funding',instrument_key='AMD_WCH_warrant_2016',model_quantity='primary_warrant_exercise_consideration',amount_nature='warrant_exercise_purchase_consideration_not_explicit_cash_or_current_stock',flag_unknown_reason='exact_exercise_day_and_cash_receipt_not_explicit'),
dict(quote='GF, WCH and Mubadala Tech are wholly-owned subsidiaries of Mubadala.',counterparty=cp,counterparty_evidence='named',model_quantity='economic_group_control_evidence',issuer_treatment='wholly_owned_subsidiary_of_Mubadala_Development_Company_PJSC',flag_unknown_reason='full_names_and_parent_identity_established_elsewhere_in_same_block_actual_membership_start_unknown'),
dict(quote='GF continues to be a related party of the Company because Mubadala and Mubadala Technology Investments LLC (Mubadala Tech, a party to the WSA) are affiliated with WCH, and a member of the Company\'s Board of Directors is associated with Mubadala.',counterparty='Mubadala Technology Investments LLC',counterparty_evidence='named',model_quantity='related_party_classification',flag_unknown_reason='classification_does_not_establish_AMD_consolidation_or_customer_financing')]
save('bf7fa7712d759101edddbe1a09c7f4cffa4e31a47c832d1195776d7f187fe25c',rows)
