from work.authored_helpers import *
k='00419ceceab385af46e63e62ef089f76de451578b0664dc75aeba3827e994060'
rows=[money('$5,000,000,000 aggregate principal amount of its senior notes','5000000000','1','several_underwriters',counterparty_evidence='anonymous',stage='recognized',amount_qualifier='exact',model_quantity='notes_issued_face_aggregate',amount_nature='issued_face_not_net_cash_components_nonadditive',flag_unknown_reason='exact_issue_day_not_explicit_July12_indentured_not_substituted'),dict(quote='On July 8, 2024, the Company entered into an underwriting agreement',event_date='2024-07-08',stage='signed',model_quantity='notes_underwriting_signed')]
for quote,num,q in [('$1,250,000,000 aggregate principal amount of its 5.050% senior notes due 2027','1250000000','2027'),('$2,250,000,000 aggregate principal amount of its 5.050% senior notes due 2029','2250000000','2029'),('$1,500,000,000 aggregate principal amount of its 5.150% senior notes due 2031','1500000000','2031')]:
 rows.append(money(quote,num,'1','several_underwriters',counterparty_evidence='anonymous',stage='recognized',amount_qualifier='exact',model_quantity='notes_'+q+'_issued_face',amount_nature='component_of_aggregate_face_not_net_cash',flag_unknown_reason='exact_issue_day_not_explicit'))
rows.extend([dict(quote='will not be guaranteed by any of the Company’s subsidiaries',model_quantity='notes_explicit_no_subsidiary_guarantee',flag_unknown_reason='unsecured_unsubordinated_issuer_notes_structurally_subordinate_to_subsidiary_liabilities'),abstention('The Company expects to use the net proceeds received from the issuance of the Notes for general corporate purposes and for repayment of debt.','Full item: underwriting/signing, three series, actual sold/issued wording, registrations, base/supplemental indenture, maturities/unsecurity/subs non-guarantee, planned use and all exhibit renvois read. No exact net cash or actual repayment/default/guarantee call/F4 original new-series supplement without Item3.03. Representatives acting for themselves but amounts not individually allocated.')])
save(k,rows)
k='cffedffbd6d38e9dad4062b516af293a89c66fb9dd8e807551b8788fbad93953'
save(k,[dict(quote='Broadcom Inc. (the “Company”) completed its acquisition of VMware, Inc. (“VMware”, and such acquisition, the “VMware Merger”) on November 22, 2023.',event_date='2023-11-22',stage='recognized',counterparty='VMware, Inc.',counterparty_evidence='named',model_quantity='VMware_acquisition_completed'),dict(quote='provide certain pro forma financial information regarding the VMware Merger for the two fiscal quarters ended May 5, 2024 and year ended October 29, 2023.',model_quantity='VMware_merger_pro_forma_information_scope',flag_unknown_reason='as_if_combined_pro_forma_not_actual_historical_group_totals_or_new_cash'),abstention('As previously disclosed','Full item read. Historical completed acquisition and pro forma information are not current acquisition payment, retroactive actual consolidated group scope or customer funding. No numeric pro forma results imported from ineligible exhibits.')])
k='6e6378da1903064cd1d88f2c52d479a12dc451fc0359751acb1eb181cb37629c'
save(k,[dict(quote='an unsolicited mini-tender offer by Tutanota LLC to purchase up to 400,000 shares of Alphabet’s Class A common stock at a price of $180 per share in cash',counterparty='Tutanota LLC',counterparty_evidence='named',stage='intent_non_binding',model_quantity='unsolicited_secondary_mini_tender_offer',flag_unknown_reason='offer_to_existing_holders_not_actual_issuer_primary_funding_or_customer_financing'),dict(quote='The Company is not affiliated, or associated in any way, with Tutanota LLC',counterparty='Tutanota LLC',counterparty_evidence='named',model_quantity='tender_offeror_explicit_not_affiliated'),abstention('Stockholders who have already tendered their shares may withdraw them','Full item: third-party secondary offer/share cap/price/date, issuer nonendorsement, withdrawal/future expiry/extension and nonaffiliation read. No actual purchase, issuer cash or proven ownership exit.')])
