from work.authored_helpers import *

save('2d4b043309e68fa959a4538921092900b9535d33d30152f89ea6b2511ecf1ed8',[
 dict(quote='waives the Inphi Notes Issuer’s and the New Marvell Parent’s obligation to offer to repurchase the Notes in compliance with the covenant set forth in Article 15 of the Indenture',event_date='2021-04-20',event_type='amendment',event_observable='F4',event_present=True,stage='signed',model_quantity='Inphi_exchange_agreement_repurchase_covenant_waiver',flag_unknown_reason='Header and ALL3 ordered body packets personally read. Same Item1.01 cb255f06 independently confirms separate Apr20 executed exchange agreements. Form contains negotiated waiver of merger-related offer-to-repurchase covenant for exchanged notes; no actual distress/default inferred. Original form title, not title-based autonomous amendment, but full reading required because anonymous investors not demonstrated all financial institutions. Executed actual agreement corroborated by Item, expected Apr29 settlement not actual conversion.'),
 dict(quote='no cash will be paid to any Exchanging Investor in respect of any accrued and unpaid interest on the Exchanged Notes or otherwise in respect of the Exchange.',model_quantity='Inphi_exchange_shares_non_cash_rule',flag_unknown_reason='Exchange consideration shares only, not new primary cash or cash interest payment. Sec19 deemed parent-subsidiary cash transfer for TAX purposes is not actual cash proceeds or GAAP recognition. Body variable share ratios and cash-equivalent formulas are blank placeholders; independent Item signed9.6m2021/199.5m2025 old principal and3909350 base shares not imported as body amounts.'),
 abstention('Exchanging Investor Information','Entire body3 packets read including Exhibits A, B1/B2, C1/C2 and D. Investor/account names and principal amounts blank; no confirmed nonfinancial financing beneficiary, control or current stake. Accredited/QIB does not prove bank status; C tax non-bank forms are templates, not actual holder evidence. Reference period length, price variables, signatures and delivery quantities blank. June30 optional abandonment, withholding24/30percent and50dollar tax penalty not actual default/fee/cash. Contract delay exceptions not actual acceleration. Actual April20 MTI/Inphi group reorganization from same independently read Item not Oct29 signing date.')
])
save('e080326f1ab12b909c88c1e457578b6798049124d5be4d4a565ae41b9b4987de',[
 dict(quote='The Company and the Trustee are on this date executing this Second Supplemental Indenture, which will become effective on the date hereof.',event_date='2021-04-15',event_type='amendment',event_observable='F4',event_present=True,stage='signed',model_quantity='MRVL_old_2023_2028_notes_restrictive_covenant_amendment_signed',flag_unknown_reason='Header and entire sole body packet read, autonomous Supplemental with Item3.03. Same Item3.03 d6eb8f65 FULL reread Apr15 executed, but operative upon consent/exchange settlement, expectedMay4. Sec4 deletes change-of-control purchase, liens, sale-leaseback, listed default events, merger and financial-information terms; no actual distress or waived payment default inferred. April15 signing date not May4 operation; historical June22,2018 base not new cash or new F4.'),
 dict(quote='upon written notice from the Company to the Trustee that MTI has made the Consent Payment',conditionality='conditional',trigger_description='upon written notice from the Company to the Trustee that MTI has made the Consent Payment',trigger_occurred='unknown',model_quantity='MRVL_old_notes_amendment_operation_condition',flag_unknown_reason='Condition to operative deletion distinct from executed effective agreement. Offering memorandum consent-payment amount absent; no payment occurrence inferred here. Same Item expectedMay4; later May4 independently reported exchange closes, but no written notice or payment amount imported. If payment not made, amendment terminates conditionally; not actual termination/default.'),
 abstention('IN WITNESS WHEREOF','Physical header and entire body personally read. Majority consents received actual86.47/95.34percent from independent Item, not majority of all company debt and not new cash. Bermuda MTG still parent of DE MTI at April15/19; reverse parent reorganization becomes actual Apr20, not retroactively current. No private Offering Memorandum, outstanding principal or consent fee supplied.')
])
save('d8b6adaccd2a233e85ce3c62325ce9a7ab1960be0ed22c5d48b4ec7b931db071',[dict(abstention('Dated as of April 12, 2021','Complete physical header0:1813 read; same Item1.01 6cf66135 FULL reread. Ordered body0,1,2,3of9 read SOLE holder/party classification: Sec202 financial DTC/Cede global legend, Sec305 global registered holder Depositary/nominee, US Bank NA financial trustee; no identified outside nonfinancial party, no claim every beneficial QIB is bank. Entire body1813:462585 excluded including read scope parts,4:8UNREAD; no amount/covenant/link/alias/bodyF4 admitted. Independent actual new2bn face500/750/750m, MTI wholly owned MTG at Apr12; Inphi transaction pending then, actualApr20 only. Special101percent redemption conditional on merger failure not actual cash/default; historical or ordinary origin terms not new F4.'),model_quantity='exhibit_body_excluded_financial_parties_only',raw_byte_start=0,raw_byte_end=1813,locator='rawbytes:0:1813')])
