"""Authored after all candidates and both full text parts were read."""
from pathlib import Path
from work.authored_helpers import *
k='6ec77866493191f68cfafbbf7c8caea50d09f67ddbce937453d57bf9ceea13b9'
prior=next(Path('work/observations').glob('e351*.jsonl')).stem
rows=repeat_chosen_rows(prior,['consolidation_scope_and_intercompany_elimination','VIE_investments_nonconsolidated','private_investment_valuation_policy','customer_financing_program_policy','Inflection_IP_license_agreement','Inflection_other_investor_ownership_below10pct'])
rows.extend([dict(quote='We have recast certain prior period amounts to conform to the current period presentation.',model_quantity='prior_period_presentation_reclassification',basis_break=True,recast_cause='presentation_reclassification',flag_unknown_reason='affected_sublines_unknown_explicit_consolidated_totals_unchanged'),dict(quote='The recast of these prior period amounts had no impact on our consolidated balance sheets, consolidated income statements, or consolidated cash flows statements.',model_quantity='presentation_recast_consolidated_totals_unchanged'),dict(quote='we determined we should increase the estimated useful lives of both server and network equipment from four years to six years. This change in accounting estimate was effective beginning fiscal year 2023.',model_quantity='server_network_life_extension_not_F7',basis_break=True,recast_cause='accounting_change',flag_unknown_reason='assessment_July2022_month_only_no_quantified_effect_in_this_block'),dict(quote='we may provide other credits or incentives, and in certain instances we estimate customer usage of our products and services, which are accounted for as variable consideration when determining the amount of revenue to recognize.',model_quantity='customer_credits_incentives_variable_revenue_policy',counterparty_evidence='anonymous',flag_unknown_reason='generic_policy_no_named_customer_amount_financing_link_or_noncash_treatment'),dict(quote='we have determined our contracts generally do not include a significant financing component.',model_quantity='contract_invoicing_generally_no_significant_financing_component',flag_unknown_reason='generally_not_all_contracts_not_zero_customer_financing_receivables')])
def t(fid,q,qty,nature):rows.append(authored_tagged(k,fid,q,model_quantity=qty,stage='recognized',amount_nature=nature,flag_unknown_reason='anonymous_counterparties_not_OpenAI_by_proximity'))
for ids,q,qty,nature in [(['42cd94905fd51605e54908529395cc3b23eaa1eee2c500e1b440e80769e3913d','336d62f3a34c4f667b92dce3b4d299d1779a89912cf83f00c3026aa2aea8f292'],'As of June 30, 2024 and 2023, long-term accounts receivable, net of allowance for doubtful accounts, was $4.9 billion and $4.5 billion, respectively,','noncurrent_trade_receivables','noncurrent_trade_AR_stock_not_all_customer_financing'),(['dd5f7252cb06496f93f9ec9af5a9a3b44431457bfd8dd4bb992990da93ed89a9','c31b20d14010ae3697ce3eef216d4ca3dae7e624b9754143968a09fd300ed725'],'As of June 30, 2024 and 2023, other receivables related to activities to facilitate the purchase of server components were $10.5 billion and $9.2 billion, respectively,','server_component_purchase_facilitation_receivables','current_receivable_stock_not_new_cash_supplier_allocation_unknown'),(['44027829869ed0a0bb76f5f403e885414a4b95fb9a0d40f07be87c5870cd2245','389b3e17ec16163d9ecdc86215470418755405b8e95c384ae93558bce2978bf6'],'As of June 30, 2024 and 2023, our financing receivables, net were $4.5 billion and $5.3 billion, respectively,','customer_financing_receivables_net','net_current_and_noncurrent_financing_stock_not_new_cash')]:
 for fid in ids:t(fid,q,qty,nature)
rows.append(abstention('If market, industry, and/or investee conditions deteriorate, we may incur future impairments.','Conditional impairment policy is not actual F6. Complete first note has no explicit substantial-doubt warning or OpenAI commitment clause. Segment and tax standards pending; contract costs immaterial not zero.'))
if __name__=='__main__':save(k,rows)
