from pathlib import Path
from decimal import Decimal
from secfragility.reader import store
u='http://www.xbrl.org/2003/iso4217:USD'
def a(q,n,s,**f):return dict(quote=q,amount=str(Decimal(n)*{'million':1000000,'billion':1000000000,'unit':1}[s]),unit=u,currency='USD',amount_origin='narrative_only',amount_qualifier='approximately')|f
qwp='In 2025, Amazon purchased approximately $840,000 of advertising from, and paid approximately $1.9 million related to digital content and approximately $800,000 for data licensing to, The Washington Post entities, all on terms negotiated on an arms-length basis.'
wp=dict(counterparty='The Washington Post entities',counterparty_evidence='named',payer='Amazon',receiver='The Washington Post entities',period_start='2025-01-01',period_end='2025-12-31',family='commercial',link_type='purchase',flag_unknown_reason='individual_publisher_legal_entities_pending')
qs='As previously disclosed, in 2022, Amazon announced agreements with Blue Origin and a third party pursuant to which it expected to pay approximately $7.4 billion for satellite launch and related services through 2028, of which approximately $2.7 billion was expected to be paid to Blue Origin.'
qp='Since the beginning of the last fiscal year, Amazon paid approximately $2.2 billion under the agreements, of which approximately $1.8 billion is estimated to have been paid to Blue Origin.'
rows=[a('In 2025, Amazon sold approximately $12.5 million of consumer goods to Blue Origin under a line of credit.','12.5','million',counterparty='Blue Origin',counterparty_evidence='named',payer='Blue Origin',receiver='Amazon',period_start='2025-01-01',period_end='2025-12-31',amount_nature='consumer_goods_sold_under_credit_line_not_explicit_GAAP_revenue_or_cash_receipts',model_quantity='related_party_goods_sales_under_vendor_credit',family='commercial',link_type='purchase',stage='delivered',flag_unknown_reason='cash_receipts_credit_outstanding_and_recognized_revenue_not_disclosed'),
a(qwp,'840000','unit',**wp,amount_nature='advertising_purchased_not_explicit_cash_paid',model_quantity='related_party_advertising_purchases',stage='delivered'),
a(qwp,'1.9','million',**wp,amount_nature='digital_content_cash_payments',model_quantity='related_party_digital_content_cash_payments',stage='drawn_or_paid',event_type='payment'),
a(qwp,'800000','unit',**wp,amount_nature='data_licensing_cash_payments',model_quantity='related_party_data_licensing_cash_payments',stage='drawn_or_paid',event_type='payment'),
a(qs,'7.4','billion',counterparty_evidence='anonymous',payer='Amazon',receiver='Blue Origin and a third party',amount_nature='2022_expected_launch_services_payments_through_2028_not_firm_current_remaining_obligation',model_quantity='historical_expected_launch_services_payments',family='commercial',link_type='purchase_commitment',instrument_key='Amazon_2022_launch_service_agreements',flag_unknown_reason='no_current_remaining_commitment_no_start_end_exact_dates_or_binding_amount'),
a(qs,'2.7','billion',counterparty='Blue Origin',counterparty_evidence='named',payer='Amazon',receiver='Blue Origin',amount_nature='Blue_Origin_component_of_historical_expected_launch_services_payments',model_quantity='historical_expected_launch_services_payments_component',family='commercial',link_type='purchase_commitment',instrument_key='Amazon_2022_launch_service_agreements',flag_unknown_reason='component_of_7_4b_no_current_remaining_commitment_or_binding_amount'),
a(qp,'2.2','billion',counterparty_evidence='anonymous',payer='Amazon',receiver='Blue Origin and a third party',period_start='2025-01-01',amount_nature='cumulative_launch_services_cash_payments_to_multiple_suppliers',model_quantity='launch_services_cash_payments_cumulative',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',instrument_key='Amazon_2022_launch_service_agreements',flag_unknown_reason='exact_payment_period_end_and_third_party_identity_not_disclosed'),
a(qp,'1.8','billion',counterparty='Blue Origin',counterparty_evidence='named',payer='Amazon',receiver='Blue Origin',period_start='2025-01-01',amount_nature='estimated_Blue_Origin_component_of_cumulative_cash_payments',model_quantity='launch_services_cash_payments_cumulative_component',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',instrument_key='Amazon_2022_launch_service_agreements',flag_unknown_reason='estimated_component_of_2_2b_exact_payment_period_end_not_disclosed'),
dict(abstained=True,abstention_reason='employee_compensation_outside_counterparty_financing_and_commercial_exposure',quote='Her compensation is consistent with the total compensation provided to other employees of the same level with similar responsibilities.')]
print(store(Path('.').resolve(),'2a94cb7b6226ee719c6a9c6ef16890afda4960459409e48c25329ce8708edfb7',rows))
