from work.authored_helpers import *
k='f70033bc57720c2deea9c99bd78742cb59c8c566120dcd0d496f553f6cfd69c1'
save(k,[dict(quote='On June 22, 2026, the Company announced the commencement of an offering of senior unsecured notes',stage='intent_non_binding',event_date='2026-06-22',model_quantity='senior_unsecured_notes_offering_commenced',flag_unknown_reason='no_terms_principal_pricing_or_actual_cash_issuance_here'),dict(quote='The Company intends to use the net proceeds from the Notes offering to repay the outstanding borrowings under its bridge loan facility in full',model_quantity='offering_intended_bridge_repayment',flag_unknown_reason='future_use_intention_not_actual_repayment'),abstention('The timing of pricing and terms of the Notes are subject to market conditions and other factors.','Full item; unpriced offering and planned repayment only. Later pricing or June26issuance not imported. No actual cash amount, payment, default, waiver or termination.')])
k='edb38d9322fce3c346cf59d1ec4e1bfdd51bb8cf579a71a34f11da2dbfb50079'
save(k,[dict(quote='On June 17, 2026, the Company issued a press release announcing the expiration, upsize and results of the Offers.',event_date='2026-06-17',model_quantity='debt_tender_results_announcement',flag_unknown_reason='no_accepted_principal_or_cash_repayment_amount_in_item'),abstention('announcing the pricing terms of the previously announced cash tender offers','Full item; tender pricing/results referenced exhibits, no actual cash or principal amount in this block. Tender expiration not capacity termination or financial-covenant waiver.')])
k='34bbb4e101f02e061c2a5f0efd990e6eec4bbaa9eb85f07c55f9ce5f9c16e6e6'
q='On June 18, 2026, CoreWeave, Inc. (“CoreWeave”) completed its previously announced private offering of $1,250 million in aggregate principal amount of its dollar-denominated 9.625% Senior Notes due 2032 (the “USD Notes”) and €2,000 million in aggregate principal amount of its euro-denominated 8.500% Senior Notes due 2032'
rows=[money(q,'1250','1000000','qualified_institutional_buyers',counterparty_evidence='anonymous',receiver='CoreWeave, Inc.',stage='recognized',event_date='2026-06-18',period_end='2026-06-18',amount_qualifier='exact',family='financing',link_type='loan_or_facility',block='recognized_liabilities',category_id='debt',component_kind='principal',measurement_basis='face',model_quantity='USD_2032_senior_notes_principal_issued',amount_nature='USD_issued_face_not_cash_net_proceeds',flag_unknown_reason='no_individual_buyer_amount_allocation_no_add_to_EUR_without_FX'),dict(quote=q,amount='2000000000',unit='http://www.xbrl.org/2003/iso4217:EUR',currency='EUR',amount_origin='narrative_only',amount_qualifier='exact',counterparty='qualified_institutional_buyers',counterparty_evidence='anonymous',receiver='CoreWeave, Inc.',stage='recognized',event_date='2026-06-18',period_end='2026-06-18',family='financing',link_type='loan_or_facility',block='recognized_liabilities',category_id='debt',component_kind='principal',measurement_basis='face',model_quantity='EUR_2032_senior_notes_principal_issued',amount_nature='EUR_issued_face_not_cash_net_proceeds',flag_unknown_reason='no_individual_buyer_amount_allocation_no_invented_USD_FX'),dict(quote='The Senior Notes will mature on July 15, 2032.',model_quantity='senior_notes_maturity_date',flag_unknown_reason='future_maturity_not_actual_repayment'),dict(quote='The Senior Notes are guaranteed on a senior unsecured basis by certain wholly-owned subsidiaries of CoreWeave',stage='signed',event_date='2026-06-18',family='credit_support',link_type='guarantee',model_quantity='senior_notes_subsidiary_unsecured_guarantees',flag_unknown_reason='subsidiaries_not_named_guarantee_overlaps_issuer_face_not_additive_no_actual_call'),dict(quote='U.S. Bank Europe DAC, UK Branch, as paying agent.',counterparty='U.S. Bank Europe DAC, UK Branch',counterparty_evidence='named',model_quantity='EUR_notes_paying_agent_role',flag_unknown_reason='paying_agent_registrar_trustee_not_cash_buyer'),dict(quote='CoreWeave intends to use the proceeds from the offering of the Senior Notes for general corporate purposes, including, without limitation, repayment of outstanding indebtedness',model_quantity='senior_notes_intended_proceeds_use',flag_unknown_reason='not_actual_repayment_capex_or_customer_cash'),abstention('The Senior Notes Indentures provide for customary events of default','Full item read including cash interest schedule, redemption/equity-claw, change-of-control101%put and eight covenant categories. Original indentures not amendment/waiver; conditional repurchase not actual payment. No final net cash, default, guarantee call or capacity termination. Separate EUR/USD faces not summed without documented FX.')]
save(k,rows)
