from work.authored_helpers import *
save('cf7445b18ac4fda9a49449fd9e787cd73d59e9bb04c882a03f76a01ab811bab2',[
    dict(abstention('GUARANTEE','Complete physical first page read. March30_2026 original parentguarantee; explicit financial institutions as lenders and USBankTrust collateralagent on behalf of sameSecuredParties. Borrower known groupindirectsubsidiary via samefullyreread1.01 key12a0b329, no external nonfinancialparty. No autonomous amendment or Item3.03. Bodyfinancial_parties_only excluded, Schedule1 GuaranteedObligations not read/exploited; headerunconditionalword alone does NOT establish fullpaymentrecourse or currentcall, same1.01 limitedbadacts characterization preserved. CoreWeaveInc DE explicit. No inferred currentactualcash, guaranteedamount or unknowns zero.'),model_quantity='exhibit_body_excluded_financial_parties_only',raw_byte_start=0,raw_byte_end=9078,locator='rawbytes:0:9078')
])
save('aeb5018a288fcd3138b751dceabdb6fa064ba4227e359a16417a0dbd6bd53aec',[
    dict(abstention('certificate establishing the terms of notes','Complete physical first page read. March16_2026 original officer certificate newEIGHTseries, March11underwriting agreement explicitly financialunderwriters in professionalcapacity thoughindividualnames not infirstpage; noultimatebeneficialholders or amounts invented. No amendmentorItem3.03. Financialparties_only bodyexcluded, referencedApril13_2022supplementhistorical notcurrentF4. WellsFargoBankNA priortrustee and ComputershareTrustCoNA successor current financialtrustee distinct, not ultimateholder. AmazonComInc DE legalidentity explicit; newseriesapproval not actualcashdraw inferred.'),model_quantity='exhibit_body_excluded_financial_parties_only',raw_byte_start=0,raw_byte_end=6334,locator='rawbytes:0:6334')
])
save('950faaccdfd4089be7ec1700d0ec820778145aaf05700bf36f7f0145cfd68ca3',[
    dict(abstention('certificate establishing the terms of notes','Complete physical first page read. March13_2026 originalofficer certificate newELEVENseries; March10underwritingagreement managers JPMorganSecuritiesLLC,CitigroupGlobalMarketsInc,GoldmanSachsCoLLC,HSBCSecuritiesUSAInc explicitly financial. No amendmentorItem3.03; bodyfinancial_parties_only exclusion. OtherunderwritersScheduleII not inheader, noinventedultimateholders. WellsFargoBankNA historicalpriortrustee and ComputershareTrustCoNA successor distinct, referencedApril13_2022supplement notcurrentF4. AmazonComInc DEexplicit; newseriesinitialterms not actualdraw orcash fromexcludedbody.'),model_quantity='exhibit_body_excluded_financial_parties_only',raw_byte_start=0,raw_byte_end=6577,locator='rawbytes:0:6577')
])
