from work.authored_helpers import *
rows=[money('completed its issuance and sale of $11.0 billion in aggregate principal amount of senior unsecured notes','11','1000000000','initial_note_purchasers',counterparty_evidence='anonymous',receiver='Broadcom Inc.',stage='recognized',event_date='2019-04-05',family='financing',link_type='loan_or_facility',model_quantity='aggregate_issued_note_face',amount_qualifier='exact',amount_nature='aggregate_face_includes5series_not_actualnetcash')]
for quote,number,year in [('$2,000 million aggregate principal amount of 3.125% senior notes due 2021','2000','2021'),('$1,500 million aggregate principal amount of 3.125% senior notes due 2022','1500','2022'),('$2,000 million aggregate principal amount of 3.625% senior notes due 2024','2000','2024'),('$2,500 million aggregate principal amount of 4.250% senior notes due 2026','2500','2026'),('$3,000 million aggregate principal amount of 4.750% senior notes due 2029','3000','2029')]:
 rows.append(money(quote,number,'1000000','initial_note_purchasers',counterparty_evidence='anonymous',receiver='Broadcom Inc.',stage='recognized',event_date='2019-04-05',family='financing',link_type='loan_or_facility',model_quantity='issued_note_face_'+year,amount_qualifier='exact',amount_nature='series_component_of11bnface_not_actualnetcash',flag_unknown_reason='passed_maturity_not_actual_repayment_or_default'))
for name in ['Broadcom Technologies Inc.','Broadcom Corporation','Broadcom Cayman Finance Limited']:
 rows.append(dict(quote='by Broadcom Technologies Inc., a Delaware corporation, Broadcom Corporation, a California corporation and Broadcom Cayman Finance Limited, an exempted company incorporated with limited liability under the laws of the Cayman Islands',counterparty=name,counterparty_evidence='named',stage='signed',event_date='2019-04-05',family='credit_support',link_type='guarantee',model_quantity='initial_notes_subsidiary_guarantee_'+name.replace(' ','_'),flag_unknown_reason='fully_unconditional_joint_several_same_notes_unsecured_not_additive_or_called_DE_CA_Cayman_legal_entities_distinct'))
rows.append(abstention('The Company intends to use the net proceeds from the sale of the Notes to repay outstanding indebtedness','Full item read:all5faces/3guars/ranking/redemption/ICRcov/defaults/registration rights. Intendedcreditrepaynot actual payment/netcash; no F4originalindenture/default/actualpenalty from passedApr5,2024deadline. Agents/dealersnotactual creditorallocation.'))
save('83fbc8c780335e372ad859c8d03d85d109658f8554adbf1d683e0630fd037d0f',rows)
save('85e662dd6ad3ea0f5e5f159bebd4d54b8403ee8e68085b3a42cfd1abc8c7872f',[abstention('shares representing approximately 4.0 percent of the Company’s outstanding common stock will be registered in MacKenzie T. Bezos’ name as separate property','Full entire item/signature read. Apr4petition/intended personalsharetransferfuturecourtdecree with votingproxy/exceptions, not companyprimarycash/newinvestment or actual completedtransfer.4percentownershipnotmonetarycash or groupconsolidation.')])
rows=[]
for quote,number,year in [('$2,000 million in aggregate principal amount of 3.125% Senior Notes due 2021','2000','2021'),('$1,500 million in aggregate principal amount of 3.125% Senior Notes due 2022','1500','2022'),('$2,000 million in aggregate principal amount of 3.625% Senior Notes due 2024','2000','2024'),('$2,500 million in aggregate principal amount of 4.250% Senior Notes due 2026','2500','2026'),('$3,000 million in aggregate principal amount of 4.750% Senior Notes due 2029','3000','2029')]:
 rows.append(money(quote,number,'1000000','prospective_note_investors',counterparty_evidence='anonymous',stage='intent_non_binding',model_quantity='priced_proposed_note_face_'+year,amount_qualifier='exact',amount_nature='March29priced_offering_face_not_actualissue_or_cash',flag_unknown_reason='no_executed_binding_underwrite_or_actualclose_here'))
rows.append(abstention('Broadcom intends to use the net proceeds from the sale of the notes to repay outstanding indebtedness','Full item read. Proposed/priced5seriesandintendedrepaymentnot actual cash or covenantamendment. Releases not imported; BankofAmericaN.A.administrativeagentnot all finalcreditors.'))
save('0da57a852f5e87ffd2f865fcc4fb5cd8d003aa0113575f3f1ae3816d76b4c5ac',rows)
