from work.authored_helpers import *
key='5da8b307c6f3d0a418fd33f35dc0abbd5244e29d37813a11ca16f74f37c0cd68'
legal='Advanced Micro Devices, Inc., a Delaware corporation (“AMD” or the “Company”), for value received, hereby certifies that OpenAI OpCo, LLC, or its registered permitted assigns (“OpenAI” or “Warrantholder”), is entitled, subject to the terms and conditions set forth herein, to purchase from the Company 160,000,000 shares of Common Stock'
vesting='The Warrant shall vest with respect to the Warrant Shares in accordance with the vesting schedule as set forth in Exhibit E hereto'
save(key,[
 dict(quote=legal,linkage_quote=legal,linkage_class='L1',counterparty='OpenAI OpCo, LLC',counterparty_evidence='named',payer='Advanced Micro Devices, Inc.',receiver='OpenAI OpCo, LLC',family='customer_consideration',link_type='equity_or_warrants_to_customer',stage='signed',event_date='2025-10-05',model_quantity='AMD_OpenAI_OpCo_customer_warrant_full_legal_parties',conditionality='conditional',trigger_description=vesting,trigger_occurred='unknown',flag_unknown_reason='issuedwarrant_materialinducement_productSupplyAgreement_notactualcommonshareissue_primarycash_FV_orrecognizedcontra;OpCoDEseparateregistrationagreement_header_notGroupPBCAlias'),
 dict(quote='160,000,000 shares of Common Stock',amount='160000000',unit='http://www.xbrl.org/2003/instance:shares',amount_origin='narrative_only',amount_qualifier='up_to',counterparty='OpenAI OpCo, LLC',counterparty_evidence='named',stage='signed',event_date='2025-10-05',model_quantity='AMD_OpenAI_OpCo_warrant_max_underlying_share_count',amount_nature='future_conditional_underlying_shares_not_current_shares_or_money',flag_unknown_reason='0.01persharestrike_andpar_notFV_cash_cashlesspossible_no1.6mprimarycashassumption'),
 dict(quote=vesting,counterparty='OpenAI OpCo, LLC',counterparty_evidence='named',model_quantity='AMD_OpenAI_OpCo_warrant_redacted_vesting_and_exercise_conditions',trigger_description=vesting,trigger_occurred='unknown',flag_unknown_reason='ExEandExF[****]_separatevestingandexerciseconditions_noactualvest_exercise_orrecognizedFV_nocaviardszero'),
 dict(quote='in lieu of making a cash payment, having canceled a portion of this Warrant in payment of the Warrant Price',counterparty='OpenAI OpCo, LLC',counterparty_evidence='named',model_quantity='AMD_OpenAI_OpCo_warrant_cashless_exercise_permission',conditionality='optional',flag_unknown_reason='2a_holderchoicecashorcashless_fiveTradingDayVWAPfutureexerciseFMV_notcurrentwarrantFV_oractualcash'),
 dict(quote='as giving rise to a sales discount or allowance in respect of the supply of product made in connection with the Supply Agreement.',counterparty='OpenAI OpCo, LLC',counterparty_evidence='named',model_quantity='AMD_OpenAI_OpCo_warrant_contractual_tax_discount_treatment',flag_unknown_reason='15_federalstatelocalINCOMETAXintent_notactualGAAPcontra_RV_orFV_amount_E5unknown'),
 dict(quote='on October 5, 2030 (the “Expiration Date”)',counterparty='OpenAI OpCo, LLC',counterparty_evidence='named',model_quantity='AMD_OpenAI_OpCo_warrant_conditional_expiry',flag_unknown_reason='17ETOct5_2030_earlySupplyAgreementforcauseCompanyterminationcancelsunvested_andvestednonexercisable;automaticexerciseONLYExercisableShares_notactualtermination/vesting;NO180dayMetaextensionimported'),
 abstention('Warrant Signature Page','Complete physical header and bothbodypackets personally read includingAMDJeanHu/OpenAIOpCoSarahFriar execution and allsixExhibitsA-F redacted[****]. No actualcash/exercise/vesting/FV orrecognizedcontra proved. ProductPurchaseAgreement private terms notfullcommercialcoverage; maximum shares notcurrentstake orconsolidation. TopCo unnamedultimateparentdefinition notGroupPBCdatedmembership; §11 nostockholderrights untilrecordholderafterexercise. ICA transfers futurepermissions notactualsale orinvestmentcompanyclassification. AmendWaiver§13 ordinarypermission notactualF4; warrantexpiry notItem1.02F9.')
])
