from work.authored_helpers import *
rows=[]
for quote,number,quantity in [('$5.0 billion unsecured revolving credit facility','5','new_revolver_limit'),('$2.0 billion unsecured term A-3 facility','2','new_term_A3_limit'),('$2.0 billion unsecured term A-5 facility','2','new_term_A5_limit'),('$2.0 billion unsecured term A-7 facility','2','new_term_A7_limit')]:
 rows.append(money(quote,number,'1000000000','credit_facility_lenders',counterparty_evidence='anonymous',receiver='Broadcom Inc.',stage='available',event_date='2019-05-07',family='financing',link_type='loan_or_facility',model_quantity=quantity,amount_qualifier='exact',amount_nature='unsecured_new_facility_limit_not_actual_quantified_borrowing',flag_unknown_reason='revolver5year_term3_5_7year_fromClosingDate_actual_term_draws_unquantified_in_explicit_borrowing_clause'))
rows.extend([dict(quote='were made in single borrowings on the Closing Date',stage='drawn_or_paid',event_date='2019-05-07',model_quantity='three_new_term_tranches_actual_drawn',flag_unknown_reason='actual_three_term_borrowings_but_clause_no_amount_no_limit_substitute_for_actual_draw'),money('refinance the $6.0 billion of existing term loans outstanding','6','1000000000','old_term_lenders',counterparty_evidence='anonymous',stage='settled',event_date='2019-05-07',model_quantity='old_term_principal_refinanced',amount_qualifier='exact',amount_nature='old_principal_refinanced_not_total_cash_or_new_draw_quantification'),money('of which up to $500 million may be utilized for the issuance of multicurrency letters of credit.','500','1000000','revolver_lenders',counterparty_evidence='anonymous',stage='available',event_date='2019-05-07',model_quantity='LC_component_in_revolver_limit',amount_qualifier='up_to',amount_nature='explicit_sublimit_reduces_revolver_available_not_extra'),dict(quote='The Company had no borrowings outstanding under the Revolving Facility on the Closing Date.',stage='recognized',event_date='2019-05-07',period_end='2019-05-07',model_quantity='new_revolver_explicitly_no_borrowings',amount_nature='explicit_zero_nonnumeric_source_clause')])
for name in ['Broadcom Corporation','Broadcom Cayman Finance Limited','Broadcom Technologies Inc.']:
 rows.append(dict(quote='The Company’s obligations under the Credit Agreement are guaranteed on an unsecured basis by Broadcom Corporation, a California corporation, Broadcom Cayman Finance Limited, an exempted company incorporated with limited liability under the laws of the Cayman Islands, and Broadcom Technologies Inc., a Delaware corporation.',counterparty=name,counterparty_evidence='named',stage='signed',event_date='2019-05-07',family='credit_support',link_type='guarantee',model_quantity='new_credit_subsidiary_guarantee_'+name.replace(' ','_'),flag_unknown_reason='same_underlying_facilities_not_extra_cash_or_called_CA_Corporation_Cayman_Finance_DE_Technologies_distinct'))
rows.append(abstention('The Credit Agreement was entered into on substantially the same terms and conditions as the Existing Credit Agreement','Full entire item read including newlimits/actualsingletermborrowings/refinance/guarantees, LCoverlap/rates/prepay/ICR3/defaults. Replacementoriginalagreement changesmaturity but no explicitexistingfinancialclauseamendment/waiver F4; no actualbreach/call. Limitsnotnumericdrawsubstitutes.'))
save('e563c577ba50306f7e820889671de47c17e70552fa4e7e483b44d067bbd2902e',rows)
save('7e4c0becc92f30f5b68eb849feb28d1b45bbe3596a9c3947ff5b53534b42f334',[
dict(quote='on the Closing Date the Company terminated all outstanding commitments, and used the proceeds of the Term Facilities, together with cash on hand, to repay all of its outstanding obligations',stage='settled',event_type='repayment',event_date='2019-05-07',model_quantity='old2018_credit_all_obligations_repaid_and_commitments_terminated',flag_unknown_reason='ClosingDateMay7defined_in_personally_read_companion1_01_total_cash_including_fees_interest_unknown_financialfacility_not_F9capacity'),money('$6.0 billion in aggregate principal amount of term loans under such term A-5 facility','6','1000000000','old_term_lenders',counterparty_evidence='anonymous',stage='settled',event_date='2019-05-07',model_quantity='old2018_A5_principal_extinguished',amount_qualifier='exact',amount_nature='immediately_prior_principal_repaid_not_total_cash_or_additive_to_companion6bnrefinance'),dict(quote='no borrowings under such revolving credit facility or such term A-3 facility',stage='recognized',event_date='2019-05-07',model_quantity='old_revolver_and_A3_explicitly_no_borrowings_before_termination',amount_nature='explicit_zero_nonnumeric_source_clause'),abstention('The Existing Credit Agreement originally provided for a $5.0 billion unsecured revolving credit facility','Full item read. Original5+9+9limitsnot currentprincipal or additionalfinance; actualrepayment6oldA5andallobligations not totalcash6inclfees. No financialclausewaiver/default/capacitytermination.')])
save('3b7cd409c08dfad22a8744b303f626b584a880194149a8c2fbfab79fbb03dde0',[abstention('There are no relationships or related transactions between Ms. Washington and the Company that would be required to be reported.','Full entire item read:Apr24appointment effectiveApr25, all directorroles/biography, initial1mGSU/annual350kGSU/75kcash prospectivecompensation, vesting, expenses/indemnification and SchmidtGreene departures/cautions. Governance affiliations not financing/consolidation/clienttransaction; scopednoreportableWashingtontransactions not all relatedpartyzero or ICFRassessF5. Noncashawardrefnot cash funding.')])
