from work.authored_helpers import *

for key,series in [('9277ffd7b05133ea4ebc48a1a7d9f4d5c596b89607555d4594eaa38dc673744c','January2017'),('e8c14a1fa641e530523259ad5d266d0a6e9afee6e9f8c107d4c50bd7bab44c59','October2017')]:
 save(key,[
  dict(quote='Section 11.03 of the Indenture is hereby amended and restated in its entirety as follows:',event_date='2018-04-09',event_type='amendment',event_observable='F4',event_present=True,stage='signed',model_quantity='Broadcom_'+series+'_actual_guarantee_release_clause_amendment',flag_unknown_reason='Header and entire sole body packet personally read, signatures present. Autonomous EX4Supplemental with Item3.03; independently full Item459b276e corroborates guarantee addition/release. Actual financial clause amendment, not proof distress, default or guarantee call; other future release conditions not actual events. Different original January/October2017 series not new debt issuance.'),
  dict(quote='New US Topco hereby agrees to become a Guarantor bound by the guarantee of the Notes on the terms set forth in Article 11 of the Indenture.',counterparty='Wilmington Trust, National Association',counterparty_evidence='named',payer='Broadcom Inc.',receiver='Wilmington Trust, National Association',linkage_class='L1',linkage_quote='Broadcom Inc., a Delaware corporation (“New US Topco”), and Wilmington Trust, National Association, as trustee (the “Trustee”).',family='credit_support',link_type='guarantee',stage='signed',event_date='2018-04-09',event_type='signing',model_quantity='Broadcom_'+series+'_new_US_Topco_guarantee',flag_unknown_reason='Amount and full Article11 extent not provided in this supplement; no paid or called amount. NewUSDE distinct former Singapore parent, no name-only alias. Header CorporationCA conflicts independently ItemCorporationDE D80 preserved; no consolidation dates or aliases inferred from conflict.'),
  dict(quote='Broadcom Cayman LP was automatically and unconditionally released from its guarantee of the Notes in accordance with Section 11.03(b);',stage='terminated',model_quantity='Broadcom_'+series+'_CaymanLP_actual_guarantee_release',flag_unknown_reason='Completed release explicitly recited; exact release day not separately provided in this supplement, observed byApr9. LP ceased to exist after mandatory exchange, not actual guarantor call, cash repayment or extra financial amount.'),
  abstention('IN WITNESS WHEREOF','Full header/body read; same Item3.03 and newUS Item1.01 both read. All financial counterparty trustee; autonomous3.03 exception used, not blanket financialbody admission. ActualApr9 guarantee and release clause changes distinct originalseries, deduplicate shared events in phase3. General-partner SGvsDE acrossItems remainsD83 conflict; no historicalissuer/currentparentalias or consolidation timeline invented.')
 ])

save('58eb42d63899da361aeab37907fec93e9baf28220ac6ede6cf4c851b937f1e58',[
 dict(abstention('dated as of April 9, 2018','Full physical header0:4744 personally read; WilmingtonTrustNA financial trustee. Same Item78c790fa fully read actualApr9newUS guarantee and CaymanLP release supports independentF4, not newcash or actualcall. This occurrence lacksItem3.03, so entirebody4744:18052 excludedUNREAD under11.1 despite corresponding independently admissible oldSG3.03 occurrence. Body never imported; CorpCAvsItemDE D80 and GPcompanyDEvsSG D83 remain unresolved. Anonymousholders not presumed allfinancial; no actual outside nonfinancialholder identified.'),model_quantity='exhibit_body_excluded_financial_parties_only',raw_byte_start=0,raw_byte_end=4744,locator='rawbytes:0:4744')
])
