from work.authored_helpers import *
from work.authored_quarantines import record
k='08e96927e75775a2863daf1ab26e029dc6c61a9e7fe866c6c0807dcfc0cebe2d'
rows=repeat_chosen_rows('4db2a13f1b866312c932026c7c311c7a2cf0a8b72f5cf881058debde4cda3619',['issuer_legal_name_jurisdiction','consolidation_scope','intercompany_elimination'])
rows += [dict(quote='Our fiscal year ending October 31, 2021 (“fiscal year 2021”) is a 52-week fiscal year.',model_quantity='fiscal_calendar',flag_unknown_reason='FY2021_FY2020_52weeks'),abstention('Actual results could differ materially from these estimates,','Complete first note no substantial doubt, actual investment impairment or equipment life change; no later ASU2021-08 adoption imported.')]
save(k,rows)
k='474de633ac6ac2421185efa53922bf1feab03cbd20f64c6826724c218c59f66a'
save(k,[authored_control(k,'our disclosure controls and procedures were effective at the reasonable assurance level.','disclosure_controls_effective',event_present=True),authored_control(k,'There was no change in our internal control over financial reporting identified in connection with the evaluation required by Rules 13a-15(d) and 15d-15(d) of the Exchange Act','no_material_ICFR_change_quarter',flag_unknown_reason='COVID_remote_work_not_MW')])
k='cce4d65ab7c185edff967e8cc6d47b0938f36794eda23dcdd997aa028ba2850b'
record('D65',k,'0001835632-21-000022',[('1689a69ac540a64bebfc223b7afd2e669ca3d75b6d257ca351cb612a73359e1e','anticipated_acquired_cash_and_exercise_proceeds_mixed','includes_expected_exercise_proceeds_not_solely_acquired_cash'),('bbb44714924ecc33ad2f5e56b8a3b8662f4dbf835ee4460a68092fdde9e0b469','anticipated_acquisition_net_cost','net_cost_after_cash_and_exercise_proceeds_not_equity_consideration_transferred')], 'Marvell juillet 2021 : cinq candidats et première note entière lus. Innovium est une intention d’acquisition annoncée après clôture, avec prix brut en actions de 1,1 milliard, cash et exercices attendus mêlés de 145 millions et coût net de 955 millions. Les deux dernières balises isolent à tort du cash acquis seul et une contrepartie en capital ; quarantaine sans remplacement. Aucune clôture effective d’octobre importée.')
rows=repeat_chosen_rows('f9364038cdbfe38c01b47be98ebae031357dd00741b5d5085f6a52faaf487178',['issuer_legal_name_jurisdiction','consolidation_scope','intercompany_elimination','fiscal_calendar','Inphi_acquisition_completed'])
rows += [dict(quote='include the operating results of Inphi for the period from the date of acquisition through the Company’s second quarter ended July 31, 2021.',model_quantity='Inphi_prospective_consolidation',basis_break=True,recast_cause='unknown'),dict(quote='Marvell Technology Group Ltd and Inphi became wholly owned subsidiaries of the new parent company, MTI, on April 20, 2021.',model_quantity='new_parent_predecessor_and_Inphi_wholly_owned',event_date='2021-04-20',basis_break=True,recast_cause='unknown',flag_unknown_reason='literal_name_without_dot_no_automatic_legal_identity_merge'),dict(quote='Subsequent to quarter end, on August 3, 2021, the Company announced its intent to acquire Innovium, Inc. (“Innovium”),',model_quantity='Innovium_acquisition_intent_announced',counterparty='Innovium, Inc.',counterparty_evidence='named',event_date='2021-08-03',stage='intent_non_binding',conditionality='conditional',trigger_description='subject to the satisfaction of customary closing conditions, including approval by Innovium’s stockholders and applicable regulatory approvals.',flag_unknown_reason='announcement_not_signed_or_closed_no_October_completion_import'),abstention('The acquisition price includes Innovium cash and exercise proceeds expected at closing of approximately $145 million, resulting in an estimated net cost to the Company of $955 million.','Two mixed or mislabeled candidates quarantined; no narrative numeric replacement.'),abstention('As events continue to evolve and additional information becomes available, these estimates may change materially in future periods.','Complete note no substantial doubt, actual investment impairment or equipment life change.')]
q="The estimated acquisition price of $1.1 billion consists of approximately 19.05 million shares of the Company's common stock"
for fid,qty in [('6cf83299dabb947fbb4237b0edd4018c0fde45a0fd7c846db112562bc377c8eb','Innovium_anticipated_gross_all_stock_acquisition_price'),('c20a7bae148613f56677e14ead995eed4faaefb8e6dbb1fffd145c52a759e2e2','Innovium_anticipated_shares_issued')]:rows.append(authored_tagged(k,fid,q,model_quantity=qty,counterparty='Innovium, Inc.',counterparty_evidence='named',stage='intent_non_binding',amount_nature='forecast_all_stock_not_actual_cash',amount_qualifier='approximately',flag_unknown_reason='forecast_end_calendar2021_not_exact_close_date_July30_VWAP_basis'))
save(k,rows)
