from authored_helpers import save,money as m
cp='GLOBALFOUNDRIES Inc.'
rows=[
dict(quote='Mubadala Technology Investments LLC, formerly known as Advanced Technology Investment Corporation (“Mubadala Tech”), West Coast Hitech L.P. (“WCH”) and GLOBALFOUNDRIES Inc. (one of our foundry suppliers, “GF”) are wholly-owned subsidiaries of Mubadala Investment Company PJSC (“Mubadala”), a joint stock company incorporated in the Emirate of Abu Dhabi and owned by the Government of the Emirate of Abu Dhabi.',counterparty='Mubadala Investment Company PJSC',counterparty_evidence='named',model_quantity='economic_group_control_evidence',issuer_treatment='wholly_owned_subsidiaries_of_Mubadala_Investment_Company_PJSC',flag_unknown_reason='actual_membership_start_not_disclosed_not_merged_with_Development_Company_without_identity_evidence'),
dict(quote='Mubadala Technology Investments LLC, formerly known as Advanced Technology Investment Corporation (“Mubadala Tech”)',counterparty='Mubadala Technology Investments LLC',counterparty_evidence='named',model_quantity='entity_alias_evidence',issuer_treatment='formerly_Advanced_Technology_Investment_Corporation',flag_unknown_reason='rename_date_not_disclosed'),
dict(quote='As of March 18, 2019, WCH beneficially owned approximately 6.9% of our outstanding common stock.',counterparty='West Coast Hitech L.P.',counterparty_evidence='named',amount='6.9',unit='percent',amount_origin='narrative_only',amount_qualifier='approximately',period_end='2019-03-18',stage='recognized',amount_nature='beneficial_ownership_stock_not_primary_cash',model_quantity='equity_ownership_percent',instrument_key='AMD_WCH_equity'),
dict(quote='In February 2019, WCH ceased to beneficially own at least 10% of our outstanding common stock. Mr. Yahia is not being nominated for re-election to the Board at the Annual Meeting.',counterparty='West Coast Hitech L.P.',counterparty_evidence='named',model_quantity='ownership_threshold_and_board_designation_change',flag_unknown_reason='below_ten_percent_not_full_equity_exit_exact_event_day_not_disclosed'),
dict(quote='Pursuant to the WSA, we are required to purchase all of our microprocessor and accelerated processing unit (“APU”) product requirements and a certain portion of our graphics processing unit (“GPU”) product requirements from GF with limited exceptions.',counterparty=cp,counterparty_evidence='named',payer='AMD',receiver=cp,family='commercial',link_type='purchase_commitment',stage='signed',instrument_key='AMD_GF_WSA',model_quantity='wafer_purchase_commitment',flag_unknown_reason='amount_unquantified'),
dict(quote='The WSA terminates no later than March 2, 2024.',counterparty=cp,counterparty_evidence='named',stage='signed',instrument_key='AMD_GF_WSA',model_quantity='wafer_supply_agreement_term',flag_unknown_reason='latest_permitted_end_not_actual_termination_and_different_from_seventh_amendment_period_end'),
m('In consideration for these rights, we agreed to pay GF $100 million, which was paid in installments starting in the fourth fiscal quarter of 2016 through the third fiscal quarter of 2017.','100','1000000',cp,payer='AMD',receiver=cp,family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_qualifier='exact',instrument_key='AMD_GF_WSA_sixth_amendment_2016',model_quantity='supplier_waiver_rights_cash_payments',amount_nature='aggregate_historical_supplier_commercial_rights_payments_not_customer_funding',flag_unknown_reason='quarter_dates_and_annual_installment_allocation_not_published_in_block'),
dict(quote='Starting in 2017 and continuing through 2020, we also agreed to make quarterly payments to GF based on the volume of certain wafers purchased from another wafer foundry.',counterparty=cp,counterparty_evidence='named',payer='AMD',receiver=cp,family='commercial',link_type='purchase_commitment',stage='signed',instrument_key='AMD_GF_WSA',model_quantity='other_foundry_volume_fee_commitment',flag_unknown_reason='fees_unquantified'),
dict(quote='On January 29, 2019, we entered into a seventh amendment to the WSA.',counterparty=cp,counterparty_evidence='named',family='commercial',link_type='purchase_commitment',stage='signed',event_type='amendment',event_date='2019-01-29',instrument_key='AMD_GF_WSA',model_quantity='wafer_supply_agreement_amendment',flag_unknown_reason='date_conflicts_with_January_28_in_Q1_note_commercial_not_financial_covenant_event'),
dict(quote='If we do not meet the annual wafer purchase target for any of these years, we will be required to pay to GF a portion of the difference between our actual wafer purchases and the wafer purchase target for that year.',counterparty=cp,counterparty_evidence='named',payer='AMD',receiver=cp,family='commercial',link_type='purchase_commitment',stage='signed',conditionality='conditional',trigger_description='If we do not meet the annual wafer purchase target for any of these years',trigger_occurred='unknown',instrument_key='AMD_GF_WSA',model_quantity='conditional_wafer_purchase_shortfall_payment',flag_unknown_reason='target_portion_cap_and_triggered_amount_not_disclosed'),
m('Our total purchases from GF related to wafer manufacturing and research and development activities were approximately $1.6 billion in fiscal 2018.','1.6','1000000000',cp,period_start='2017-12-31',period_end='2018-12-29',payer='AMD',receiver=cp,family='commercial',link_type='purchase',stage='delivered',instrument_key='AMD_GF_WSA',model_quantity='related_supplier_purchases',amount_nature='supplier_wafer_and_R_and_D_purchases_not_explicit_cash_or_supplier_GAAP_revenue')]
save('5168b937dccbdff105c54eb084183501cab1d3673f01fdc9860096d42a02804a',rows)
