from authored_helpers import save,abstention as a,money as m
fy=dict(period_start='2021-06-01',period_end='2022-05-31')
sales=[
('Annapurna Releasing LLC','433000','1','Annapurna Releasing LLC purchased approximately $433,000 in cloud SaaS products.'),
('Autonomous Medical Devices, Inc.','1.0','1000000','Autonomous Medical Devices, Inc. purchased approximately $1.0 million in cloud SaaS, PaaS and IaaS products.'),
('Ellison Institute, LLC','847000','1','Ellison Institute, LLC purchased approximately $847,000 in cloud SaaS, PaaS and IaaS products.'),
('Four Seasons Resorts Lanai','432000','1','Four Seasons Resorts Lanai purchased approximately $432,000 in cloud SaaS products, software licenses, training and / support.'),
('Sensei AG Holdings, Inc.','465000','1','Sensei AG Holdings, Inc. purchased approximately $465,000 in cloud SaaS products, training and support.'),
('Skydance Media','192000','1','Skydance Media purchased approximately $192,000 in cloud PaaS and IaaS products.'),
('The Ronin Project','148000','1','The Ronin Project purchased approximately $148,000 in cloud PaaS and IaaS products.')]
rows=[m(q,n,s,cp,**fy,payer=cp,receiver='Oracle',family='commercial',link_type='purchase',stage='delivered',amount_nature='related_customer_purchases_not_explicit_GAAP_revenue_or_cash',model_quantity='related_customer_purchases',instrument_key='ORCL_fiscal_2022_related_customer_purchases',flag_unknown_reason='legal_entity_pending_where_trade_name_only_no_Oracle_financing_inferred') for cp,n,s,q in sales]
rows += [
m('In fiscal 2022, the total amount of all purchases by these companies was approximately $3.8 million.','3.8','1000000','companies related to Mr. Ellison',**fy,counterparty_evidence='anonymous',amount_nature='aggregate_related_customer_purchases_includes_named_components_not_additive',model_quantity='related_customer_purchases_total',instrument_key='ORCL_fiscal_2022_related_customer_purchases'),
m('In fiscal 2022, the total amount of all purchases from these companies was approximately $461,000, which included the purchase of products and services of approximately $219,000 from Desert Champions, LLC and approximately $223,000 from F50 League LLC.','461000','1','companies related to Mr. Ellison',**fy,counterparty_evidence='anonymous',amount_nature='aggregate_related_supplier_purchases_includes_named_components_not_additive',model_quantity='related_supplier_purchases_total'),
dict(quote='Under this agreement, if we present Mr. Ellison with reasonable evidence of a lower price or rate for the same goods or services offered by the related company, which would have been available to us at the time we entered into the applicable transaction, then Mr. Ellison will reimburse us for the difference.',counterparty='Mr. Ellison',counterparty_evidence='named',payer='Mr. Ellison',receiver='Oracle',family='credit_support',link_type='guarantee',stage='signed',conditionality='conditional',trigger_description='if we present Mr. Ellison with reasonable evidence of a lower price or rate for the same goods or services offered by the related company, which would have been available to us at the time we entered into the applicable transaction',trigger_occurred='unknown',model_quantity='related_supplier_price_protection_reimbursement',flag_unknown_reason='cap_and_called_amount_not_disclosed_person_not_legal_entity'),
dict(quote='Total related person transaction revenues were approximately 0.01% of our total revenues and total related person operating expenses were approximately 0.1% of our total operating expenses in fiscal 2022.',amount='0.01',unit='percent',amount_origin='narrative_only',amount_qualifier='approximately',**fy,amount_nature='related_person_revenue_percent_not_financed_customer_revenue_share',model_quantity='related_person_revenue_percent',counterparty_evidence='anonymous',flag_unknown_reason='all_related_person_transactions_not_E2_financed_customer_category'),
dict(quote='Total related person transaction revenues were approximately 0.01% of our total revenues and total related person operating expenses were approximately 0.1% of our total operating expenses in fiscal 2022.',amount='0.1',unit='percent',amount_origin='narrative_only',amount_qualifier='approximately',**fy,amount_nature='related_person_operating_expense_percent',model_quantity='related_person_operating_expense_percent',counterparty_evidence='anonymous'),
m('In fiscal 2022, Oracle paid Desert Champions, LLC, approximately $219,000 for tickets to the BNP Paribas Open tennis tournament and for expenses associated with this event.','219000','1','Desert Champions, LLC',**fy,payer='Oracle',receiver='Desert Champions, LLC',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_nature='tennis_tournament_tickets_and_expenses_cash_payments',model_quantity='related_supplier_cash_payments',flag_unknown_reason='comma_variant_not_merged_without_alias_evidence'),
dict(quote='In fiscal 2022, Oracle entered into an agreement providing for an in-kind exchange with the SailGP sailing league (operated by Mr. Ellison’s company F50 League LLC).',counterparty='F50 League LLC',counterparty_evidence='named',family='commercial',link_type='purchase',stage='signed',model_quantity='in_kind_sponsorship_exchange',issuer_treatment='in_kind_exchange',issuer_treatment_quote='In fiscal 2022, Oracle entered into an agreement providing for an in-kind exchange with the SailGP sailing league (operated by Mr. Ellison’s company F50 League LLC).',flag_unknown_reason='no_explicit_GAAP_revenue_or_contra_revenue_treatment'),
m('Pursuant to the agreement, Oracle received a SailGP sponsorship package, including branding rights and customer experiences, valued at approximately $2.5 million; and SailGP received Oracle products and services valued at approximately $2.3 million.','2.5','1000000','SailGP',**fy,payer='Oracle',receiver='SailGP',family='commercial',link_type='purchase',stage='delivered',amount_nature='received_sponsorship_package_value_not_cash',model_quantity='noncash_sponsorship_value',instrument_key='ORCL_F50_SailGP_sponsorship',flag_unknown_reason='legal_recipient_pending_no_explicit_contra_revenue_accounting'),
m('Pursuant to the agreement, Oracle received a SailGP sponsorship package, including branding rights and customer experiences, valued at approximately $2.5 million; and SailGP received Oracle products and services valued at approximately $2.3 million.','2.3','1000000','SailGP',**fy,payer='SailGP',receiver='Oracle',family='commercial',link_type='purchase',stage='delivered',amount_nature='provided_Oracle_products_services_value_not_cash',model_quantity='noncash_product_service_value',instrument_key='ORCL_F50_SailGP_sponsorship',flag_unknown_reason='commercial_orientation_customer_to_supplier_no_explicit_GAAP_revenue'),
m('In fiscal 2022, Oracle also paid F50 League LLC approximately $160,000 for hospitality tickets to a SailGP tournament race and approximately $63,000 to sponsor a video series with SailGP and pay other related fees.','160000','1','F50 League LLC',**fy,payer='Oracle',receiver='F50 League LLC',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_nature='hospitality_tickets_cash_payments',model_quantity='related_supplier_cash_payments'),
m('In fiscal 2022, Oracle also paid F50 League LLC approximately $160,000 for hospitality tickets to a SailGP tournament race and approximately $63,000 to sponsor a video series with SailGP and pay other related fees.','63000','1','F50 League LLC',**fy,payer='Oracle',receiver='F50 League LLC',family='commercial',link_type='purchase',stage='drawn_or_paid',event_type='payment',amount_nature='video_series_sponsorship_and_other_fees_cash_payments',model_quantity='related_supplier_cash_payments'),
dict(quote='Oracle is an equity investor in Ampere Computing LLC (Ampere).',counterparty='Ampere Computing LLC',counterparty_evidence='named',model_quantity='equity_investment_relationship',flag_unknown_reason='holding_amount_and_primary_vs_secondary_origin_not_disclosed'),
dict(quote='Under certain circumstances, Oracle has the obligation to acquire additional equity of Ampere from the other equity holders of Ampere.',counterparty='Ampere Computing LLC',counterparty_evidence='named',model_quantity='conditional_secondary_equity_acquisition',stage='signed',conditionality='conditional',trigger_description='Under certain circumstances',trigger_occurred='unknown',flag_unknown_reason='specific_circumstances_cap_and_called_amount_not_disclosed_secondary_not_primary_funding'),
m('In fiscal 2022, we invested $300 million in convertible debt issued by Ampere and also acquired an additional equity interest in Ampere from another investor for approximately $127.8 million.','300','1000000','Ampere Computing LLC',**fy,payer='Oracle',receiver='Ampere',amount_qualifier='exact',family='financing',link_type='convertible_or_safe',stage='recognized',event_type='funding',amount_nature='convertible_debt_investment_not_explicit_cash_or_current_stock',model_quantity='convertible_debt_funding',instrument_key='ORCL_Ampere_fiscal_2022_convertible_debt',flag_unknown_reason='cash_form_and_individual_payment_dates_not_disclosed'),
m('In fiscal 2022, we invested $300 million in convertible debt issued by Ampere and also acquired an additional equity interest in Ampere from another investor for approximately $127.8 million.','127.8','1000000','Ampere Computing LLC',**fy,payer='Oracle',receiver='another investor',counterparty_evidence='anonymous',stage='recognized',event_type='secondary_purchase',amount_nature='secondary_equity_purchase_not_primary_funding_to_Ampere',model_quantity='secondary_equity_purchase',flag_unknown_reason='seller_identity_and_cash_form_not_disclosed'),
m('In fiscal 2022, Ampere purchased approximately $613,000 in cloud SaaS, PaaS and IaaS products from Oracle.','613000','1','Ampere Computing LLC',**fy,payer='Ampere',receiver='Oracle',family='commercial',link_type='purchase',stage='delivered',amount_nature='customer_purchases_not_explicit_GAAP_revenue_or_cash_receipts',model_quantity='related_customer_purchases'),
m('Oracle purchased Ampere processors in fiscal 2022 with a value of $50.9 million, including $21.6 million against a $25 million pre-payment order placed in fiscal 2020.','50.9','1000000','Ampere Computing LLC',**fy,payer='Oracle',receiver='Ampere',amount_qualifier='exact',family='commercial',link_type='purchase',stage='delivered',amount_nature='processor_purchase_value_including_prepayment_application_not_cash',model_quantity='processor_purchases',instrument_key='ORCL_Ampere_fiscal_2020_processor_prepayment'),
m('Oracle purchased Ampere processors in fiscal 2022 with a value of $50.9 million, including $21.6 million against a $25 million pre-payment order placed in fiscal 2020.','21.6','1000000','Ampere Computing LLC',**fy,payer='Oracle',receiver='Ampere',amount_qualifier='exact',family='commercial',link_type='purchase',stage='delivered',amount_nature='prepayment_application_component_not_additive_to_processor_purchases',model_quantity='processor_prepayment_application',instrument_key='ORCL_Ampere_fiscal_2020_processor_prepayment'),
m('Oracle purchased Ampere processors in fiscal 2022 with a value of $50.9 million, including $21.6 million against a $25 million pre-payment order placed in fiscal 2020.','25','1000000','Ampere Computing LLC',period_start='2019-06-01',period_end='2020-05-31',payer='Oracle',receiver='Ampere',amount_qualifier='exact',family='commercial',link_type='prepayment',stage='signed',amount_nature='historical_processor_prepayment_order_not_current_cash',model_quantity='processor_prepayment_order',instrument_key='ORCL_Ampere_fiscal_2020_processor_prepayment'),
a('Steven Janicki, Vice President, Oracle IT Communications and Collaboration, is Mr. Ellison’s half-brother.','employee_compensation_outside_counterparty_financing_and_commercial_exposure')]
save('f6e081e8d1740e66778ec5e7dfff8f0578e12182eb8fc0d7e9490dc3ee428dd4',rows)
