from work.authored_helpers import *

for key,end,quote,reason in [
 ('8bd24abfd0bbfa5f05cf3d70fabeb9c61bf7fb2de679ef2f4359efdaa92dfbd7',7685,'DATED AS OF NOVEMBER 5, 2018','BofA administrative and Deutsche syndication agents, BofA/Deutsche/BMO/Barclays/BNP/Citi/HSBC/JPM/Mizuho/MUFG/RBC/Scotia/SG/SMBC/Wells arrangers identified financial. RBC explicitly brand, not legal alias. Unknown lenders and LC issuers unresolved, no identified outside nonfinancial financer. Original agreement not autonomous amendment. Same Item21657005 and6c9376b7 fully read: actual18bn term9+9 versus5bn RCF capacity,500mLC included and explicit zero RCF draw. CorpCA/CaymanFinance/PteLtdSG explicitly guarantors, not aliases for CorpDE. Proposed950mVeracode sale subject to closing conditions, no actual proceeds. Interestcoverage3x covenant threshold not actual breach.'),
 ('ca0aaa6df173d20db600cd100ab7e9ef62309c0fdef56b23a5becd3f6184c0be',2240,'Dated as of June 22, 2018','USBankNationalAssociation financial trustee; anonymous Holders not presumed all financial. Full ordered body0of9 read solely to assess parties: generic Holder and Depositary definitions, no identified actual outside nonfinancial holder. Remaining body1-8 unread. Original indenture, no3.03 or autonomous supplement trigger. Same Iteme1f444b1 fully read: actual1bn issuance500+500 and expected988.7m net not additive, not actual cash uses. Conditional101percent special redemption if Cavium not closed byMarch31,19 and changeofcontrol ratings trigger do not establish actual event/default.')
]:
 save(key,[dict(abstention(quote,'Complete physical header personally read. '+reason+f' Entire body{end}:rawend financialparty excluded, including any scope-only packet read; no body amount,link,covenant,F4 or legal alias admitted.'),model_quantity='exhibit_body_excluded_financial_parties_only',raw_byte_start=0,raw_byte_end=end,locator=f'rawbytes:0:{end}')])

save('66252d3c0de3c215745da4e9fa85927ae151e4c0037acd333025e567d6ad75b5',[
 abstention('MARVELL SEVERANCE AGREEMENT','Complete header and entire one ordered body packet personally read, all six physical pages including signatures. WillemMeintjes and MarvellSemiconductorInc signedDecember9,2016; later filedJune29,2018, not signedJune2018. Twelve months salary and twelve months COBRA are conditional employee severance, no actual termination, payout or fundedcustomer link. Sixty-day release and six-month409A delay conditions not actual event. January1,2022 or later completion conditional expiration not finance capacity termination. Generic future waiver clause and successor obligation not autonomous financial amendmentF4. Same Item41c83610 fully read: Cavium Chinese approval but closing still conditional, dividend announced not proofactualpaid. No guarantee call or financial funding established.')
])
