from work.authored_helpers import *
k='7acf692e16f68389cac29d1364e8bd38e8d6b971abc37f96a28a8f4256d1bd68'
rows=[dict(quote='The condensed consolidated financial statements include the accounts of Meta Platforms, Inc., its subsidiaries where we have controlling financial interests, and any variable interest entities for which we are deemed to be the primary beneficiary.',model_quantity='consolidation_scope'),dict(quote='All intercompany balances and transactions have been eliminated.',model_quantity='intercompany_elimination'),dict(quote='we extended the estimated average useful lives of a majority of the servers and network assets from four years to 4.5 years, effective the second quarter of 2022,',model_quantity='server_network_life_extension_not_F7',flag_unknown_reason='Q22022_effective_no_exact_day_not_later_Q4_five_year_change'),dict(quote='The impact from the change in our estimates was calculated based on the servers and network assets existing as of the effective date of the change and applying the revised estimated useful lives prospectively.',model_quantity='life_change_existing_assets_prospective_cohort'),dict(quote='On January 1, 2022, we early adopted Accounting Standards Update (ASU) No. 2021-08,',model_quantity='ASU2021_08_adopted',event_date='2022-01-01',recast_cause='accounting_change',flag_unknown_reason='no_material_impact_not_exact_zero'),dict(quote='On July 1, 2022, we early adopted ASU No. 2022-03,',model_quantity='ASU2022_03_adopted',event_date='2022-07-01',recast_cause='accounting_change',flag_unknown_reason='no_material_impact_not_exact_zero'),abstention('This guidance will be effective for our annual financial statements for the year ended December 31, 2022.','Government-assistance standard not yet adopted in this filing; complete note no explicit substantial doubt. Future impairment expectations not actual investment impairment or capacity termination Item1.02.')]
q='The financial impact of this change in estimate was a reduction in depreciation expense of $482 million and an increase in net income of $394 million,'
rows += [authored_tagged(k,'6ef80aa9517430a54cc2fc941e32a972ef764da14bdd84da80eb39773771f84f',q,model_quantity='depreciation_life_change_expense_effect',amount_nature='negative_expense_change_positive_pretax_effect_invert_sign',flag_unknown_reason='YTD2022_existing_assets_at_effective_Q2_date'),authored_tagged(k,'e099c44d26e8230f622f097dbf1827e719cb3f7758320c2c92b366bf83768c9a',q,model_quantity='life_change_net_income_effect',amount_nature='after_tax_not_pretax_bridge',flag_unknown_reason='YTD2022_existing_assets_at_effective_Q2_date'),authored_tagged(k,'ffe3dcfee01ff587a17144f7acc2834db884c28e621d1dab5361aa905e4626ea','we recorded an impairment loss of $413 million for operating lease ROU assets and leasehold improvements.',model_quantity='operating_lease_and_leasehold_impairment',stage='recognized',amount_nature='combined_asset_impairment_non_cash_not_investment_F6',flag_unknown_reason='office_restructuring_not_Item1_02_capacity_termination')]
save(k,rows)
k='4cf80919067a28b144c85e058c7bc8dbbab690fb9ab252bab8a6d874e3ca4852'
save(k,[authored_control(k,'our CEO and CFO have concluded that as of September 30, 2022, our disclosure controls and procedures are designed at a reasonable assurance level and are effective','disclosure_controls_effective',event_present=True),authored_control(k,'There were no changes in our internal control over financial reporting identified in management\'s evaluation','no_material_ICFR_change_quarter',flag_unknown_reason='nochange_and_generic_limits_not_F5_absence')])
k='9aca7ea4d35ac06442aa416cc93afe576d87a0cf5d83f6b5d3a010f3e216fc0b'
save(k,[dict(quote='In 2015, we implemented a holding company reorganization, and as a result, Alphabet Inc. ("Alphabet") became the successor issuer to Google.',model_quantity='Alphabet_successor_issuer_year',flag_unknown_reason='year_only_no_exact_date_from_this_clause'),dict(quote='The consolidated financial statements of Alphabet include the accounts of Alphabet and entities consolidated under the variable interest and voting models.',model_quantity='consolidation_scope'),dict(quote='All intercompany balances and transactions have been eliminated.',model_quantity='intercompany_elimination'),authored_tagged(k,'c0101978f8546dbb7247c40acb598f193df1fc0fd840e6d8ba48f2e560622bff','On February 1, 2022, the company announced that the Board of Directors had approved and declared a 20-for-one stock split',model_quantity='stock_split_ratio_approved',event_date='2022-02-01',flag_unknown_reason='approval_not_execution_date'),dict(quote='The Stock Split had a record date of July 1, 2022 and an effective date of July 15, 2022.',model_quantity='stock_split_effective_date',event_date='2022-07-15',flag_unknown_reason='record_date_distinct_from_execution'),dict(quote='All prior period references made to share or per share amounts in the accompanying consolidated financial statements and applicable disclosures have been retroactively adjusted to reflect the effects of the Stock Split.',model_quantity='share_split_retroactive_presentation',basis_break=True,recast_cause='presentation_reclassification',flag_unknown_reason='share_per_share_only_not_operating_cash_totals'),abstention('Actual results could differ materially from these estimates.','Complete note no explicit substantial doubt or actual useful life change; no later 2023 assessment imported.')])
