from work.authored_helpers import *
save('f0b5cb0f07046371e3ca1ca2463883e2a322d01b0764de1e3ad2ce52924e71c2',[abstention('declared the payment of its quarterly dividend of $0.06 per share','Full item read including Bermuda law and dividend conditions. Dec2announcement not declaration day, futureJan14/recordDec23not actual aggregate payout or funding/distress.')])
k='f705fff2768a0364cd2ea3784900a5a6357f210b24220a17d06035de7a9bc738'
rows=[dict(quote='On October 29, 2020, Marvell Technology Group Ltd. (“Marvell”) entered into an Agreement and Plan of Merger and Reorganization',counterparty='Inphi Corporation',counterparty_evidence='named',stage='signed',event_date='2020-10-29',model_quantity='Inphi_merger_agreement_signed',flag_unknown_reason='pending_conditional_mergers_oneforone_Marvell_and2_323HoldCo_plus66cash_perInphi_share_not_aggregate_price_or_actual_payment'),dict(quote='Maui HoldCo, Inc., a Delaware corporation and a wholly owned subsidiary of Marvell (“HoldCo”), Maui Acquisition Company Ltd, a Bermuda exempted company and a wholly owned subsidiary of HoldCo (“Bermuda Merger Sub”), Indigo Acquisition Corp., a Delaware corporation and a wholly owned subsidiary of HoldCo',counterparty='Maui HoldCo, Inc.',counterparty_evidence='named',model_quantity='current_Maui_HoldCo_group_legal_identity',flag_unknown_reason='HoldCo_DE_wholly_Marvell_Bermuda_Maui_Acquisition_Bermuda_and_Indigo_DE_wholly_HoldCo_future_Marvell_Inphi_subsidiary_inversion_not_current_or_MTI_alias_proof')]
for quote,amount,payer,receiver,trigger,quantity in [
('a termination fee of $300 million','300','Inphi Corporation','Marvell Technology Group Ltd.','by Inphi in order to accept a Company Superior Offer (as defined in the Merger Agreement) and enter into a definitive agreement providing for consummation of the transaction contemplated by such Company Superior Offer.','conditional_Inphi_to_Marvell_break_fee'),
('$400 million if, among other things','400','Marvell Technology Group Ltd.','Inphi Corporation','by Marvell in order to accept a Disruptive Marvell Superior Offer (as defined in the Merger Agreement) and enter into a definitive agreement providing for consummation of the transaction contemplated by such Disruptive Marvell Superior Offer','conditional_Marvell_to_Inphi_superior_offer_fee'),
('$460 million if, among other things','460','Marvell Technology Group Ltd.','Inphi Corporation','(A) the Merger Agreement is terminated by Marvell or Inphi because the Mergers have not been consummated (1) on or prior to the Outside Date or (2) as a result of a suit or legal proceeding brought by certain specified governmental authorities and (B) as of the time of termination of the Merger Agreement, a Designated Circumstance (as defined in the Merger Agreements) exists and all of Marvell’s closing conditions (other than closing conditions related to the Designated Circumstance) have been satisfied.','conditional_Marvell_to_Inphi_designated_circumstance_fee')]:
 rows.append(money(quote,amount,'1000000',receiver if payer=='Marvell Technology Group Ltd.' else payer,payer=payer,receiver=receiver,stage='signed',event_date='2020-10-29',model_quantity=quantity,amount_qualifier='exact',amount_nature='conditional_termination_fee_not_called_cash_or_acquisition_price',trigger_description=trigger,flag_unknown_reason='selected_explicit_trigger_other_alternatives_in_full_source_fees_without_duplication_actual_trigger_and_payment_unknown'))
for quote,amount,scale,quantity in [('a $2.5 billion senior 364-day bridge term loan facility','2.5','1000000000','bridge_commitment'),('a $1.5 billion senior unsecured term loan facility','1.5','1000000000','term_commitment'),('a $750.0 million 3-year term loan tranche','750','1000000','term_three_year_component'),('a $750.0 million 5-year term loan tranche','750','1000000','term_five_year_component'),('$100.0 million under a revolving credit facility to be entered into','100','1000000','JPMorgan_revolver_component_committed')]:
 rows.append(money(quote,amount,scale,'JPMorgan Chase Bank, N.A.',payer='JPMorgan Chase Bank, N.A.',receiver='Marvell Technology Group Ltd.',stage='signed',event_date='2020-10-29',family='financing',link_type='loan_or_facility',model_quantity=quantity,amount_qualifier='exact',amount_nature='conditional_financing_commitment_not_drawn_cash_components_not_additive',flag_unknown_reason='future_documentation_and_merger_conditions_revolver100m_is_component_not_total750_actual_funding_date_and_borrower_reorganization_unknown_bridge_reductions_overlap_permanent_financing'))
rows.extend([money('in an aggregate committed amount of up to $750.0 million','750','1000000','prospective_revolver_lenders',counterparty_evidence='anonymous',stage='intent_non_binding',model_quantity='prospective_revolver_total_limit',amount_qualifier='up_to',amount_nature='planned_total_revolver_of_which_JPMorgan100_committed_not_actual_total_committed_or_new_cash'),abstention('The actual documentation governing the Bridge Facility, the Term Loan Facility and the Revolving Facility has not been finalized','Full entire item read including representations/fee alternatives/loan commitments/bridge reductions and all additional-info/participants/cautions/no-offer. Original merger and financing not F4. Target-holder66per-share secondaryconsideration not targetprimarycash. No actual consolidation, draw, fees paid or guarantee call; original2.5+1.5commitments may be refinanced not added to later versions.')])
save(k,rows)
