from work.authored_helpers import *
rows=[dict(quote='the Company terminated all outstanding commitments and repaid all outstanding obligations',stage='settled',event_type='repayment',event_date='2021-01-19',model_quantity='old_credit_facilities_obligations_repaid_and_commitments_terminated',flag_unknown_reason='Closing_Date_Jan19_defined_in_personally_read_companion1_01_exact_total_cash_fees_interest_unknown_financial_credit_not_capacity_F9'),dict(quote='the Company had outstanding no borrowings under the May 2019 Credit Agreement',stage='recognized',event_date='2021-01-19',model_quantity='old_May2019_credit_explicitly_no_borrowings_before_termination',amount_nature='explicit_zero_nonnumeric_source_clause')]
for quote,amount,series in [('$1,818,750,000 in aggregate principal amount of loans under the term A-3 facility','1818750000','A3'),('$4,068,750,000 in aggregate principal amount of loans under the term A-5 facility','4068750000','A5')]:
 rows.append(money(quote,amount,'1','old_term_lenders',counterparty_evidence='anonymous',stage='settled',event_date='2021-01-19',period_end='2021-01-19',model_quantity='November2019_'+series+'_principal_extinguished',amount_qualifier='exact',amount_nature='immediately_prior_principal_repaid_not_total_cash_including_fees_interest'))
rows.append(abstention('The May 2019 Credit Agreement originally provided for a $5.0 billion unsecured revolving credit facility','Full item read. Old May19original5+2+2+2bn and Nov19original7.75+7.75bn limits not immediatelyprior debt or new cash; no sum with new7.5bncommitment. Actual repayment/financial-facility termination not F9capacity or F4 waiver/default; adminbank not all creditor allocation.'))
save('b6b719a9e13b51a25ed9c258c5addaac20b1c07a5d548991b36d5fe0145103a2',rows)
save('11ec023c4b69a4ce66a69dfc0b9cae394a49a6f0f58491e6f565833373116ac3',[
money('up to an aggregate purchase price, excluding accrued and unpaid interest, of $3.5 billion.','3.5','1000000000','existing_noteholders',counterparty_evidence='anonymous',stage='intent_non_binding',model_quantity='tender_offer_purchase_price_cap',amount_qualifier='up_to',amount_nature='offer_price_cap_excluding_interest_not_actual_purchase_price_or_principal'),abstention('announced the early results of its previously announced cash tender offers','Full item and cautions read. Jan19early-results announcement not actual quantified purchases/settlement/financial-clause amendment; seven issuer/series priorities no value allocation. Release not imported.')])
save('f620697e162283ccc4d7b39ba0c46a3d52d3b377eb7532dcac05a86d8b7133e8',[
abstention('Effective as of 11:59 p.m. EST on January 11, 2021, the waiting period under the HSR Act expired with respect to the Merger.','Full item, all cautions and signature read. Jan11HSR expiry but other approvals/shareholder conditions pending; no actual Xilinx acquisition or funding. HistoricalOct26signedagreement and current ThronesMergerSub whollyAMD not current Xilinx consolidation; laterJan2022HSR expiry is separately disclosed, not imported here.')])
