from work.authored_helpers import *
from work.authored_quarantines import record
record('D78','234b02e56ddf795954099a6c8d10998e0eee7e1c81f261785f3be2e97e5c5ea6','0001193125-21-123305',[], 'Deux lignes de garantie MTI–Inphi rejetées par SEM_CHECK : le bloc 3.03 ne contient que les alias MTI et Inphi, et non la contrepartie complète proposée Inphi Corporation. Rejets conservés, sans nouvel essai sémantique à cet as_of ; une éventuelle preuve de garantie d’une pièce indépendante reste distincte. Les amendements de conversion admis ne prouvent ni défaut ni paiement.')
save('fc7afa0416e80e355471bd198cdada34277c516aa406229ccdbb1617db8efe00',[abstention('The information set forth in Item 5.03 and Item 8.01 is incorporated by reference herein.','Entire short item read. Cross-reference alone no independently established modification; 8.01 read separately, 5.03 outside closed first pass not imported.')])
rows=[dict(quote='On April 20, 2021 (the “Merger Effective Date”), Marvell completed the previously announced acquisition of Inphi Corporation (“Inphi”)',counterparty='Inphi Corporation',counterparty_evidence='named',stage='settled',event_date='2021-04-20',model_quantity='inphi_merger_completed_perimeter_start',flag_unknown_reason='separate_Bermuda_Marvell_and_Delaware_Inphi_survive_as_wholly_MTI_at1601_and1602_ET_not_Marvell_rename_only'),dict(quote='Marvell and MTI funded the cash portion of the consideration for the Mergers with borrowings under the Term Credit Agreement and proceeds of the previously announced offering and issuance',stage='drawn_or_paid',event_date='2021-04-20',model_quantity='merger_cash_consideration_funded',flag_unknown_reason='actual_aggregate_cash_consideration_and_term_borrowing_amount_unknown_note_faces_not_net_cash_or_target_primary_funding')]
for quote,number,year in [('$500 million aggregate principal amount of 1.650% Senior Notes due 2026','500','2026'),('$750 million aggregate principal amount of 2.450% Senior Notes due 2028','750','2028'),('$750 million aggregate principal amount of 2.950% Senior Notes due 2031','750','2031')]:
 rows.append(money(quote,number,'1000000','note_investors',counterparty_evidence='anonymous',stage='recognized',model_quantity='prior_issued_merger_finance_notes_'+year,amount_qualifier='exact',amount_nature='previously_issued_note_face_not_new_Apr20_cash_or_total_acquisition_cost',flag_unknown_reason='original_issuance_date_not_stated_here_do_not_double_count_independent_note_issuance_block'))
rows.append(abstention('each share of common stock, $0.001 par value per share, of Inphi','Full item read:completed mergers, one-for-one Marvell to MTI shares and Inphi2.323MTI+66cash conversion rights; aggregate payment and target cash infusion unknown. Current Maui Bermuda/Indigo Delaware distinct; ticker futureApr21 not merger date. Registration/agreements not imported; no assumed company rename or historical group overwrite.'))
save('eebec76be3758cf61d0217ee11be3802d327134a6f0b2ac9e4669f676f763e31',rows)
save('d6eb8f654b5736e90136cbb16d59033dc4b0e88a2155b0071798089e32dfb385',[
dict(quote='On April 15, 2021, Marvell executed a Second Supplemental Indenture',stage='signed',event_date='2021-04-15',event_type='amendment',event_observable='F4',event_present=True,model_quantity='marvell_old_indentures_restrictive_covenants_removed_signed',flag_unknown_reason='operative_only_future_exchange_settlement_expected_May4_not_actual_breach_or_operativity_Apr15'),
dict(quote='Marvell Technology, Inc.’s, a Delaware corporation and Marvell’s wholly owned subsidiary (“MTI”)',counterparty='Marvell Technology, Inc.',counterparty_evidence='named',model_quantity='MTI_before_merger_legal_membership',flag_unknown_reason='current_Apr19_MTI_Delaware_wholly_Marvell_Technology_Group_Ltd_Bermuda_not_retroactive_post_Apr20_inverted_ownership'),
abstention('The Marvell Second Supplemental Indenture will become operative upon the settlement of the Exchange Offers','Full item read:Apr16consents86.47/95.34 percentages not face/cash; Apr15signed elimination covenant/merger/default clauses not actual Event of Default. Operative date conditional future here; separate second supplement to be fully read.')])
