from work.authored_helpers import *
k='35750ac40b5733551d062724a9115e86dd661b9bee97c93d3cb696c037a6319a'
rows=[]
for quote,num,q in [('$1,250,000,000 aggregate principal amount of its 4.700% notes due 2024','1250000000','2024'),('$1,250,000,000 aggregate principal amount of its 4.600% notes due 2025','1250000000','2025'),('$2,000,000,000 aggregate principal amount of its 4.550% notes due 2027','2000000000','2027'),('$1,500,000,000 aggregate principal amount of its 4.650% notes due 2029','1500000000','2029'),('$2,250,000,000 aggregate principal amount of its 4.700% notes due 2032','2250000000','2032')]:
 rows.append(money(quote,num,'1','several_underwriters',counterparty_evidence='anonymous',event_date='2022-12-01',stage='recognized',amount_qualifier='exact',model_quantity='notes_'+q+'_issued_face',amount_nature='issued_face_not_actual_net_cash'))
rows.extend([money('The aggregate public offering price of the Notes was $8.246 billion','8.246','1000000000','several_underwriters',counterparty_evidence='anonymous',event_date='2022-12-01',stage='recognized',amount_qualifier='exact',model_quantity='notes_public_offering_price_aggregate',amount_nature='public_price_not_face_or_final_cash_received'),money('the estimated net proceeds from the offering were approximately $8.235 billion','8.235','1000000000','several_underwriters',counterparty_evidence='anonymous',event_date='2022-12-01',stage='recognized',amount_qualifier='approximately',model_quantity='notes_estimated_net_after_discount_before_expenses',amount_nature='estimated_net_not_final_actual_cash',flag_unknown_reason='after_underwriting_discounts_before_other_offering_expenses_nonadditive_to_face_public_price'),abstention('pursuant to an Underwriting Agreement dated November 29, 2022','Full item: completed sale/five series, underwriting/date/four managers, registration, aggregate public price/estimated net qualifiers, base/prior/successor trustee/supplement/date/officers certificate and all form/exhibit renvois read. No final net cash, security/guarantee status, actual repayment/default/waiver/call; trustee replacement/officers certificate original new-series terms not F4. Managers not each all funding.')])
save(k,rows)
save('efeb9ef54526acc9318e9205e2778653877aa172ba456da738e0e610c5880961',[money('a borrowing capacity of up to $10.0 billion.','10.0','1000000000','364_day_revolving_lenders',counterparty_evidence='anonymous',event_date='2022-11-18',stage='available',amount_qualifier='up_to',family='financing',link_type='loan_or_facility',model_quantity='364_day_unsecured_revolver_limit',amount_nature='available_unsecured_limit_not_cash_drawn'),dict(quote='but does not contain financial covenants.',model_quantity='revolver_explicit_no_financial_covenants'),abstention('JPMorgan Chase Bank, N.A., as administrative agent','Full item: signed facility/364dayterm/optional extension, SOFRspread/undrawn fee, planned CPbackstop, explicit no financial covenants and conditional default acceleration/termination, complete institution-service relationships/exhibit read. No actual draws/principal/zero outstanding proof or extension exercised/default/waiver/call. SOFR Secured name not debt security; agent not full funding allocation. Later replacement not imported.')])
k='c0af95f99f0669c5df7017a29ce38419257855f3a5d7f61b3c74f053412f0a91'
rows=[money('Issuance of $7 Billion Aggregate Principal Amount of Notes','7','1000000000','unidentified_noteholders',counterparty_evidence='anonymous',event_date='2022-11-09',stage='recognized',amount_qualifier='exact',model_quantity='notes_issued_face_aggregate',amount_nature='issued_face_not_net_cash_components_nonadditive')]
for quote,num,q in [('$1,000,000,000 aggregate principal amount of its 5.800% Notes due 2025','1000000000','2025'),('$1,250,000,000 aggregate principal amount of its 6.150% Notes due 2029','1250000000','2029'),('$2,250,000,000 aggregate principal amount of its 6.250% Notes due 2032','2250000000','2032'),('$2,500,000,000 aggregate principal amount of its 6.900% Notes due 2052','2500000000','2052')]:
 rows.append(money(quote,num,'1','unidentified_noteholders',counterparty_evidence='anonymous',event_date='2022-11-09',stage='recognized',amount_qualifier='exact',model_quantity='notes_'+q+'_issued_face',amount_nature='component_of_aggregate_face_not_net_cash'))
rows.extend([money('On November 2, 2022, Oracle upsized the commitments under its term loan credit agreement and borrowed an additional $1.3 billion.','1.3','1000000000','term_loan_lenders',counterparty_evidence='anonymous',event_date='2022-11-02',stage='drawn_or_paid',amount_qualifier='exact',model_quantity='term_loan_additional_actual_borrowing',amount_nature='actual_additional_borrowing_not_total_limit_or_net_proceeds',flag_unknown_reason='commitment_upsize_not_explicit_financial_clause_amendment_may_be_existing_accordion_no_automatic_F4'),money('Oracle used the net proceeds thereof to prepay $1.3 billion of borrowings under the DDTL.','1.3','1000000000','DDTL_lenders',counterparty_evidence='anonymous',event_date='2022-11-02',stage='drawn_or_paid',amount_qualifier='exact',model_quantity='DDTL_actual_principal_prepayment_from_term_borrowing',amount_nature='actual_old_loan_principal_prepayment_not_new_financing_cash_inflow',flag_unknown_reason='inflow_and_outflow_linked_not_additive_one_exposure_total'),dict(quote='Oracle (formerly known as Ozark Holding Inc.), Oracle Systems Corporation (formerly known as Oracle Corporation)',model_quantity='current_and_legacy_Oracle_legal_names_distinct',flag_unknown_reason='different_legal_persons_not_alias_merge_dates_unknown'),abstention('Oracle intends to use the net cash proceeds of the offering to prepay borrowings under its March 2022 delayed draw term loan credit agreement','Full item: actualNov9note sale/four series/underwriting/indenture/names/registrations/planned DDTLprepay/exhibits, separate actualNov2term-loan borrowing1.3 and linked DDTLprepay1.3 read. New notes face not net cash; plannedNov9use not actual cash payoff. No assumed total facility upsize or covenant amendment from borrowing/accordion alone, security/guarantee proof/default/call. Trustee/representatives not each full payer.')])
save(k,rows)
