from work.authored_helpers import *
from work.authored_quarantines import record
k='45cb6c049a423e37deabecc1f7a71c5a63f202bab417cf44ef0f0a78c311579b'
record('D77',k,'0001193125-22-171108',[], 'AMD notes 2052 : le texte fixe l’échéance au 1er juin 2052 mais la date de par call au 1er décembre 2052, dite six mois avant l’échéance. Ces indications sont incompatibles ; aucune correction implicite vers décembre 2051. L’échéance littérale et le conflit de par call restent tracés, tout calcul de fenêtre de remboursement 2052 dépendant de la date contradictoire est indéterminé. Aucun remboursement effectif n’est publié ici.')
for key,date,stage in [(k,'2022-06-09','recognized'),('9c310f9def44feb30959776173181714be1d037ecc3910a92aaac947cf323284','2022-06-07','signed')]:
 rows=[]
 for quote,num,scale,q in [('$1 billion aggregate principal amount of senior notes','1','1000000000','aggregate'),('$500 million aggregate principal amount of its 3.924% Senior Notes due 2032','500','1000000','2032'),('$500 million aggregate principal amount of its 4.393% Senior Notes due 2052','500','1000000','2052')]:
  rows.append(money(quote,num,scale,'several_underwriters_or_noteholders',counterparty_evidence='anonymous',event_date=date,stage=stage,amount_qualifier='exact',model_quantity='notes_'+q+'_'+('issued_face' if stage=='recognized' else 'underwritten_face'),amount_nature='face_not_net_cash_components_nonadditive',flag_unknown_reason='same_offering_signed_then_closed_not_second_flow'))
 if key==k:
  rows.extend([dict(quote='The 2032 Notes mature on June 1, 2032 and bear interest at a rate of 3.924% per annum and the 2052 Notes mature on June 1, 2052',model_quantity='notes_contractual_maturities',flag_unknown_reason='2052_par_call_Dec1_2052_described_six_months_prior_conflicts_no_silent_Dec2051_repair'),dict(quote='December 1, 2052 (the date that is six months prior to the maturity date of the 2052 Notes)',model_quantity='notes_2052_par_call_relative_date_conflict',flag_unknown_reason='literal_after_June1_2052_maturity_not_six_months_prior_dependent_redemption_window_unknown'),abstention('The Notes are the Company’s general unsecured senior obligations.','Full item: completedJune9offering, both faces/maturities/unsecurity, entire optional redemption/makewhole/parcall including literal2052date contradiction, conditional101%changeofcontrolput, all covenant limitations/exceptions and original default/grace/insolvency clauses, registrations and exhibits read. No net cash or actual redemption/default/F4original indenture/guarantee call; trustee not payer.')])
 else:
  rows.append(abstention('The Offering is expected to close on June 9, 2022, subject to the satisfaction of customary closing conditions.','Full item:June7signed underwriting/five representatives/two series/security/maturities, customary conditions/indemnities, expectedJune9closing/plannedgeneral use, registration/prospectus/exhibit read. No actual close/cash/repayment/default/financial waiver; laterJune9not imported. Representatives not each funded total.'))
 save(key,rows)
save('6fbd8c0c493dbbc9c88c1b814abeb56889e2cbfd761b4d3dfbb2a473ddfce186',[abstention('On June 7, 2022, the Company issued a press release announcing the pricing of the Offering.','Full item:June7launch/pricing references, complete forward-looking close/use/outcome/market risk/disclaimer read. No amount in this item, actual issuance/cash/repayment/default/waiver/call; release bodies and later close not imported.')])
