from work.authored_helpers import *

for key,end,quote,reason in [
 ('3ed249dff0047d32f7de4c6fe4a21b3ce757616c81a2f94a431ad246cf602833',6724,'dated as of June 7, 2019','WellsFargoBankNA administrative agent and WellsSecurities/BofASecurities/JPM named financial arrangers. Same Itemdd27ae96 and77dc5637 fully reread:500mRCF cap,50m swingline and75mLC included, explicit zero borrowings June7. Actual old2015facility repaid/terminated but amount ND. AMDISS future subsidiaries internal, no identified actual outside nonfinancial lender; unnamed lenders pending, not allbank aliases. Original credit not autonomous amendment; covenant thresholds4x/3x and guarantee release conditions not actual breach or guarantee call.'),
 ('9423b28023c0b7f3450caaf79f6aa8ddda8cbf71e164c7950924f92119209681',11662,'DATED AS OF MAY 7, 2019','Named agents and arrangers BofA/JPM/Deutsche/BMO/Barclays/BNP/Citi/HSBC/Mizuho/MUFG/RBC/Scotia/SMBC/Wells/ANZ/Commerz/DBS/SunTrust/TD financial; RBC CapitalMarkets explicitly brand not legal alias. Unknown lenders pending, no identified actual outside nonfinancial lender. Same Iteme563c577/7e4c0bec fully reread actual6bn term made2+2+2 and5bnRCF cap with500mLC included and zeroRCF borrowing. Old6bn term repaid versus historical18bn capacity not cash. Guarantors CorpCA/TechDE/CaymanFinance explicitly Company subsidiaries; no retrospective CorporationDE alias. Original agreement not F4 or new capacity terminationF9.')
]:
 save(key,[dict(abstention(quote,'Complete physical header personally read. '+reason+f' Entire body{end}:rawend excluded UNREAD; no body amount,covenant,link,F4 or entityalias admitted.'),model_quantity='exhibit_body_excluded_financial_parties_only',raw_byte_start=0,raw_byte_end=end,locator=f'rawbytes:0:{end}')])

save('3e0f1548d12584d378ea6949ea72f564469574a5b041de50517acb148c339641',[
 abstention('ROBIN L. WASHINGTON','Header and entire one body packet (both physical pages) personally read; same Item8.01 3b7cd409 fully reread. Director service letter accepted April24, appointment effectiveApril25; initial1m equity grant, annual350kGSUs/75kcash conditional director compensation, not customer consideration, financing, actual cash payment or investment in Gilead/Honeywell/Salesforce. Biographical affiliations do not establish financial links. No autonomous amendment or actual F4 financial covenant event; vesting/service and stockownership conditions not actual violation.')
])
