from work.authored_helpers import *
save('1a90f7fe3cfc366714a1f6447580b4eb13b1754523916f34d8cf69563786a70b',[
dict(quote='On October 26, 2020, Advanced Micro Devices, Inc., a Delaware corporation (the “Company”), entered into an Agreement and Plan of Merger',counterparty='Xilinx, Inc.',counterparty_evidence='named',stage='signed',event_date='2020-10-26',model_quantity='Xilinx_merger_agreement_signed',flag_unknown_reason='AMD_Thrones_Merger_Sub_Inc_Xilinx_all_DE_current_Thrones_whollyAMD_future_Xilinx_survivor_not_current_consolidation_17234_share_ratio_not_aggregate_cash'),
money('Xilinx will be required to pay a termination fee to the Company equal to $1 billion','1','1000000000','Xilinx, Inc.',payer='Xilinx, Inc.',receiver='Advanced Micro Devices, Inc.',stage='signed',event_date='2020-10-26',model_quantity='conditional_Xilinx_to_AMD_break_fee',amount_qualifier='exact',amount_nature='conditional_fee_not_actual_cash_or_purchase_price',trigger_description='if the Merger Agreement is terminated because Xilinx’s board of directors has changed its recommendation.',flag_unknown_reason='selected_trigger_other_circumstances_not_fully_enumerated_no_actual_trigger_payment'),
money('The Company will be required to pay a termination fee to Xilinx equal to $1.5 billion','1.5','1000000000','Xilinx, Inc.',payer='Advanced Micro Devices, Inc.',receiver='Xilinx, Inc.',stage='signed',event_date='2020-10-26',model_quantity='conditional_AMD_to_Xilinx_recommendation_fee',amount_qualifier='exact',amount_nature='conditional_fee_not_actual_cash_or_purchase_price',trigger_description='if the Merger Agreement is terminated because the Company’s board of directors has changed its recommendation.',flag_unknown_reason='selected_trigger_other_circumstances_not_fully_enumerated_no_actual_trigger_payment'),
money('The Company will be required to pay a termination fee equal to $1 billion if the Merger Agreement is terminated in certain circumstances related to the failure to obtain required regulatory approvals prior to the Outside Date.','1','1000000000','Xilinx, Inc.',payer='Advanced Micro Devices, Inc.',stage='signed',event_date='2020-10-26',model_quantity='conditional_AMD_regulatory_failure_fee',amount_qualifier='exact',amount_nature='conditional_regulatory_fee_not_called_or_additive_to_other_fee',trigger_description='if the Merger Agreement is terminated in certain circumstances related to the failure to obtain required regulatory approvals prior to the Outside Date.',flag_unknown_reason='specific_circumstances_and_receiver_not_explicit_in_this_fee_clause_actual_trigger_unknown'),
abstention('following the issuance of any dividend in respect of the second quarter of Xilinx’s fiscal 2021 year, Xilinx is required to suspend its dividend','Full entire item read:consideration/RSUoptions/governance/allconditions/covenants/termination/qualifications. Contractualdividend suspension≥12monthsnot actual distress/capacityF9. Pendingmergernot actual acquisition/stockdelivery;66?nonehere no cross-merger import. Parvalues/exchange1.7234noncash not monetary consideration.')])
save('fd14f4847a0f3643248bb75e9b9a133a57d68fc86c8021e999fb00b8f9bdf058',[abstention('granted preliminary approval of the settlement of the stockholder derivative action','Full item read. Oct22preliminary court approval and resolution by stipulation, no quantified final liability/actual cash or investment impairment. Litigation/external Notice not imported.')])
save('e4589e97f5883e0b46fb27683de07c4767ccf1bdc14bb5918bb2bd37fa5850bb',[
dict(quote='Google LLC (“Google”), a wholly-owned subsidiary of Alphabet Inc.',counterparty='Google LLC',counterparty_evidence='named',model_quantity='Google_LLC_legal_current_group_membership',flag_unknown_reason='full_legal_names_current_wholly_owned_not_brand_or_exact_legal_start_date'),abstention('filed an antitrust complaint against Google','Full item and signature read. Oct20DOJ11states complaint, priorAug19demands and continuedinvestigations not final judgment/paid fine/investment impairment or funding.')])
