from extension_authoring import save,tagged
k='5304461260728b251da2dca00dba5ee9c88616c64db2b835ff4fcaba74cd2f80'
rows=[dict(quote='CoreWeave, Inc., the ultimate parent company, is not otherwise liable for such debt, except in cases where the Company provides limited guarantees under which recourse may arise only upon specified events, such as actual fraud, willful misconduct, misappropriation of collateral, certain voluntary or consented bankruptcy actions, or other customary non-recourse carve-out obligations.',model_quantity='nonrecourse_debt_parent_guarantee_scope',issuer_treatment='subsidiary_nonrecourse_with_limited_carveout_guarantees_not_general_parent_repayment_guarantee',flag_unknown_reason='carveout_trigger_occurrence_not_established'),dict(quote='As of June 30, 2026, the Company was in compliance with all covenants under its delayed draw term loan facility agreements.',model_quantity='debt_covenant_compliance',issuer_treatment='DDTL_covenants_compliant_at_report_date',flag_unknown_reason='future_conditional_events_not_actual_default'),dict(quote='These letters of credit remain outstanding, continue to secure the related lease obligations, and reduce availability under the senior secured revolving credit facility',model_quantity='revolver_letter_of_credit_availability_policy',issuer_treatment='lease_support_LCs_reduce_revolver_availability_not_additive_cash_draws'),dict(quote='The Company had entered into various agreements with original equipment manufacturers (the "OEM Financing Arrangements"), whereby the Company obtained financing for certain equipment.',model_quantity='OEM_financing_arrangements_counterparty_identity',counterparty_evidence='anonymous',flag_unknown_reason='OEMs_not_named_no_NVIDIA_or_other_supplier_attribution'),dict(quote='The Company also had entered into various arrangements with a software license vendor (the "Software License Financing Arrangements"), whereby the Company obtained financing for certain software licenses.',model_quantity='software_license_vendor_financing_identity',counterparty_evidence='anonymous',flag_unknown_reason='software_vendor_not_named_no_NVIDIA_or_other_supplier_attribution')]
rows.append(tagged(k,167,'In June 2026, the Company paid $100 million to MagAI Ventures in partial settlement of amounts outstanding under the MagAI Capacity Agreement, as amended.',counterparty='MagAI Ventures',counterparty_evidence='named',payer='CRWV',receiver='MagAI Ventures',model_quantity='capacity_deposit_debt_cash_settlement',amount_nature='cash_repayment_of_existing_debt_not_new_primary_financing_to_recipient',event_type='cash_payment',stage='settled',instrument_key='CRWV_MagAI_capacity_debt'))
rows.append(tagged(k,168,'The remaining obligation as of June 30, 2026 was $189 million, consisting of the unused refundable deposit amount, together with accrued redemption premiums through the reporting date.',counterparty='MagAI Ventures',counterparty_evidence='named',model_quantity='capacity_deposit_debt_outstanding',amount_nature='remaining_debt_stock_includes_accrued_redemption_premiums_not_cash_flow',block='recognized_liabilities',category_id='debt',measurement_basis='carrying_amount',stage='recognized',instrument_key='CRWV_MagAI_capacity_debt'))
rows.append(dict(quote="Accordingly, the notes were settled through the issuance of shares of the Company's Class A common stock",model_quantity='acquisition_promissory_notes_noncash_settlement',issuer_treatment='equity_settlement_not_cash_debt_repayment',flag_unknown_reason='former_acquiree_shareholders_unnamed'))
rows.append(dict(quote='The DCSP Note Receivable provides for a total commitment of up to $305 million in delayed draw term loan funding for a term of seven years with a stated interest rate of 13.00% per annum.',model_quantity='DCSP_lender_and_commitment_scope',issuer_treatment='CoreWeave_lends_to_anonymous_DCSP_not_receives_305m_financing',counterparty_evidence='anonymous',flag_unknown_reason='DCSP_unnamed_commitment_not_actual_draw_amount'))
q='As of June 30, 2026, the gross amount of the DCSP Note Receivable was $302 million, which is presented net of the financing obligation and finance lease of $230 million.'
rows.append(tagged(k,202,q,model_quantity='DCSP_gross_note_receivable',amount_nature='gross_loan_asset_stock_not_incremental_cash_funding',block='exposed_assets',measurement_basis='gross_receivable',instrument_key='CRWV_anonymous_DCSP_arrangement'))
rows.append(tagged(k,203,q,model_quantity='DCSP_financing_obligation_and_finance_lease_stock',amount_nature='gross_combined_financing_and_lease_liabilities_offset_against_note_not_additive_to_components',block='recognized_liabilities',measurement_basis='gross_combined_liability',instrument_key='CRWV_anonymous_DCSP_arrangement'))
rows.append(dict(quote='The DCSP Financing Arrangements allow for the net settlement of amounts due between the parties and meet the criteria for right of setoff in accordance with ASC 210, Balance Sheet.',model_quantity='DCSP_receivable_obligation_offset_policy',issuer_treatment='issuer_right_of_setoff_under_ASC210',instrument_key='CRWV_anonymous_DCSP_arrangement'))
rows.append(dict(quote='Under the terms of the DCSP Service Agreement, the Company continues to control the Existing Critical Infrastructure Assets and the Company recorded a financing obligation related to the consideration received for the Existing Critical Infrastructure Assets.',model_quantity='DCSP_controlled_asset_financing_accounting',issuer_treatment='retained_asset_control_and_financing_obligation_not_asset_sale',instrument_key='CRWV_anonymous_DCSP_arrangement'))
rows.append(dict(quote="The Company concluded that it was not the primary beneficiary of the DCSP because it lacked the power to direct the activities that most significantly impact the DCSP's economic performance.",model_quantity='DCSP_VIE_nonconsolidation_judgment',issuer_treatment='unconsolidated_VIE_no_power_over_significant_activities',instrument_key='CRWV_anonymous_DCSP_arrangement'))
rows.append(dict(quote="This funding commitment is not subject to a contractual cap; however, the Company estimates the remaining funding obligation to be not material. Amounts funded under this commitment are recoverable from the DCSP only through contingent, unsecured reimbursement rights.",model_quantity='DCSP_uncapped_remaining_funding_commitment',block='contractual_outflows',category_id='uncalled_commitment',component_kind='support_commitment_contractual',stage='signed',issuer_treatment='uncapped_completion_funding_with_contingent_unsecured_recovery',instrument_key='CRWV_anonymous_DCSP_arrangement',flag_unknown_reason='not_material_estimate_not_zero_or_contractual_cap_no_amount_inferred'))
save(k,rows)
