from extension_authoring import save,tagged
k='ee99212ff6ac49136b49de5c03a20f9e670a5b88dd5a4deca009a1af5d298854'
q='Our maximum potential liability under the Backstop upon the deployment of all AI racks, on an undiscounted basis, was approximately $29 billion.'
rows=[tagged(k,17,q,amount_qualifier='approximately',model_quantity='AI_rack_lease_backstop_maximum_potential_liability',amount_nature='maximum_after_all_racks_deployed_not_current_backstop_draw_or_fair_value',block='contingent_obligations',category_id='capacity_backstop',component_kind='guarantee_cap',measurement_basis='undiscounted_maximum_upon_full_deployment',conditionality='conditional',trigger_description='In the event of a lease default by the customer',trigger_occurred='unknown',instrument_key='AVGO_anonymous_AI_racks_2026_backstop',judgment_sensitive=True,flag_unknown_reason='customer_and_financial_partner_unnamed_default_not_established')]
rows.append(dict(quote='No amounts have been paid under the Backstop.',model_quantity='backstop_actual_payment_statement',period_end='2026-08-02',instrument_key='AVGO_anonymous_AI_racks_2026_backstop',issuer_treatment='no_backstop_payments_not_no_contingent_exposure'))
q='In connection with lease agreements that enable access to compute capacity, our customer may, under certain circumstances and if needed, issue to us convertible promissory notes up to an aggregate principal amount of $42 billion.'
rows.append(tagged(k,18,q,amount_qualifier='up_to',model_quantity='uncommitted_customer_convertible_note_facility_cap',amount_nature='uncommitted_conditional_notes_cap_not_cash_paid_or_outstanding_notes',measurement_basis='uncommitted_facility_cap',conditionality='conditional',trigger_description='under certain circumstances and if needed',instrument_key='AVGO_anonymous_AI_compute_customer_notes',flag_unknown_reason='anonymous_customer_unspecified_conditions_no_issued_notes_or_actual_cash_advance'))
rows.append(dict(quote='The notes are subject to various conditions, including the requirement to use the notes or proceeds from the notes, if any, solely for the customer’s obligations under the lease agreements.',model_quantity='financing_use_condition_linked_to_capacity_leases',conditionality='conditional',trigger_description='solely for the customer’s obligations under the lease agreements',instrument_key='AVGO_anonymous_AI_compute_customer_notes',flag_unknown_reason='customer_not_named_cannot_establish_named_L2_pair'))
rows.append(dict(quote='As of August 2, 2026, no notes have been issued to us.',model_quantity='customer_convertible_notes_outstanding_statement',period_end='2026-08-02',instrument_key='AVGO_anonymous_AI_compute_customer_notes',issuer_treatment='no_issued_notes'))
rows.append(dict(quote='Purchase commitments exclude agreements that are cancelable without penalty and unconditional purchase commitments with a remaining term of one year or less.',model_quantity='purchase_obligation_scope',block='contractual_outflows',category_id='purchase_obligation',measurement_basis='unconditional_remaining_term_over_one_year',flag_unknown_reason='not_total_short_term_purchase_obligations_counterparties_unnamed'))
save(k,rows)
