from extension_authoring import save,tagged
k='f86a04ce606e914b6c45895b9d469c0c701dd549ddb9754d475a04e1699ef73d'
save(k,[
tagged(k,0,'As of June 30, 2026, expected future fixed or guaranteed commitments under these agreements were $707.0 billion, the significant majority of which related to long-term supply agreements.',model_quantity='long_term_purchase_commitment_scope',amount_nature='future_fixed_or_guaranteed_purchases_not_current_cash_payments_or_AI_only',block='contractual_outflows',category_id='purchase_obligation',component_kind='purchase',measurement_basis='future_fixed_or_guaranteed_commitments',stage='signed',instrument_key='GOOGL_anonymous_supply_energy_content_commitments',flag_unknown_reason='aggregate_counterparties_unnamed_duration_tag_not_cash_flow'),
dict(quote='The energy service agreements include terms ranging from two to 26 years, with obligations through 2054, and generally include take-or-pay provisions for minimum quantities of energy supply and substantive termination fees.',model_quantity='energy_take_or_pay_commitment_terms',block='contractual_outflows',category_id='take_or_pay',issuer_treatment='energy_minimum_quantities_and_termination_fees_not_all_commitments_fulfilled_by_2030',flag_unknown_reason='energy_subtotal_not_allocated_from_707bn'),
tagged(k,2,'As of June 30, 2026, our maximum potential amount of future payments under these guarantees was $7.6 billion, upon which we may receive certain assets.',model_quantity='energy_equipment_backstop_maximum_exposure',amount_nature='conditional_future_guarantee_cap_not_actual_payment',block='contingent_obligations',category_id='guarantee',component_kind='guarantee_cap',measurement_basis='maximum_potential_future_payments',stage='signed',family='credit_support',link_type='backstop',conditionality='conditional',instrument_key='GOOGL_anonymous_energy_equipment_backstop',flag_unknown_reason='counterparties_unnamed_fair_value_not_material_does_not_mean_cap_zero_distinct_from_credit_derivative_notional'),
dict(quote='It is not possible to make a reasonable estimate of the maximum potential amount under these indemnification agreements due to the unique facts and circumstances involved in each particular agreement.',model_quantity='indemnification_maximum_exposure_estimation_limit',block='contingent_obligations',category_id='indemnification',flag_unknown_reason='unestimated_maximum_not_zero_no_material_claims_does_not_establish_no_exposure'),
tagged(k,6,'$5.2 billion',model_quantity='subsequent_regulatory_fine_cash_payment_scope',amount_nature='July_regulatory_fine_and_interest_cash_not_AI_financing_or_guarantee_call',stage='settled',event_type='payment',flag_unknown_reason='payment_day_undisclosed_not_June_cash_flow'),
dict(quote='which we recognized in the second quarter of 2026. We appealed the decision.',model_quantity='PriceRunner_damages_recognition_period',issuer_treatment='July_court_decision_damages_recognized_in_second_quarter_not_cash_paid',flag_unknown_reason='2point1bn_tag_subsequent_July_period_differs_from_explicit_Q2_recognition_do_not_silently_redate_fact'),
])
