from extension_authoring import save,tagged
k='730f0da7848bf6a02b773e9c26a453446d6f543cb3512688617ace16c818f33f'
rows=[]
anth=dict(counterparty='Anthropic',counterparty_evidence='named')
op=dict(counterparty='OpenAI',counterparty_evidence='named')
fund=dict(payer='AMZN',family='financing',stage='drawn_or_paid',event_type='funding',measurement_basis='cash_paid_primary')
q='Anthropic — From Q3 2023 to Q4 2025, we invested $8.0 billion in convertible notes from Anthropic, which are classified as available-for-sale and reported at fair value with unrealized gains and losses included in “Accumulated other comprehensive income (loss)” and as Level 3 assets.'
rows.append(tagged(k,53,q,**anth,**fund,receiver='Anthropic',link_type='convertible_or_safe',model_quantity='counterparty_primary_cash_financing',amount_nature='historical_multiyear_primary_convertible_note_cash_not_current_balance',instrument_key='AMZN_Anthropic_2023_2025_convertible_notes',flag_unknown_reason='multiyear_flow_not_allocated_to_quarters'))
q='In Q2 2026, we invested $5.0 billion in Anthropic Series G nonvoting preferred stock.'
rows.append(tagged(k,56,q,**anth,**fund,receiver='Anthropic',link_type='equity_primary',model_quantity='counterparty_primary_cash_financing',amount_nature='primary_Series_G_cash_investment_not_mark_to_market',instrument_key='AMZN_Anthropic_Series_G_2026'))
q='Under this financing arrangement, in Q2 2026, we exercised our option to participate in subsequent Anthropic equity financings by investing $5.0 billion in Anthropic Series H nonvoting preferred stock, which reduced the amount available under the facility to $15.0 billion.'
rows.append(tagged(k,59,q,**anth,**fund,receiver='Anthropic',link_type='equity_primary',model_quantity='counterparty_primary_cash_financing',amount_nature='primary_Series_H_cash_draw_under_facility_not_entire_facility',instrument_key='AMZN_Anthropic_Series_H_2026'))
q='Additionally, we entered into a financing arrangement to make available to Anthropic an aggregate facility not to exceed $20.0 billion that will expire 30 months after an Anthropic liquidity event, including an initial public offering (“IPO”).'
rows.append(tagged(k,57,q,amount_qualifier='up_to',**anth,payer='AMZN',receiver='Anthropic',family='financing',link_type='convertible_or_safe',stage='signed',event_type='commitment',model_quantity='named_conditional_financing_facility_cap',amount_nature='aggregate_facility_cap_not_cash_paid_or_current_available_amount',block='contractual_outflows',category_id='uncalled_commitment',component_kind='support_commitment_contractual',measurement_basis='aggregate_facility_cap',instrument_key='AMZN_Anthropic_2026_delivery_linked_facility'))
q='Under this financing arrangement, in Q2 2026, we exercised our option to participate in subsequent Anthropic equity financings by investing $5.0 billion in Anthropic Series H nonvoting preferred stock, which reduced the amount available under the facility to $15.0 billion.'
rows.append(tagged(k,60,q,**anth,stage='available',model_quantity='named_facility_remaining_limit',amount_nature='remaining_financing_facility_limit_not_cash_paid',block='contractual_outflows',category_id='uncalled_commitment',component_kind='support_commitment_contractual',measurement_basis='remaining_facility_limit',instrument_key='AMZN_Anthropic_2026_delivery_linked_facility'))
rows.append(dict(quote='At inception, there is no amount available to be drawn against and as we reach certain delivery milestones of compute capacity under the amended commercial arrangement, amounts under this facility are made available for Anthropic to draw upon at its discretion.',**anth,model_quantity='financing_tranches_linked_to_compute_delivery',stage='signed',instrument_key='AMZN_Anthropic_2026_delivery_linked_facility',flag_unknown_reason='L2_terms_observed_issuer_named_in_metadata_but_no_two_legal_party_names_in_same_quote'))
q='We recorded upward adjustments of approximately $50.5 billion in Q2 2026 and $62.8 billion for the six months ended June 30, 2026 to our nonvoting preferred stock in “Other income (expense), net” to reflect observable changes in price related to Anthropic’s fundings.'
for i in [61,62]:rows.append(tagged(k,i,q,amount_qualifier='approximately',**anth,model_quantity='investment_gain_loss',amount_nature='Anthropic_preferred_observable_price_upward_adjustment_not_primary_cash',stage='recognized',event_type='observable_price_adjustment',measurement_basis='earnings_price_adjustment',instrument_key='AMZN_Anthropic_preferred_stock',issuer_treatment='ASC321_measurement_alternative_Level3',flag_unknown_reason='gain_attributed_Anthropic_but_same_round_price_setting_participation_not_explicitly_established'))
q='As of December 31, 2025 and June 30, 2026, the amounts recorded on our consolidated balance sheets for nonvoting preferred stock were approximately $14.8 billion and $92.5 billion.'
for i in [63,64]:rows.append(tagged(k,i,q,amount_qualifier='approximately',**anth,payer='AMZN',receiver='Anthropic',family='financing',link_type='equity_primary',model_quantity='investee_equity_carrying_amount',amount_nature='outstanding_preferred_stock_carrying_value_not_cash_paid',block='exposed_assets',measurement_basis='carrying_value',component_kind='interest_held',stage='recognized',instrument_key='AMZN_Anthropic_preferred_stock',issuer_treatment='ASC321_measurement_alternative_Level3'))
q='As of December 31, 2025 and June 30, 2026, the estimated fair value of our convertible notes recorded on our consolidated balance sheets was approximately $45.8 billion and $97.9 billion, and the associated unrealized gain included in “Accumulated other comprehensive income (loss)” was $39.5 billion and $92.0 billion.'
for i in [65,66]:rows.append(tagged(k,i,q,amount_qualifier='approximately',**anth,payer='AMZN',receiver='Anthropic',family='financing',link_type='convertible_or_safe',model_quantity='investee_convertible_note_carrying_amount',amount_nature='convertible_notes_fair_value_not_cumulative_cash_funding',block='exposed_assets',measurement_basis='fair_value',component_kind='interest_held',stage='recognized',instrument_key='AMZN_Anthropic_convertible_notes',issuer_treatment='ASC320_available_for_sale_Level3'))
for i in [67,68]:rows.append(tagged(k,i,q,**anth,model_quantity='investee_unrealized_gain_in_OCI',amount_nature='OCI_unrealized_gain_not_period_pretax_earnings_or_cash',stage='recognized',measurement_basis='accumulated_other_comprehensive_income',instrument_key='AMZN_Anthropic_convertible_notes'))
q='We also invested $15.0 billion in Series C Preferred Stock of OpenAI and entered into an equity commitment letter agreement (the “Letter Agreement”), pursuant to which we agreed to purchase additional shares of Series C Preferred Stock (the “Commitment Shares”) with an aggregate purchase price of $35.0 billion (the “Commitment Amount”).'
rows.append(tagged(k,69,q,**op,**fund,receiver='OpenAI',link_type='equity_primary',model_quantity='counterparty_primary_cash_financing',amount_nature='Q1_primary_Series_C_cash_investment_not_total_signed_commitment',instrument_key='AMZN_OpenAI_Series_C_2026'))
rows.append(tagged(k,70,q,**op,payer='AMZN',receiver='OpenAI',family='financing',link_type='equity_primary',stage='signed',event_type='commitment',model_quantity='named_equity_funding_commitment_original',amount_nature='original_additional_equity_commitment_not_cash_paid_or_unfunded_at_June30',block='contractual_outflows',category_id='uncalled_commitment',component_kind='support_commitment_contractual',measurement_basis='original_signed_commitment',instrument_key='AMZN_OpenAI_Series_C_2026'))
q='In Q2 2026, we invested $13.7 billion of the Commitment Amount in Series C Preferred Stock.'
rows.append(tagged(k,71,q,**op,**fund,receiver='OpenAI',link_type='equity_primary',model_quantity='counterparty_primary_cash_financing',amount_nature='Q2_cash_installment_of_existing_Series_C_commitment_not_new_separate_commitment',instrument_key='AMZN_OpenAI_Series_C_2026'))
q='We account for our $28.7 billion investment in Series C Preferred Stock recorded on our consolidated balance sheet as of June 30, 2026, and the remaining Commitment Amount as a component of our equity investments in private companies not accounted for under the equity-method, with future adjustments for observable changes in prices or impairments representing Level 3 fair value measurements recognized in “Other income (expense), net” on our consolidated statements of operations.'
rows.append(tagged(k,72,q,**op,payer='AMZN',receiver='OpenAI',family='financing',link_type='equity_primary',model_quantity='investee_equity_carrying_amount',amount_nature='outstanding_Series_C_stock_not_additional_cash_flow',block='exposed_assets',measurement_basis='carrying_value',component_kind='interest_held',stage='recognized',instrument_key='AMZN_OpenAI_Series_C_2026',issuer_treatment='ASC321_measurement_alternative_Level3'))
q='Subsequent to June 30, 2026, we invested the remaining $21.3 billion Commitment Amount in shares of Series C Preferred Stock of OpenAI.'
rows.append(tagged(k,73,q,**op,**fund,receiver='OpenAI',link_type='equity_primary',model_quantity='counterparty_primary_cash_financing',amount_nature='subsequent_remaining_commitment_cash_installment_not_Q2_cash',instrument_key='AMZN_OpenAI_Series_C_2026',flag_unknown_reason='exact_day_not_disclosed_tagged_July_interval_preserved'))
rows.append(dict(quote='We also amended our commercial arrangement primarily for the provision of AWS cloud services, which includes contractual obligations related to the performance of AWS chips.',**anth,payer='Anthropic',receiver='AMZN',family='commercial',link_type='purchase_commitment',stage='signed',model_quantity='named_cloud_service_commercial_arrangement',instrument_key='AMZN_Anthropic_2026_cloud_arrangement',flag_unknown_reason='no_recognized_customer_revenue_amount_in_this_note'))
rows.append(dict(quote='OpenAI — In Q1 2026, we and OpenAI entered into (i) a commercial arrangement primarily for the provision of AWS cloud services, which includes the use and performance of AWS chips, and (ii) a joint collaboration agreement pursuant to which certain services using OpenAI models will be made available to the Company and on AWS.',**op,payer='OpenAI',receiver='AMZN',family='commercial',link_type='purchase_commitment',stage='signed',model_quantity='named_cloud_service_commercial_arrangement',instrument_key='AMZN_OpenAI_2026_cloud_arrangement',flag_unknown_reason='commercial_commitment_not_recognized_customer_revenue'))
rows.append(dict(quote='Certain of our investments, including our investments in Anthropic and OpenAI, represent a variable interest in entities that we do not consolidate because we are not the primary beneficiary.',model_quantity='named_investee_nonconsolidation_policy',issuer_treatment='vie_unconsolidated',flag_unknown_reason='maximum_exposure_carried_assets_and_future_commitments_no_single_additive_total'))
save(k,rows)
