from extension_authoring import save,tagged

k='fdb95c83fd78554b833eae5cfdc8351d48a1ceb8087fbd963172292ba4ea3763'
q="During the six months ended June 30, 2026, the Company committed to invest up to $1.7 billion, which includes incremental funding commitments of approximately $500 million during the three months ended June 30, 2026, to acquire equity interests in two separate joint ventures that each hold a data center development project."
rows=[tagged(k,0,q,amount_qualifier='up_to',model_quantity='jv_funding_commitment',amount_nature='total_two_JV_funding_commitment_not_cash_paid',block='contractual_outflows',category_id='jv_funding_commitment',measurement_basis='funding_commitment_cap',component_kind='support_commitment_contractual',counterparty_evidence='anonymous',stage='signed',instrument_key='CRWV_2026_two_development_JVs'),tagged(k,1,q,amount_qualifier='approximately',model_quantity='jv_funding_commitment_incremental',amount_nature='incremental_Q2_commitment_included_in_total_not_additive',counterparty_evidence='anonymous',stage='signed',instrument_key='CRWV_2026_two_development_JVs')]
rows.append(dict(quote="As of June 30, 2026, the Company was not the primary beneficiary of these VIEs and did not consolidate them, as it lacked the power to direct the activities that most significantly impact the VIEs' economic performance.",model_quantity='investment_consolidation_policy',issuer_treatment='vie_unconsolidated',counterparty_evidence='anonymous',instrument_key='CRWV_2026_two_development_JVs'))
rows.append(dict(quote='Upon formation, the third-party infrastructure developer obtained an 85% equity interest in the JV, while the Company held the remaining 15% equity interest, for which the Company contributed net assets worth $57 million.',model_quantity='JV_original_nonmonetary_contribution',counterparty_evidence='anonymous',event_type='noncash_contribution',stage='recognized',instrument_key='CRWV_2025_NJ_development_JV',flag_unknown_reason='developer_and_JV_legal_names_not_disclosed_in_note'))
rows.append(dict(quote='The Company also entered into a data center lease agreement with the JV in June 2025 which will commence upon completion of construction. Once commenced, the lease will have an initial lease term of 15 years with base rent payments that are based on a percentage of construction costs incurred.',model_quantity='joint_venture_forward_starting_lease_terms',family='commercial',link_type='capacity_lease',counterparty_evidence='anonymous',stage='signed',instrument_key='CRWV_2025_NJ_development_JV_lease',flag_unknown_reason='lease_not_yet_commenced_named_counterparty_and_fixed_total_not_disclosed'))
q="The Company's maximum exposure to loss with respect to the JV includes (i) the carrying value of the Company's investment, (ii) up to $95 million related to a guarantee for certain contingent consideration payable to a third-party by the JV upon the achievement of certain milestones, (iii) lease prepayment of $37 million, and (iv) potential requirements to fund the construction and development of the data center campus to the extent the JV is unable to secure third-party financing."
rows.append(tagged(k,13,q,amount_qualifier='up_to',model_quantity='JV_contingent_consideration_guarantee_cap',amount_nature='conditional_guarantee_cap_not_paid_financing_or_JV_debt',block='contingent_obligations',category_id='guarantee',measurement_basis='maximum_guarantee_cap',component_kind='guarantee_cap',counterparty_evidence='anonymous',conditionality='conditional',trigger_description='upon the achievement of certain milestones',trigger_occurred='unknown',stage='signed',instrument_key='CRWV_2025_NJ_development_JV_guarantee'))
rows.append(tagged(k,14,q,model_quantity='JV_lease_prepayment',amount_nature='lease_prepayment_asset_in_maximum_exposure_not_equity_cash_funding',counterparty_evidence='anonymous',family='commercial',link_type='prepayment',stage='recognized',instrument_key='CRWV_2025_NJ_development_JV_lease'))
q='Based on current projected development costs and third-party financing secured by the JV as of June 30, 2026, the Company estimated that the maximum funding exposure to fund construction and development costs is up to $160 million.'
rows.append(tagged(k,15,q,amount_qualifier='up_to',model_quantity='JV_conditional_construction_funding_cap',amount_nature='estimated_maximum_funding_exposure_not_fixed_debt_or_cash',block='contingent_obligations',category_id='jv_funding_commitment',measurement_basis='estimated_maximum_funding_cap',component_kind='support_commitment_contractual',counterparty_evidence='anonymous',conditionality='conditional',trigger_description='to the extent the JV is unable to secure third-party financing',trigger_occurred='unknown',stage='signed',instrument_key='CRWV_2025_NJ_development_JV'))
rows.append(dict(quote='Our strategic investments primarily consist of non-marketable equity securities accounted for under the measurement alternative, which are investments in privately-held companies without readily determinable market values and classified within Level 3 of the fair value hierarchy.',model_quantity='investment_measurement_policy',issuer_treatment='ASC321_measurement_alternative',counterparty_evidence='anonymous'))
rows.append(dict(quote='Notes receivable are primarily related to the DCSP Financing Arrangements (as defined in Note 10—Debt) and are reported at their amortized cost basis.',model_quantity='DCSP_notes_receivable_measurement_policy',issuer_treatment='amortized_cost',counterparty_evidence='anonymous',instrument_key='CRWV_DCSP_financing_arrangements',flag_unknown_reason='counterparty_names_and_DCSProgram_structure_require_debt_note'))
save(k,rows)
