from extension_authoring import save

k='d233b411c98272632bc6f50f8e2ce459873b5398b8cad887297c1afa35c25c1e'
save(k,[dict(quote='The Company has investments accounted for under the equity method, which are considered related parties.',model_quantity='investment_consolidation_policy',counterparty_evidence='anonymous',issuer_treatment='equity_method'),dict(quote='The Company has no obligation to fund these investees.',model_quantity='equity_method_investee_funding_obligation_absence',counterparty_evidence='anonymous',flag_unknown_reason='explicit_absence_of_funding_obligation_not_absence_of_historical_funding_or_current_asset'),dict(quote='The Company also has a $100 million term loan receivable outstanding from one of the investees as of June 27, 2026 and December 27, 2025, bearing interest at a variable rate plus a margin payable quarterly and maturing in October 2026, recorded with related interest receivable within Prepaid expenses and other current assets on the Company’s Consolidated Balance Sheets.',model_quantity='related_investee_term_loan_terms',counterparty_evidence='anonymous',family='financing',link_type='loan_or_facility',stage='recognized',flag_unknown_reason='individual_investee_not_named_in_note_candidate_context_date_is_2024_10_09_not_current_balance')])

k='cbfe1fe6a6f0434eb31ca829179b58f44a4c5f909c214b6d93504fcd420b4ffd'
save(k,[dict(quote='As of June 30, 2026 and December 31, 2025, the Company held investments in unconsolidated affiliates which are accounted for as equity investments without readily determinable fair values of $237 million and $157 million, respectively.',model_quantity='investment_measurement_policy',issuer_treatment='ASC321_measurement_alternative_unconsolidated',counterparty_evidence='anonymous'),dict(quote='The Company recorded a gain from observable price changes of $70 million on these investments during the three months ended June 30, 2026.',model_quantity='investment_observable_price_adjustment_disclosed',counterparty_evidence='anonymous',event_type='observable_price_adjustment',flag_unknown_reason='investee_identity_and_price_setting_participation_not_disclosed_amount_already_tagged')])

k='b9d3a0db09c1a193e6a58a1bdc5bd16950d125bdd86f235eb1b5fb6fd6786f6b'
save(k,[dict(quote='The fair value of these digital assets is determined using Level I in the fair value hierarchy.',model_quantity='digital_asset_measurement_policy',issuer_treatment='fair_value_Level1',counterparty_evidence='anonymous'),dict(quote='The Company’s assets that are measured at fair value on a recurring basis consist of the following:',abstained=True,abstention_reason='Tagged recurring fair-value table contains no named commercial or financing counterparty; cost-to-fair-value differences do not establish a period earnings effect.')])
